'use strict';
const fs=require('node:fs'),vm=require('node:vm'),cp=require('node:child_process'),assert=require('node:assert/strict');
const {harness,freeGame,copy}=require('./verify-ui-integration');
const Scene=require('../src/scene'),A=require('../src/art'),I=require('../src/icons'),checks=[];
const phone=()=>harness({}, {width:390,height:844,coarse:true});
async function check(name,fn){try{await fn();checks.push({name,ok:true});}catch(e){checks.push({name,ok:false,error:e.stack});console.error(name,e.message);}}
const keys=html=>new Set(Array.from(html.matchAll(/data-cell="([^"]+)"/g),m=>m[1]));
function size(html){return {cells:keys(html).size,nodes:(html.match(/<[a-z][\w:-]*\b/g)||[]).length,images:(html.match(/<image /g)||[]).length,masks:(html.match(/<mask /g)||[]).length,clipPaths:(html.match(/<clipPath /g)||[]).length,bytes:Buffer.byteLength(html)};}
function time(b){for(let i=0;i<3;i++)b.board();const times=[];for(let i=0;i<15;i++){const start=performance.now();b.board();times.push(performance.now()-start);}times.sort((a,b)=>a-b);return +times[7].toFixed(3);}
(async()=>{
 await check('Viewport margin covers every hex intersecting the screen at all supported profiles',()=>{for(const [w,h] of [[320,568],[390,844],[844,390],[1300,800]])for(const zoom of [220,500,1250,6000]){const camera={x:197,y:-93,width:zoom},box=Scene.extent(camera,w,h),map=[];for(let q=-20;q<=20;q++)for(let r=-20;r<=20;r++)map.push({q,r});const xy=c=>({x:Math.sqrt(3)*44*(c.q+c.r/2),y:66*c.r}),drawn=new Set(Scene.cells(map,box,xy).map(c=>c.q+','+c.r));for(const c of map){const p=xy(c);if(Math.abs(p.x-camera.x)<zoom/2+44&&Math.abs(p.y-camera.y)<zoom*h/w/2+44)assert(drawn.has(c.q+','+c.r));}assert(Scene.contains(box,camera,w,h));assert(!Scene.contains(box,{...camera,x:camera.x+Scene.margin},w,h));}});
 await check('Drag within the guard buffer writes only the camera; a long pan updates the SVG scene without replacing HUD',async()=>{const h=phone();await freeGame(h);const board=h.document.getElementById('board'),scene=h.document.getElementById('board-scene'),writes=scene.writes,appWrites=h.document.app.writes;for(let i=0;i<20;i++){h.ui.camera.x+=1;h.battle.applyCamera();}assert.equal(scene.writes,writes);h.ui.camera.x+=500;h.battle.applyCamera();assert.equal(scene.writes,writes+1);assert.equal(h.document.getElementById('board'),board);assert.equal(h.document.app.writes,appWrites);assert(keys(scene.innerHTML).size>0);});
 await check('Repeated wheel events coalesce into one animation frame and do not redraw the HUD',async()=>{const h=phone();await freeGame(h);const frames=[],board=h.document.getElementById('board'),before=board.getAttribute('viewBox'),writes=h.document.app.writes;h.context.requestAnimationFrame=fn=>{frames.push(fn);return 987;};const wheel=board.listeners.get('wheel')[0];for(let i=0;i<8;i++)wheel({preventDefault(){},clientX:180,clientY:400,deltaY:-1});assert.equal(frames.length,1);assert.equal(board.getAttribute('viewBox'),before);frames[0]();assert.notEqual(board.getAttribute('viewBox'),before);assert.equal(h.document.app.writes,writes);});
 await check('An active effect keeps its source scene alive during camera movement',async()=>{const h=phone();await freeGame(h);const scene=h.document.getElementById('board-scene'),writes=scene.writes;h.ui.busy=true;h.ui.camera.x+=500;h.battle.applyCamera();assert.equal(scene.writes,writes);h.ui.busy=false;h.battle.applyCamera();assert.equal(scene.writes,writes+1);});
 await check('Shared board clip avoids per-cell SVG definitions and every normal map unit uses one image',async()=>{const h=phone();await freeGame(h);h.ui.game.settings.fog=false;h.ui.camera.width=500;const html=h.battle.board(),stats=size(html),units=(html.match(/data-unit-sprite=/g)||[]).length;assert.equal(stats.clipPaths,1);assert.equal(stats.masks,0);assert.equal(stats.images,units);assert(!html.includes('data-building-health='));});
 await check('Overview uses native unit emblems and preserves every visible seat, HP and AP marker',async()=>{const h=phone();await freeGame(h);h.ui.game.settings.fog=false;h.ui.camera.width=6000;const html=h.battle.board();assert.equal(size(html).cells,h.ui.game.cells.length);assert.equal(size(html).images,0);for(const u of h.ui.game.units)assert(html.includes('data-unit-sprite="'+u.id+'"'));});
 await check('Selecting a structure shows current HP in the corner; closing or clearing prevents persistent labels',async()=>{const h=phone();await freeGame(h);const G=h.context.Game,s=h.ui.game,b=s.buildings.find(b=>b.owner===s.actor&&G.hasBuildingHealth(b));s.units=s.units.filter(u=>u.q!==b.q||u.r!==b.r);b.hp-=20;G.vision(s);h.battle.touchCell(b.q,b.r);const card=h.document.getElementById('facility-health');assert(card);assert.equal(Number(card.dataset.hp),b.hp);await h.click('[data-action="health-close"]');assert.equal(h.document.getElementById('facility-health'),null);h.env.render();assert.equal(h.document.getElementById('facility-health'),null);h.battle.touchCell(b.q,b.r);assert(h.document.getElementById('facility-health'));await h.action('clear');assert.equal(h.document.getElementById('facility-health'),null);assert(!h.battle.board().includes('data-building-health='));});
 await check('A guarded building attack updates the corner during playback and the close button remains usable',async()=>{const h=phone();await freeGame(h);const G=h.context.Game,s=h.ui.game,H=h.context.Hex,b=s.buildings.find(b=>b.type==='factory'&&b.owner!==s.actor),near=H.neighbors(b).map(c=>G.cell(s,c)).find(c=>c&&Number.isFinite(H.cost('tank',c)));s.settings.fog=false;s.units=s.units.filter(u=>!([b,near].some(c=>u.q===c.q&&u.r===c.r)));const a=G.normalizeUnit({id:'ART_ATTACK',type:'tank',owner:s.actor,q:near.q,r:near.r}),guard=G.normalizeUnit({id:'ART_GUARD',type:'infantry',owner:b.owner,q:b.q,r:b.r});s.units.push(a,guard);G.vision(s);h.battle.focusUnit(a.id);const hp=b.hp,guardHp=guard.hp;const promise=h.env.act({kind:'attack',unitId:a.id,targetId:b.id});await h.flush();assert(h.ui.busy);assert(b.hp<hp&&guard.hp<guardHp);const card=h.document.getElementById('facility-health');assert(card);assert.equal(Number(card.dataset.hp),b.hp);await h.click('[data-action="health-close"]');assert.equal(h.ui.healthHidden,b.id);await h.finish();await promise;assert.equal(h.document.getElementById('facility-health'),null);assert.equal(h.executed.length,1);});
 await check('Esc clears recent damage and a new game cannot inherit another observer’s health card',async()=>{const h=phone();await freeGame(h);const s=h.ui.game,b=s.buildings.find(b=>b.owner===s.actor&&h.context.Game.hasBuildingHealth(b));h.ui.healthNotice={id:b.id,viewer:h.env.viewer(),actor:s.actor,round:s.round};h.env.render();assert(h.document.getElementById('facility-health'));await h.key('Escape');assert.equal(h.document.getElementById('facility-health'),null);await freeGame(h);assert.equal(h.ui.healthNotice,null);});
 await check('Resource buildings expose no structure card and fog only displays the cached HP',async()=>{const h=phone();await freeGame(h);const G=h.context.Game,s=h.ui.game,resource=s.buildings.find(b=>b.type==='city'&&b.owner===s.actor);h.ui.tile=G.cell(s,resource);assert.equal(h.battle.buildingHealth(),'');const b=s.buildings.find(b=>b.owner!==s.actor&&G.hasBuildingHealth(b));G.vision(s);const id=h.env.viewer();s.knownBuildings[id][b.id]=copy(b);s.settings.fog=true;s.vision[id]={ground:[],air:[]};h.ui.tile=G.cell(s,b);const old=h.battle.buildingHealth();assert(old.includes('最后观测'));b.hp=1;assert.equal(h.battle.buildingHealth(),old);});
 await check('The 37 instrument illustrations are self-contained and eight active skill artworks differ',()=>{assert.equal(I.names.length,37);const skills=new Set();for(const name of I.names){const svg=I.svg(name);assert(svg.includes('data-art="cel-instrument"'));assert(!/<image|<filter|<text|currentColor/.test(svg));assert.equal(svg,fs.readFileSync('assets/interface/'+name+'.svg','utf8'));}for(const name of Object.values(I.skills))skills.add(I.svg(name).replace(/data-icon="[^"]+"/,'data-icon="skill"'));assert.equal(skills.size,8);});
 await check('Continuous terrain has no internal boundary; coastline carries shallow gradient and ruins carry vines/crystals',()=>{for(const terrain of ['plain','ocean','ridge']){const cell={q:0,r:0,terrain},map=[cell,...[[1,0],[0,1],[-1,1],[-1,0],[0,-1],[1,-1]].map(([q,r])=>({q,r,terrain}))];assert(!A.terrainMarkupContext(cell,map).includes('terrain-boundary'));}assert(A.terrainMarkup('coast').includes('radialGradient'));const ruins=A.terrainMarkup('ruins');assert(ruins.includes('ruin-vines')&&ruins.includes('ruin-crystals'));for(const cell of [{q:0,r:0,terrain:'ocean'},{q:1,r:1,terrain:'ocean'}]){const x=Math.sqrt(3)*44*(cell.q+cell.r/2),y=66*cell.r,svg=A.terrainMarkupContext(cell,[cell]);for(const wave of svg.matchAll(/<path d="M([^"]+)" fill="none" stroke="#cee7df"/g)){for(const pair of wave[1].split('L')){const [dx,dy]=pair.split(',').map(Number),ax=x+dx,ay=y+dy-1.65*Math.sin(ax/10);assert(Math.abs(ax/12-Math.round(ax/12))<.0001);assert(Math.abs(ay/28-Math.round(ay/28))<.0001);}}}});
 await check('Only core structures use armor decks/shield insignia; animation count is bounded and respects pause/reduced mode',async()=>{for(const type of ['hq','barracks','factory','port','airfield']){assert(A.buildingTileMarkup(type,'union').includes('core-platform'));assert(A.buildingMarkup(type,'union').includes('core-shield'));}for(const type of ['city','market','energyfield','energyplatform']){assert(A.buildingTileMarkup(type,'union').includes('resource-plot'));assert(!A.buildingMarkup(type,'union').includes('core-shield'));}const h=phone();await freeGame(h);h.ui.game.settings.fog=false;const html=h.battle.board();assert((html.match(/class="facility-beacon /g)||[]).length<=5);const css=fs.readFileSync('world.css','utf8');assert(css.includes('.is-paused .facility-beacon'));assert(css.includes('@media(prefers-reduced-motion:reduce)'));});
 const benchmarks=[];
 await check('Large map reduces generated SVG work relative to the published v1.1.3 scene',async()=>{const h=phone();await h.action('free');await h.change('[data-setting="size"]','L');await h.change('[data-setting="fog"]','false');await h.click('[data-action="preview"]');await h.click('[data-action="start-free"]');await h.click('[data-action="close"]');const s=h.ui.game;assert.equal(s.cells.length,919);const newModules={art:h.context.GameArt,anime:h.context.GameAnime,battle:h.context.GameBattleUI};let old=null;try{for(const name of ['anime','art','battle-ui'])vm.runInContext(cp.execFileSync('git',['show','65009692669e69d91da8de3d9d6e92d77c5022d3:src/'+name+'.js'],{encoding:'utf8'}),h.context);old=h.context.GameBattleUI.create({...h.env,A:h.context.GameArt});}catch(e){console.warn('Baseline Git object unavailable; new scene budget still verified.');}const oldModules={art:h.context.GameArt,anime:h.context.GameAnime};for(const [label,width] of [['phone-detail',500],['phone-overview',1250]]){const center=h.env.xy(s.buildings.find(b=>b.type==='hq'&&b.owner===s.actor));h.ui.camera={x:center.x,y:center.y,width};let previous=null;if(old){h.context.GameArt=oldModules.art;h.context.GameAnime=oldModules.anime;previous={...size(old.board()),medianGenerationMs:time(old)};}h.context.GameArt=newModules.art;h.context.GameAnime=newModules.anime;h.context.GameBattleUI=newModules.battle;const current={...size(h.battle.board()),medianGenerationMs:time(h.battle)};assert(current.cells<919);assert.equal(current.masks,0);assert.equal(current.clipPaths,1);if(previous){assert(current.nodes<previous.nodes*.75);assert(current.bytes<previous.bytes*.75);}benchmarks.push({label,mapCells:919,cameraWidth:width,viewport:[390,844],previous,current,nodeReductionPercent:previous?+(100*(1-current.nodes/previous.nodes)).toFixed(1):null});}});
 const report={version:'1.1.4',scope:'Isolated controller VM, generated SVG budgets and Node HTML generation timing. Not browser paint/FPS or device layout measurements.',date:new Date().toISOString(),passed:checks.filter(x=>x.ok).length,total:checks.length,benchmarks,checks};fs.writeFileSync('reports/scene-tests-v1.1.4.json',JSON.stringify(report,null,2));console.log(`Scene/health/art: ${report.passed}/${report.total}`);console.log(JSON.stringify(benchmarks,null,2));if(report.passed!==report.total)process.exitCode=1;
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
