const assert=require('node:assert/strict'),fs=require('node:fs');
const D=require('../src/data'),H=require('../src/grid'),M=require('../src/maps'),G=require('../src/game'),C=require('../src/campaign'),S=require('../src/storage'),AI=require('../src/ai'),Content=require('../src/content');
const results=[];function test(id,name,fn){try{fn();results.push({id,name,ok:true});}catch(e){results.push({id,name,ok:false,error:e.stack});console.error(id,name,e.message);}}
function unit(type,owner,q,r,id=type+owner){return G.normalizeUnit({id,type,owner,q,r});}
function fixture(units=[],buildings=[],settings={}){const s=G.create(M.fixed('S',2),{fog:false,...settings});s.cells=[];for(let q=-8;q<=8;q++)for(let r=-8;r<=8;r++)s.cells.push({q,r,terrain:'plain'});s.units=units;s.buildings=buildings;s.players.forEach(p=>{p.resources={money:2500,energy:200};p.ownTurnIndex=p.id==='P1'?1:0;});s.explored={P1:s.cells.map(c=>H.key(c.q,c.r)),P2:s.cells.map(c=>H.key(c.q,c.r))};s.knownBuildings={P1:{},P2:{}};G.vision(s);return s;}
function building(type,owner,q,r,id=type+owner){const d=D.buildingById[type];return G.normalizeBuilding({id,type,owner,q,r,level:1,hp:d.hp,maxHp:d.hp,state:'complete',stock:[],order:null});}
function ok(s,c){const r=G.execute(s,c);assert.equal(r.ok,true,r.error);return r;}
function fail(s,c){const before=JSON.stringify({units:s.units,buildings:s.buildings,resources:s.players.map(p=>p.resources)});assert.equal(G.execute(s,c).ok,false);assert.equal(JSON.stringify({units:s.units,buildings:s.buildings,resources:s.players.map(p=>p.resources)}),before);}
function cycle(s){ok(s,{kind:'end'});ok(s,{kind:'end'});}
test('DATA-01','38 units, ten tier trees, eight specials and eleven AA permissions',()=>{assert.equal(D.units.length,38);assert.equal(D.units.filter(u=>u.system).length,30);assert.equal(D.units.filter(u=>!u.system).length,8);assert.equal(D.units.filter(u=>u.antiAir).length,11);assert.equal(D.units.filter(u=>u.dedicatedAA).length,6);assert.deepEqual([D.byId.infantry.hp,D.byId.infantry.armor,D.byId.infantry.damage],[80,0,30]);assert.ok(D.units.every(u=>Number.isInteger(u.energyPerStep)));});
test('TRN-03 / FC09','First income once and save preserves it',()=>{const s=G.create(M.fixed('S',2));assert.deepEqual(s.players[0].resources,{money:720,energy:74});G.begin(s);const loaded=S.restore(S.pack(s,'test'));assert.deepEqual(loaded.players[0].resources,{money:720,energy:74});assert.equal(loaded.players[0].ownTurnIndex,1);ok(s,{kind:'end'});assert.deepEqual(s.players[1].resources,{money:720,energy:74});});
test('ATK-01','Infantry 40 attack, 20 counter, own counter preserved',()=>{const a=unit('infantry','P1',0,0),b=unit('infantry','P2',1,0),s=fixture([a,b]);assert.deepEqual(G.attackPreview(s,a,b),{damage:40,standard:40,counter:20,targetHp:40,attackerHp:60,counterReason:null,counterRemaining:1,targetId:b.id,buildingId:null,buildingDamage:0,buildingHp:null,counterBuildingId:null,counterBuildingDamage:0,counterBuildingHp:null});ok(s,{kind:'attack',unitId:a.id,targetId:b.id});assert.deepEqual([a.hp,b.hp,a.ap,a.counterRemaining,b.counterRemaining],[60,40,0,1,0]);});
test('ATK-02','Bomber dies to 150 percent AA counter',()=>{const a=unit('lightbomber','P1',0,0),b=unit('antiair','P2',1,0),s=fixture([a,b]);assert.deepEqual([G.attackPreview(s,a,b).damage,G.attackPreview(s,a,b).counter],[50,100]);ok(s,{kind:'attack',unitId:a.id,targetId:b.id});assert.equal(G.unit(s,a.id),undefined);assert.equal(b.hp,50);assert.equal(s.players[1].stats.kills,1);});
test('ATK-03','AA active attack retains its counter, fighter retaliates ten',()=>{const a=unit('antiair','P1',0,0),b=unit('fighter','P2',1,0),s=fixture([a,b]);ok(s,{kind:'attack',unitId:a.id,targetId:b.id});assert.deepEqual([a.hp,b.hp,a.counterRemaining],[90,70,1]);});
test('ATK-04','Six AA standard retaliation values',()=>{const ids=['antiair','missileaa','longrangeaa','aafrigate','aamissileship','areaaship'],values=[90,120,150,90,135,165];ids.forEach((id,i)=>{const a=unit(id,'P1',0,0),t=unit('fighter','P2',1,0),s=fixture([a,t]);if(D.byId[id].branch==='navy')G.cell(s,a).terrain='ocean';assert.equal(Math.floor(G.standardDamage(s,a,t)*1.5),values[i]);});});
test('ATK-05 / ATK-06','AA also retaliates against land and only once',()=>{const a=unit('lighttank','P1',0,0),a2=unit('lighttank','P1',1,-1,'a2'),t=unit('antiair','P2',1,0),s=fixture([a,a2,t]);assert.equal(G.attackPreview(s,a,t).counter,30);ok(s,{kind:'attack',unitId:a.id,targetId:t.id});assert.equal(G.attackPreview(s,a2,t).counter,0);ok(s,{kind:'attack',unitId:a2.id,targetId:t.id});assert.equal(a2.hp,120);});
test('ATK-07','Indirect and lethal attacks cannot trigger AA',()=>{const a=unit('artillery','P1',0,0),t=unit('antiair','P2',2,0),s=fixture([a,t]);assert.equal(G.attackPreview(s,a,t).counter,0);t.hp=10;assert.equal(G.attackPreview(s,a,t).counter,0);});
test('ATK-08','Infantry cannot retaliate to air, ordinary ships use half',()=>{const a=unit('lightbomber','P1',0,0),t=unit('infantry','P2',1,0),s=fixture([a,t]);assert.equal(G.attackPreview(s,a,t).counter,0);const ship=unit('navaldestroyer','P2',1,0);s.units=[a,ship];G.cell(s,ship).terrain='ocean';assert.equal(G.attackPreview(s,a,ship).counter,Math.floor(G.standardDamage(s,ship,a)*.5));});
test('ATK-09','Building and garrison receive one protected attack',()=>{const a=unit('tank','P1',0,0),t=unit('infantry','P2',1,0),b=building('factory','P2',1,0),s=fixture([a,t],[b]);ok(s,{kind:'attack',unitId:a.id,targetId:b.id});assert.equal(t.hp,35);assert.equal(t.counterRemaining,0);assert.equal(a.hp,155);assert.equal(b.hp,185);});
test('ATK-10 / FOG-03','Direct LOS blocked; indirect still requires visibility',()=>{const a=unit('tank','P1',0,0),b=unit('infantry','P2',2,0),s=fixture([a,b]);G.cell(s,{q:1,r:0}).terrain='ridge';fail(s,{kind:'attack',unitId:a.id,targetId:b.id});a.type='artillery';assert.equal(G.attackReason(s,a,b),null);s.settings.fog=true;s.vision.P1={ground:[],air:[]};assert.ok(G.attackReason(s,a,b));});
test('OCC-01 / OCC-02','One unit per cell and blocked air path',()=>{const a=unit('fighter','P1',0,0),b=unit('infantry','P1',1,0),s=fixture([a,b]);fail(s,{kind:'move',unitId:a.id,q:1,r:0});const route=G.movement(s,a).get('2,0');assert.ok(route.path.every(c=>c.q!==1||c.r!==0));});
test('OCC-03 / OCC-04','Building co-location legal and death releases a tile',()=>{const a=unit('infantry','P1',0,0),b=building('city','P1',1,0),s=fixture([a],[b]);ok(s,{kind:'move',unitId:a.id,q:1,r:0});assert.equal(G.occupied(s,b).id,a.id);const t=unit('infantry','P2',2,0);t.hp=10;s.units.push(t);ok(s,{kind:'attack',unitId:a.id,targetId:t.id});assert.equal(G.occupied(s,{q:2,r:0}),undefined);});
test('MOV-01','Two moves share whole-turn budget',()=>{const a=unit('infantry','P1',0,0),s=fixture([a]);ok(s,{kind:'move',unitId:a.id,q:2,r:0});fail(s,{kind:'move',unitId:a.id,q:4,r:0});ok(s,{kind:'move',unitId:a.id,q:3,r:0});assert.equal(a.spentMove,3);});
test('MOV-02','Road bonus and permanent loss when leaving road',()=>{const a=unit('infantry','P1',0,0),s=fixture([a]);for(let q=1;q<=4;q++)G.cell(s,{q,r:0}).terrain='road';ok(s,{kind:'move',unitId:a.id,q:4,r:0});assert.equal(a.spentMove,4);fail(s,{kind:'move',unitId:a.id,q:4,r:1});const b=unit('infantry','P1',0,0),ss=fixture([b]);for(let q=2;q<=4;q++)G.cell(ss,{q,r:0}).terrain='road';ok(ss,{kind:'move',unitId:b.id,q:1,r:0});assert.equal(b.roadEligible,false);fail(ss,{kind:'move',unitId:b.id,q:4,r:0});});
test('MOV-03 / EN02','Rubble two points but one entry energy charge',()=>{const a=unit('tank','P1',0,0),s=fixture([a]);G.cell(s,{q:1,r:0}).terrain='rubble';ok(s,{kind:'move',unitId:a.id,q:1,r:0});assert.equal(a.spentMove,2);assert.equal(s.players[0].resources.energy,198);});
test('MOV-04 / EN04','Amphibious sea/land energy 2/1/1',()=>{const a=unit('amphibious','P1',0,0),s=fixture([a]);s.cells=s.cells.filter(c=>c.r===0&&c.q>=0&&c.q<=3);G.cell(s,{q:1,r:0}).terrain='ocean';G.cell(s,{q:2,r:0}).terrain='coast';ok(s,{kind:'move',unitId:a.id,q:3,r:0});assert.equal(s.players[0].resources.energy,196);assert.equal(H.domain(a,G.cell(s,a)),'land');assert.equal(D.byId[a.type].branch,'navy');});
test('MOV-05','Three artillery cannot fire after moving, battleship can',()=>{for(const type of ['lightartillery','artillery','heavyartillery']){const a=unit(type,'P1',0,0),t=unit('tank','P2',3,0),s=fixture([a,t]);ok(s,{kind:'move',unitId:a.id,q:1,r:0});fail(s,{kind:'attack',unitId:a.id,targetId:t.id});if(type==='artillery')fail(s,{kind:'skill',unitId:a.id,targetId:t.id});}const a=unit('battleship','P1',0,0),t=unit('tank','P2',3,0),s=fixture([a,t]);G.cell(s,a).terrain='ocean';G.cell(s,{q:1,r:0}).terrain='ocean';ok(s,{kind:'move',unitId:a.id,q:1,r:0});ok(s,{kind:'attack',unitId:a.id,targetId:t.id});});
test('CAP-01','All 38 types capture only their own building tile',()=>{for(const d of D.units){const u=unit(d.id,'P1',0,0),b=building('city',null,1,0),s=fixture([u],[b]);if(d.branch==='navy'&&!d.amphibious)G.cell(s,u).terrain='ocean';fail(s,{kind:'capture',unitId:u.id,buildingId:b.id});u.q=b.q;u.r=b.r;ok(s,{kind:'capture',unitId:u.id,buildingId:b.id});assert.equal(b.owner,'P1');assert.equal(u.ap,0);}});
test('CAP-02 / CAP-03','Air garrison blocks; adjacent enemy does not',()=>{const u=unit('infantry','P1',0,0),t=unit('fighter','P2',1,0),b=building('city',null,1,0),s=fixture([u,t],[b]);fail(s,{kind:'capture',unitId:u.id,buildingId:b.id});t.q=2;u.q=b.q;ok(s,{kind:'capture',unitId:u.id,buildingId:b.id});});
test('CAP-04','Move onto building auto-captures, attack then capture fails',()=>{const u=unit('infantry','P1',0,0),b=building('city',null,2,0),s=fixture([u],[b]);ok(s,{kind:'move',unitId:u.id,q:2,r:0});assert.equal(b.owner,'P1');assert.equal(u.ap,0);fail(s,{kind:'capture',unitId:u.id,buildingId:b.id});const ss=fixture([unit('infantry','P1',0,0),unit('infantry','P2',1,0)],[building('city',null,0,1)]);ok(ss,{kind:'attack',unitId:ss.units[0].id,targetId:ss.units[1].id});fail(ss,{kind:'capture',unitId:ss.units[0].id,buildingId:ss.buildings[0].id});});
test('CAP-05 / CAP-06','Capture preserves damaged tier, income waits, stock discarded',()=>{const u=unit('infantry','P1',0,0),b=building('city','P2',1,0),s=fixture([u],[b]);b.level=2;u.q=b.q;const money=s.players[0].resources.money;ok(s,{kind:'capture',unitId:u.id,buildingId:b.id});assert.deepEqual([b.level,b.hp,s.players[0].resources.money],[2,null,money]);cycle(s);assert.equal(s.players[0].resources.money,money+55);const f=building('factory','P2',1,0);f.level=2;f.hp=70;f.order={kind:'unit',type:'infantry'};f.stock=[{id:'a',type:'infantry',sourceId:f.id},{id:'b',type:'infantry',sourceId:f.id}];s.buildings=[f];s.units[0].ap=2;ok(s,{kind:'capture',unitId:u.id,buildingId:f.id});assert.equal(f.order,null);assert.equal(f.stock.length,0);assert.equal(f.level,2);assert.equal(f.hp,70);assert.equal(G.count(s,'P2'),0);assert.equal(G.productionReason(s,f,'lighttank'),null);});
test('WIN-02 / WIN-03','Capture HQ wins; HP zero alone never wins',()=>{const a=unit('fighter','P1',0,0),b=building('hq','P2',1,0,'enemy-hq'),s=fixture([a],[b]);s.players[1].originalHqId=b.id;b.hp=0;a.q=b.q;G.checkVictory(s);assert.equal(s.result,null);ok(s,{kind:'capture',unitId:a.id,buildingId:b.id});assert.equal(s.result.winner,'P1');const money=s.players[0].resources.money;fail(s,{kind:'end'});G.begin(s);assert.equal(s.players[0].resources.money,money);});
test('WIN-04 / WIN-05','All buildings includes neutral platform and ruins',()=>{const a=unit('fighter','P1',0,0),hq=building('hq','P1',3,0),last=building('energyplatform',null,1,0),s=fixture([a],[hq,last],{victoryMode:'own_all_registered_buildings'});G.cell(s,last).terrain='ocean';a.q=last.q;G.checkVictory(s);assert.equal(s.result,null);ok(s,{kind:'capture',unitId:a.id,buildingId:last.id});assert.equal(s.result.winner,'P1');assert.equal(last.hp,null);});
test('WIN-06 / ECO-04','Foundation registered immediately, damage carried through completion',()=>{const hq=building('hq','P1',0,0),s=fixture([],[hq]),money=s.players[0].resources.money;ok(s,{kind:'construct',type:'factory',q:1,r:0});const b=s.buildings[1];assert.equal(b.hp,100);assert.equal(s.buildings.length,2);assert.equal(s.players[0].resources.money,money-180);b.hp=60;cycle(s);assert.deepEqual([b.state,b.hp,b.maxHp],['complete',160,200]);assert.equal(s.players[0].resources.money,money-180+60);});
test('ECO-05','Captured foundation becomes level-one ruins',()=>{const a=unit('infantry','P1',0,0),b=building('factory','P2',1,0),s=fixture([a],[b]);a.q=1;b.state='foundation';b.hp=100;b.maxHp=100;ok(s,{kind:'capture',unitId:a.id,buildingId:b.id});assert.deepEqual([b.state,b.level,b.hp,b.maxHp],['complete',1,0,200]);});
test('SKL-01 / SKL-02 / SKL-03','Repair 40 capped, invalid no spend, target once and next turn repeat',()=>{const a=unit('engineer','P1',0,0),a2=unit('engineer','P1',1,-1,'eng2'),t=unit('engineer','P1',1,0,'repair-target'),s=fixture([a,a2,t]);fail(s,{kind:'skill',unitId:a.id,targetId:t.id});fail(s,{kind:'skill',unitId:a.id,targetId:a.id});t.hp=30;ok(s,{kind:'skill',unitId:a.id,targetId:t.id});assert.equal(t.hp,70);assert.equal(a.ap,0);fail(s,{kind:'skill',unitId:a2.id,targetId:t.id});cycle(s);ok(s,{kind:'skill',unitId:a.id,targetId:t.id});assert.equal(t.hp,100);});
test('SKL-04 / SKL-05','HQ ruins need paid rebuilding; air repair remains available',()=>{const a=unit('engineer','P1',0,0),b=building('hq','P1',0,0),s=fixture([a],[b]);b.hp=0;const money=s.players[0].resources.money;fail(s,{kind:'skill',unitId:a.id,targetId:b.id});ok(s,{kind:'repairBuilding',buildingId:b.id});assert.equal(b.hp,120);assert.equal(s.players[0].resources.money,money-120);const t=unit('fighter','P1',1,0);t.hp=50;s.units.push(t);a.ap=2;a.repairUsed=false;ok(s,{kind:'skill',unitId:a.id,targetId:t.id});assert.equal(t.hp,90);a.ap=2;a.repairUsed=false;b.state='foundation';fail(s,{kind:'skill',unitId:a.id,targetId:b.id});});
test('SKL-06','Piercing fifty and stationary sniper hundred',()=>{for(const [aType,tType,damage] of [['tank','heavy',50],['destroyer','tank',100]]){const a=unit(aType,'P1',0,0),t=unit(tType,'P2',1,0),s=fixture([a,t]);const hp=t.hp;ok(s,{kind:'skill',unitId:a.id,targetId:t.id});assert.equal(hp-t.hp,damage);assert.equal(a.cooldownReady,3);}});
test('SKL-07','Scan expires next own start, cooldown two own turns',()=>{const a=unit('scout','P1',0,0),s=fixture([a]);s.players[0].ownTurnIndex=3;ok(s,{kind:'skill',unitId:a.id});assert.equal(a.cooldownReady,5);ok(s,{kind:'end'});assert.equal(a.status.scan,true);ok(s,{kind:'end'});assert.equal(a.status.scan,undefined);fail(s,{kind:'skill',unitId:a.id});cycle(s);ok(s,{kind:'skill',unitId:a.id});});
test('SKL-08','Shock damage forty, target move penalty lasts one own turn',()=>{const a=unit('artillery','P1',0,0),t=unit('tank','P2',2,0),s=fixture([a,t]);ok(s,{kind:'skill',unitId:a.id,targetId:t.id});assert.equal(t.hp,120);ok(s,{kind:'end'});assert.deepEqual([t.ap,t.movePenalty],[2,1]);cycle(s);assert.equal(t.movePenalty,0);});
test('SKL-09','Jam pending, active, protected, then available',()=>{const a=unit('jammer','P1',0,0),a2=unit('jammer','P1',0,1,'j2'),t=unit('fighter','P2',1,0),s=fixture([a,a2,t]);ok(s,{kind:'skill',unitId:a.id,targetId:t.id});fail(s,{kind:'skill',unitId:a2.id,targetId:t.id});ok(s,{kind:'end'});assert.equal(t.ap,1);cycle(s);assert.equal(t.ap,2);assert.ok(t.status.jam);cycle(s);assert.equal(t.status.jam,undefined);});
test('TRN-01 / TRN-02','Order advances only owner turn and upgrade income follows later',()=>{const b=building('city','P1',0,0),f=building('barracks','P1',1,0),s=fixture([],[b,f]);ok(s,{kind:'upgrade',buildingId:b.id});ok(s,{kind:'produce',buildingId:f.id,type:'infantry'});const money=s.players[0].resources.money;ok(s,{kind:'end'});assert.equal(b.level,1);assert.equal(f.stock.length,0);ok(s,{kind:'end'});assert.equal(b.level,2);assert.equal(b.hp,null);assert.equal(f.stock.length,0);assert.equal(G.occupied(s,f).type,'infantry');assert.equal(G.occupied(s,f).ap,2);assert.equal(s.players[0].resources.money,money+35);cycle(s);assert.equal(s.players[0].resources.money,money+35+55);});
test('ECO-01 / ECO-02','24 cap and stock three, unit/upgrade mutual exclusion',()=>{const f=building('barracks','P1',0,0),units=Array.from({length:20},(_,i)=>unit('infantry','P1',i%8,Math.floor(i/8),`u${i}`)),s=fixture(units,[f]);f.stock=Array.from({length:3},(_,i)=>({id:`st${i}`,type:'infantry',sourceId:f.id}));f.order={kind:'unit',type:'infantry'};assert.equal(G.count(s),24);fail(s,{kind:'produce',buildingId:f.id,type:'infantry'});f.stock=[];f.order={kind:'upgrade'};fail(s,{kind:'produce',buildingId:f.id,type:'infantry'});});
test('DEP-01 / DEP-02 / DEP-04','Blocked stock retained, new unit fully actionable',()=>{const f=building('airfield','P1',0,0),u=unit('infantry','P1',0,0),s=fixture([u],[f]);f.stock=[{id:'stock',type:'fighter',sourceId:f.id}];fail(s,{kind:'deploy',buildingId:f.id,stockId:'stock',q:0,r:0});assert.equal(f.stock.length,1);ok(s,{kind:'deploy',buildingId:f.id,stockId:'stock',q:1,r:0});const a=s.units.at(-1);assert.deepEqual([a.ap,a.counterRemaining,a.repairUsed],[2,1,false]);assert.equal(f.stock.length,0);});
test('DEP-03','Naval deploy only ocean; marine can land; source immutable',()=>{const f=building('port','P1',0,0),s=fixture([],[f]);G.cell(s,f).terrain='coast';G.cell(s,{q:1,r:0}).terrain='ocean';f.stock=[{id:'ship',type:'aafrigate',sourceId:f.id},{id:'marine',type:'marine',sourceId:f.id}];fail(s,{kind:'deploy',buildingId:f.id,stockId:'ship',q:-1,r:0});ok(s,{kind:'deploy',buildingId:f.id,stockId:'ship',q:1,r:0});ok(s,{kind:'deploy',buildingId:f.id,stockId:'marine',q:-1,r:0});});
test('ECO-03','Ruined production cancels stock and keeps registry identity',()=>{const a=unit('heavy','P1',0,0),f=building('factory','P2',1,0),s=fixture([a],[f]);f.hp=10;f.level=3;f.order={kind:'unit',type:'heavy'};f.stock=[{id:'s1',type:'heavy',sourceId:f.id},{id:'s2',type:'heavy',sourceId:f.id}];ok(s,{kind:'attack',unitId:a.id,targetId:f.id});assert.deepEqual([f.hp,f.level,f.owner,f.order,f.stock.length,s.buildings.length],[0,3,'P2',null,0,1]);});
test('FOG-01 / FC33','Enemies hide outside current sight and stale building retained',()=>{const a=unit('infantry','P1',0,0),t=unit('tank','P2',1,0),b=building('city','P2',2,0),s=fixture([a,t],[b],{fog:true});G.vision(s);assert.equal(G.visible(s,'P1',t),true);a.q=-6;G.vision(s);const old=s.knownBuildings.P1[b.id].owner;b.owner=null;G.vision(s);assert.equal(G.visible(s,'P1',t),false);assert.equal(s.knownBuildings.P1[b.id].owner,old);});
test('FOG-02 / EN02','Hidden collision charges entered steps only',()=>{const a=unit('tank','P1',0,0),t=unit('infantry','P2',2,0),s=fixture([a,t],[],{fog:true});s.cells=s.cells.filter(c=>c.r===0&&c.q>=0&&c.q<=3);s.vision.P1={ground:['0,0'],air:[]};assert.ok(G.movement(s,a).has('3,0'));ok(s,{kind:'move',unitId:a.id,q:3,r:0});assert.equal(a.q,1);assert.equal(a.ap,1);assert.equal(s.players[0].resources.energy,198);assert.ok(s.revealed.P1.includes(t.id));const ss=fixture([unit('tank','P1',0,0),unit('infantry','P2',1,0)],[],{fog:true});ss.cells=ss.cells.filter(c=>c.r===0&&c.q>=0&&c.q<=3);ss.vision.P1={ground:['0,0'],air:[]};ok(ss,{kind:'move',unitId:ss.units[0].id,q:2,r:0});assert.equal(ss.units[0].ap,2);assert.equal(ss.players[0].resources.energy,200);});
test('EN03 / EN08','Zero energy blocks movement but not attack',()=>{const a=unit('tank','P1',0,0),t=unit('infantry','P2',1,0),s=fixture([a,t]);s.players[0].resources.energy=0;fail(s,{kind:'move',unitId:a.id,q:0,r:1});ok(s,{kind:'attack',unitId:a.id,targetId:t.id});assert.equal(s.players[0].resources.energy,0);});
test('MAP-01 / MAP-02','Standard map count, mirror and connected ground/sea',()=>{const m=M.standard(),list=M.cells(m);assert.equal(list.length,247);assert.equal(m.buildings.length,25);assert.equal(m.initialUnits.length,12);for(const c of list)assert.equal(list.find(x=>x.q===18-c.q&&x.r===12-c.r).terrain,c.terrain);const R=require('../src/random'),routes=R.distances(list,{q:2,r:6});assert.ok(routes.has('16,6'));const sea=R.distances(list,{q:3,r:2},true);assert.ok(sea.has('15,10'));});
test('SAV-01 / SAV-02 / FC40','Snapshots preserve AP, counter and terminal lock',()=>{const s=G.create(M.fixed('S',2));const u=s.units[0];u.ap=0;u.counterRemaining=0;u.repairUsed=true;const loaded=S.restore(S.pack(s,'state'));assert.deepEqual([loaded.units[0].ap,loaded.units[0].counterRemaining,loaded.units[0].repairUsed],[0,0,true]);loaded.result={winner:'P1',reason:'test'};const again=S.restore(S.pack(loaded,'terminal'));fail(again,{kind:'end'});});
test('EN06 / EN07','Legacy energy maps once, same values accepted, conflicts explicit',()=>{const s=G.create(M.fixed('S',2));s.players[0].resources.oil=s.players[0].resources.energy;delete s.players[0].resources.energy;const moved=S.migrate(s);assert.equal(moved.players[0].resources.energy,74);assert.equal('oil' in moved.players[0].resources,false);s.players[0].resources.energy=75;assert.throws(()=>S.migrate(s),/冲突/);assert.throws(()=>S.migrate({schemaVersion:'0.4'}),/v0.4/);});
test('FC01–FC08','Size limits, no unused seats, every fixed map and hash',()=>{for(const map of Content.free.fixedMaps){assert.equal(M.contentHash(map),map.contentHash);assert.equal(require('../src/random').validate(map).ok,true);assert.equal(map.buildings.length,12*map.playerCount+1);assert.equal(map.initialUnits.length,6*map.playerCount);}assert.throws(()=>M.fixed('S',6));});
test('FC10–FC14','Team order, independent ownership and cannot control ally',()=>{assert.deepEqual(G.teams(4,'2v2').order,['P1','P3','P2','P4']);assert.deepEqual(G.teams(6,'3v3').order,['P1','P4','P2','P5','P3','P6']);const s=G.create(M.fixed('M',4),{teams:'2v2'});assert.equal(G.allied(s,'P1','P2'),true);assert.equal(G.allied(s,'P1','P3'),false);const ally=s.units.find(u=>u.owner==='P2');fail(s,{kind:'move',unitId:ally.id,q:ally.q,r:ally.r+1});const b=s.buildings.find(b=>b.owner==='P2'),u=s.units.find(u=>u.owner==='P1');u.q=b.q+1;u.r=b.r;assert.ok(G.captureReason(s,u,b));});
test('FC15–FC22','Original HQ elimination atomic, teammates survive, ruins alone not elimination',()=>{const s=G.create(M.fixed('M',4),{teams:'2v2',fog:false});const target=s.players[2],b=G.building(s,target.originalHqId),a=s.units.find(u=>u.owner==='P1');s.units=s.units.filter(u=>u.owner!=='P3');a.q=b.q;a.r=b.r;b.hp=0;G.checkVictory(s);assert.equal(target.eliminated,false);ok(s,{kind:'capture',unitId:a.id,buildingId:b.id});assert.equal(target.eliminated,true);assert.equal(s.players[3].eliminated,false);assert.equal(s.result,null);assert.equal(b.owner,'P1');assert.ok(s.buildings.filter(x=>x.id!==b.id&&x.id.includes('P3')).every(x=>x.owner===null));assert.deepEqual(target.resources,{money:0,energy:0});});
test('FC23–FC28','All-building HQ not elimination, surrender registry unchanged',()=>{const s=G.create(M.fixed('S',2),{victoryMode:'own_all_registered_buildings',fog:false}),b=G.building(s,s.players[1].originalHqId),u=s.units.find(u=>u.owner==='P1');s.units=s.units.filter(x=>x.owner!=='P2'||x.q!==b.q||x.r!==b.r);u.q=b.q;u.r=b.r;ok(s,{kind:'capture',unitId:u.id,buildingId:b.id});assert.equal(s.players[1].eliminated,false);assert.equal(s.result,null);const total=s.buildings.length;ok(s,{kind:'end'});ok(s,{kind:'surrender'});assert.equal(s.buildings.length,total);assert.equal(s.result.winner,'P1');});
test('FC29 / FC30','Conservative stall: empty affordable recovery tile prevents draw',()=>{const s=fixture([],[building('hq','P1',0,0),building('hq','P2',5,0)]);G.checkVictory(s);assert.equal(s.result,null);s.buildings.forEach(b=>b.hp=0);G.checkVictory(s);assert.equal(s.result,null);s.players.forEach(p=>p.resources={money:0,energy:0});G.checkVictory(s);assert.equal(s.result.winner,null);assert.match(s.result.reason,/恢复生产/);});
test('FC31 / FC32','Pending seats skip eliminated players with no duplicate income',()=>{const s=G.create(M.fixed('M',3),{fog:false}),before=s.players[0].resources.money;ok(s,{kind:'end'});ok(s,{kind:'surrender'});assert.equal(s.actor,'P3');ok(s,{kind:'end'});assert.equal(s.round,2);assert.equal(s.actor,'P1');assert.equal(s.players[0].resources.money,before+120);assert.equal(s.players[1].ownTurnIndex,1);});
test('FC35','Local human handoff cover requested on switch',()=>{const s=G.create(M.fixed('S',2),{controllers:['local_human','local_human']});ok(s,{kind:'end'});assert.equal(s.handoffRequired,true);});
test('FC46 / FC47','AI uses observations, costs, cap, and first-eight HQ restraint',()=>{const s=G.create(M.fixed('S',2),{controllers:['ai','ai'],difficulty:'training'});for(let i=0;i<180&&!s.result;i++){const c=AI.choose(s);if(['attack','capture'].includes(c.kind))assert.ok(!s.players.some(p=>p.originalHqId===(c.targetId||c.buildingId))||G.player(s).ownTurnIndex>=9);ok(s,c);for(const p of s.players){assert.ok(p.resources.money>=0&&p.resources.energy>=0);assert.ok(G.count(s,p.id)<=24);}}const hidden=s.units.find(u=>u.owner!==s.actor);s.settings.fog=true;s.vision[s.actor]={ground:[],air:[]};assert.ok(!AI.observation(s).units.includes(hidden));});
test('CAMP-01 / CAMP-02 / CAMP-03','Seven exact maps, HQ guards, 47 buildings, 82 units, C02 state',()=>{let b=0,u=0;for(const mission of Content.campaign.missions){const map=M.campaign(mission.id),s=G.create(map);b+=s.buildings.length;u+=s.units.length;for(const p of s.players){const hq=G.building(s,p.originalHqId);assert.ok(s.units.some(x=>x.owner===p.id&&x.q===hq.q&&x.r===hq.r));assert.deepEqual(G.income(s,p.id),{money:60,energy:4});}assert.equal(new Set(s.units.map(x=>`${x.q},${x.r}`)).size,s.units.length);}assert.deepEqual([b,u],[47,82]);const s=G.create(M.campaign('C02'));assert.equal(G.unit(s,'C02-U04').hp,80);assert.equal(G.building(s,'C02-NC').hp,null);assert.deepEqual(s.players[0].resources,{money:180,energy:34});});
test('CAMP-06 / CAMP-07 / CAMP-08 / CAMP-09','Scoped construction and chapter production authorization',()=>{for(const m of Content.campaign.missions){const s=G.create(M.campaign(m.id));assert.match(G.constructReason(s,'city',s.cells[0]),/禁止/);}const a=G.create(M.campaign('C01'));assert.match(G.upgradeReason(a,G.building(a,'C01-UB')),/授权/);const b=G.create(M.campaign('C02')),barr=G.building(b,'C02-UB');barr.level=2;b.players[0].resources.money=500;assert.equal(G.productionReason(b,barr,'antitank'),null);const c=G.create(M.campaign('C05')),f=G.building(c,'C05-RF');f.owner='union';c.players[0].resources.money=1000;assert.match(G.productionReason(c,f,'heavy'),/授权/);assert.equal(G.productionReason(c,f,'destroyer'),null);assert.equal(Content.campaign.missions[5].playerProductionWhitelist.length,38);});
test('CAMP-10 / CAMP-11','Finite enemy plan pays and loss permanently cancels',()=>{const s=G.create(M.campaign('C02')),b=G.building(s,'C02-RB');s.actor='red';s.turnStarted=true;s.players[1].ownTurnIndex=2;s.players[1].resources.money=0;const cmd=AI.choose(s);assert.notEqual(cmd?.kind,'produce');assert.equal(s.enemyPlan[0].state,'pending');b.owner='union';AI.choose(s);assert.equal(s.enemyPlan[0].state,'cancelled');b.owner='red';AI.choose(s);assert.equal(s.enemyPlan[0].state,'cancelled');});
test('STORY-01 / STORY-05 / STORY-06','Intro before income; unfinished scene saves correctly',()=>{const s=C.create('C01');assert.deepEqual(s.players[0].resources,{money:0,energy:20});const t=S.restore(S.pack(s,'intro'));assert.deepEqual(t.story.queue,['PROLOGUE','C01-INTRO']);assert.equal(t.story.progress.unlocked.length,1);C.confirm(t);assert.equal(t.turnStarted,false);C.confirm(t);assert.deepEqual(t.players[0].resources,{money:60,energy:24});G.begin(t);assert.equal(t.players[0].resources.money,60);});
test('STORY-02 / STORY-03','MID event deduplicated after transaction and turn-three fallback',()=>{const s=C.create('C01');C.confirm(s);C.confirm(s);s.events.push({kind:'first_legal_attack',actor:'union'});C.after(s);C.after(s);assert.deepEqual(s.story.queue,['C01-MID']);C.confirm(s);s.players[0].ownTurnIndex=3;C.after(s);assert.equal(s.story.queue.length,0);});
test('STORY-04 / STORY-08 / STORY-10 / HELP-02 / END-01','All scenes and clues, frozen assisted battle, epilogue gates completion',()=>{let progress=C.newProgress();for(const m of Content.campaign.missions){const s=C.create(m.id,progress);while(s.story.queue.length)C.confirm(s);const before=JSON.stringify({units:s.units,buildings:s.buildings,players:s.players});C.assist(s);assert.equal(JSON.stringify({units:s.units,buildings:s.buildings,players:s.players}),before);assert.equal(s.result,null);while(s.story.queue.length){if(s.story.queue[0]==='EPILOGUE')assert.equal(s.story.progress.complete,false);C.confirm(s);}progress=s.story.progress;assert.equal(progress.completed[m.id].tacticalMedal,false);}assert.equal(progress.clues.length,7);assert.equal(progress.seenScenes.length,23);assert.equal(progress.complete,true);const replay=C.create('C01',progress);while(replay.story.queue.length)C.confirm(replay);C.assist(replay);while(replay.story.queue.length)C.confirm(replay);assert.equal(replay.story.progress.clues.length,7);});
test('HELP-01 / SAVE-01','Help is advice only, full campaign state restored',()=>{const s=C.create('C02',{...C.newProgress(),unlocked:['C01','C02']});C.confirm(s);const before=JSON.stringify(s);assert.ok(C.help(s).length<=3);assert.equal(JSON.stringify(s),before);s.activeMillis=60*60000;assert.equal(C.timeHelp(s),true);const loaded=S.restore(S.pack(s,'chapter'));assert.deepEqual(loaded.enemyPlan,s.enemyPlan);assert.deepEqual(loaded.story,s.story);assert.equal(loaded.activeMillis,s.activeMillis);});
test('SAVE-02','Checksum rejects corrupted snapshots',()=>{const entry=S.pack(G.create(M.fixed('S',2)),'checksum');entry.snapshot.players[0].resources.money++;assert.throws(()=>S.restore(entry),/校验/);});
test('CAMP-04 / STORY-07','Campaign HQ victory preserves other assets and ended enemy HP/owner',()=>{const s=C.create('C05',{...C.newProgress(),unlocked:['C05']});while(s.story.queue.length)C.confirm(s);const hq=G.building(s,G.player(s,'red').originalHqId);s.units=s.units.filter(u=>u.q!==hq.q||u.r!==hq.r);const a=G.ownUnits(s,'union')[0];a.q=hq.q;a.r=hq.r;G.vision(s);const enemies=JSON.stringify(G.ownUnits(s,'red').map(u=>[u.id,u.owner,u.hp]));const assets=JSON.stringify(G.ownBuildings(s,'red').filter(b=>b.id!==hq.id).map(b=>[b.id,b.owner,b.hp]));ok(s,{kind:'capture',unitId:a.id,buildingId:hq.id});assert.equal(s.result.winner,'union');assert.equal(G.player(s,'red').eliminated,false);C.after(s);while(s.story.queue.length)C.confirm(s);assert.equal(JSON.stringify(G.ownUnits(s,'red').map(u=>[u.id,u.owner,u.hp])),enemies);assert.equal(JSON.stringify(G.ownBuildings(s,'red').map(b=>[b.id,b.owner,b.hp])),assets);S.validate(s);});
test('FC37','Draw consent survives end-turn, requires both humans and freezes AP',()=>{const s=G.create(M.fixed('S',2),{controllers:['local_human','local_human']});ok(s,{kind:'drawVote'});assert.equal(s.result,null);ok(s,{kind:'end'});assert.deepEqual(s.drawVotes,['P1']);ok(s,{kind:'drawVote'});assert.equal(s.result.winnerTeamId,null);assert.ok(s.units.every(u=>u.ap===0));fail(s,{kind:'end'});});
test('SAVE-03','Rechecks typed coordinates, order sources and instance IDs after checksum',()=>{for(const mutate of [s=>s.units[0].type='unknown',s=>s.units[0].q=999,s=>s.units[0].ap=3,s=>s.turnOrder[1]=s.turnOrder[0],s=>s.buildings[0].stock=[{id:'illegal',type:'infantry',sourceId:'other'}]]){const s=G.create(M.fixed('S',2));mutate(s);assert.throws(()=>S.validate(s));}});
test('MAP-03','Ridge obstruction counts use accessible neighboring costs and ties are shared',()=>{const list=[];for(let q=-8;q<=8;q++)for(let r=-5;r<=5;r++)list.push({q,r,terrain:'plain'});list.find(c=>c.q===-4&&c.r===0).terrain='ridge';list.find(c=>c.q===0&&c.r===0).terrain='ridge';const out=require('../src/random').regionCounts(list,[{hq:[-6,0]},{hq:[6,0]}]);assert.deepEqual(out.values.map(x=>x.ridge),[1,0]);});
test('FOG-04','A lost own building is acknowledged once; subsequent hidden changes stay unknown',()=>{const s=G.create(M.fixed('S',2));const b=s.buildings.find(b=>b.owner==='P1');s.units=[];s.buildings=[b];b.hp=0;G.vision(s);b.owner='P2';G.vision(s);assert.equal(s.knownBuildings.P1[b.id].owner,'P2');b.hp=40;G.vision(s);assert.equal(s.knownBuildings.P1[b.id].hp,0);});
test('HELP-03','Whole-story assistance preserves mode and stopped battle before intro income',()=>{let progress=C.newProgress();for(const m of Content.campaign.missions){const s=C.create(m.id,progress,{victoryMode:'own_all_registered_buildings'});C.assist(s);const before=JSON.stringify(s.story.stoppedBattle);while(s.story.queue.length)C.confirm(s);assert.equal(s.turnStarted,false);assert.equal(s.settings.victoryMode,'own_all_registered_buildings');assert.equal(JSON.stringify({units:s.units,buildings:s.buildings,players:s.players,actor:s.actor,round:s.round,enemyPlan:s.enemyPlan,result:s.result}),before);progress=s.story.progress;assert.equal(C.timeHelp(s),false);}assert.equal(progress.complete,true);assert.equal(progress.seenScenes.length,23);});
fs.mkdirSync('reports',{recursive:true});fs.writeFileSync('reports/core-tests.json',JSON.stringify({date:new Date().toISOString(),passed:results.filter(x=>x.ok).length,total:results.length,results},null,2));console.log(`Core: ${results.filter(x=>x.ok).length}/${results.length} groups passed`);if(results.some(x=>!x.ok))process.exitCode=1;
