// Application contracts tested in a small DOM fixture. This is not browser QA.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const D=require('../src/data'),H=require('../src/grid'),G=require('../src/game'),M=require('../src/maps'),A=require('../src/art'),Controls=require('../src/controls'),AI=require('../src/ai');
const results=[];function test(name,fn){try{fn();results.push({name,ok:true});}catch(err){results.push({name,ok:false,error:err.stack});console.error(name,err.message);}}
function fixture(){
 const state=G.create(M.standard(),{fog:false,controllers:['local_human','local_human']});
 const ui={game:state,view:'game',selected:null,tile:null,intent:null,camera:{x:450,y:400,width:1000},busy:false,dialog:null,drawer:null,paused:false,sound:true,volume:.45};
 const attributes={},listeners={},board={clientWidth:1280,clientHeight:720,setAttribute:(k,v)=>attributes[k]=v,addEventListener:(k,fn)=>listeners[k]=fn,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720})},status={innerHTML:''},overlay={innerHTML:''};
 const windowEvents={},documentEvents={},doc={getElementById:id=>id==='board'?board:id==='context-status'?status:id==='route-preview'?overlay:null,querySelector:()=>null,addEventListener:(k,fn)=>documentEvents[k]=fn};
 const ctx={document:doc,innerWidth:1280,innerHeight:720,performance:{now:()=>100},requestAnimationFrame:()=>1,cancelAnimationFrame:()=>{},addEventListener:(k,fn)=>windowEvents[k]=fn,GameGestures:require('../src/gestures'),GameAnime:require('../src/anime'),GameControls:Controls,GameFX:{unlock:()=>{}},console};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/battle-ui.js','utf8'),ctx);
 let renders=0;const commands=[],actions=[],b=ctx.GameBattleUI.create({ui,D,H,G,A,esc:x=>String(x??''),btn:(t,a)=>`<button data-action="${a}">${t}</button>`,commandButton:(t,c)=>`<button data-cmd='${JSON.stringify(c)}'>${t}</button>`,xy:c=>({x:Math.sqrt(3)*44*(c.q+c.r/2),y:66*c.r}),bounds:cells=>({x:0,y:0,w:2000,h:1000}),viewer:()=>ui.viewerId||state.actor,knownBuildingAt:c=>state.buildings.find(b=>b.q===c.q&&b.r===c.r),unitPanel:()=>'',buildingPanel:()=>'',exercisePanel:()=>'',savesPage:()=>'',render:()=>renders++,act:cmd=>commands.push(cmd),toast:()=>{},action:name=>actions.push(name),home:()=>'<home>',resultPanel:()=>'<result>'});
 return {state,ui,b,attributes,commands,actions,windowEvents,documentEvents,listeners,status,get renders(){return renders;}};
}
test('Full viewport camera respects actual aspect ratio without re-rendering',()=>{const f=fixture();f.b.applyCamera();const values=f.attributes.viewBox.split(' ').map(Number);assert.equal(values[2],1000);assert.equal(values[3],562.5);assert.equal(f.renders,0);});
test('All WASD directions move the view; taps also work',()=>{for(const [code,axis,sign] of [['KeyW','y',-1],['KeyA','x',-1],['KeyS','y',1],['KeyD','x',1]]){const f=fixture(),start=f.ui.camera[axis];assert.equal(f.b.keyDown({code,target:{tagName:'BODY'},preventDefault(){}}),true);assert.ok((f.ui.camera[axis]-start)*sign>0);assert.equal(f.renders,0);}});
test('Typing, modifiers and dialogs do not pan the map',()=>{for(const options of [{target:{tagName:'INPUT'}},{ctrlKey:true},{altKey:true},{metaKey:true}]){const f=fixture(),before=JSON.stringify(f.ui.camera);f.b.keyDown({code:'KeyD',target:{tagName:'BODY'},preventDefault(){},...options});assert.equal(JSON.stringify(f.ui.camera),before);}const f=fixture();f.ui.dialog={};assert.equal(f.b.keyDown({code:'KeyD',target:{tagName:'BODY'},preventDefault(){}}),false);});
test('Space toggles pause while an animation runs, held Space does not toggle repeatedly',()=>{const f=fixture();f.ui.busy=true;for(const repeat of [false,true])f.b.keyDown({code:'Space',repeat,target:{tagName:'BODY'},preventDefault(){}});assert.deepEqual(f.actions,['pause']);});
test('Camera continues to work while paused and held keys clear on blur',()=>{const f=fixture();f.ui.paused=true;f.b.keyDown({code:'KeyD',target:{tagName:'BODY'},preventDefault(){}});assert.ok(f.ui.camera.x>450);f.windowEvents.blur();assert.ok(f.attributes.viewBox);});
test('Left selection followed by destination sends one move command with no confirmation',()=>{const f=fixture();f.b.pickCell(3,6);assert.equal(f.ui.selected,'STD-P1-0');f.b.pickCell(3,5);assert.deepEqual(f.commands,[{kind:'move',unitId:'STD-P1-0',q:3,r:5}]);});
test('Right-click does not change the selected unit',()=>{const f=fixture();f.b.pickCell(3,6);f.b.pickCell(3,5,'right');assert.equal(f.ui.selected,'STD-P1-0');assert.equal(f.commands[0].kind,'move');});
test('Busy animation prevents duplicate commands or selection changes',()=>{const f=fixture();f.ui.busy=true;f.b.pickCell(3,6);assert.equal(f.ui.selected,null);assert.equal(f.commands.length,0);assert.equal(f.renders,0);});
test('Enemy inspection is separate from issuing commands',()=>{const f=fixture();f.b.pickCell(15,6);assert.equal(f.ui.selected,'STD-P2-0');f.b.pickCell(3,6);assert.equal(f.ui.selected,'STD-P1-0');assert.equal(f.commands.length,0);});
test('Hidden enemies cannot be selected for inspection or printed on the board',()=>{const f=fixture();f.state.settings.fog=true;G.vision(f.state);f.b.pickCell(15,6);assert.equal(f.ui.selected,null);assert.ok(!f.b.board().includes('data-unit-sprite="STD-P2-0"'));});
test('Local handoff contains no board or unit sprites',()=>{const f=fixture();f.state.handoffRequired=true;const html=f.b.battle();assert.ok(html.includes('我已接手'));assert.ok(!html.includes('id="board"'));assert.ok(!html.includes('data-unit-sprite'));});
test('End results wait for the last visual action to complete',()=>{const f=fixture();f.state.result={winner:'P1'};assert.equal(f.b.battle(),'<result>');f.ui.busy=true;assert.ok(f.b.battle().includes('id="board"'));});
test('Main battle frame owns selection, resources, turn controls and all drawers',()=>{const f=fixture();const html=f.b.battle();assert.ok(html.includes('class="battle-frame'));for(const token of ['economy-strip','selection-slot','context-status','turn-dock','mini-map','drawer-army','drawer-build'])assert.ok(html.includes(token),token);assert.ok(!html.includes('确认移动'));});
test('AI decision UI uses sanitized explanations and hides raw command scores',()=>{const f=fixture();f.state.players[0].controller='ai';f.state.settings.difficulty='hell';f.ui.aiDecision={actor:f.state.actor,phase:'dispatch',phaseLabel:'部队调度',reason:'当前视野内的公开说明',command:{kind:'move',q:777,r:888},scores:[{score:123456}]};const html=f.b.battle();assert.ok(html.includes('人机决策 · 地狱'));assert.ok(html.includes('当前视野内的公开说明'));assert.ok(!html.includes('"q":777'));assert.ok(!html.includes('123456'));});
test('New difficulty profiles have matching UI labels and actual unit statistics',()=>{const src=fs.readFileSync('src/ui.js','utf8');for(const level of AI.difficulties)assert.ok(src.includes(level.name));assert.ok(src.includes('d=G.unitStats(s,u)'));assert.ok(src.includes('GameAI.forViewer(s,decision,viewer())'));assert.ok(src.includes('const command=decision.command'));});
test('Facility drawer gives left-click inspection priority over old targeting modes',()=>{for(const intent of ['skill','deploy','construct',null]){const f=fixture();f.ui.selected='STD-P1-0';f.ui.intent=intent;f.ui.drawer='building';f.b.pickCell(2,5);assert.equal(f.ui.selected,null);assert.equal(f.ui.intent,null);assert.equal(f.commands.length,0);assert.equal(f.ui.tile.q,2);}});
test('Next-unit and direct focus cannot reveal unseen AI coordinates',()=>{const f=fixture();f.state.players[1].controller='ai';f.state.actor='P2';f.ui.viewerId='P1';f.state.settings.fog=true;G.vision(f.state);const before=JSON.stringify(f.ui.camera);f.b.nextUnit();f.b.focusUnit('STD-P2-0');assert.equal(JSON.stringify(f.ui.camera),before);assert.equal(f.ui.selected,null);assert.equal(f.ui.tile,null);});
test('A previously selected enemy has no highlight after leaving observation',()=>{const f=fixture();f.state.settings.fog=true;G.vision(f.state);f.ui.selected='STD-P2-0';assert.ok(!f.b.board().includes('stroke="#fff2b6" stroke-width="3"'));});
test('Jam hover describes AP interference instead of fictitious attack damage',()=>{const f=fixture();f.state.units=f.state.units.filter(u=>u.q!==4||u.r!==5);f.state.units.push(G.normalizeUnit({id:'JAM',type:'jammer',owner:'P1',q:4,r:5}),G.normalizeUnit({id:'TARGET',type:'infantry',owner:'P2',q:5,r:5}));G.vision(f.state);f.ui.selected='JAM';f.ui.intent='skill';f.b.bindBoard();f.listeners.pointermove({target:{closest:()=>({dataset:{cell:'5,5'}})}});assert.ok(f.status.innerHTML.includes('不造成生命损失'));assert.ok(!f.status.innerHTML.includes('预计伤害'));});
test('Repair hover shows actual capped HP gain',()=>{const f=fixture();f.ui.selected='STD-P1-3';f.ui.intent='skill';G.unit(f.state,'STD-P1-0').hp=65;f.b.bindBoard();f.listeners.pointermove({target:{closest:()=>({dataset:{cell:'3,6'}})}});assert.ok(f.status.innerHTML.includes('修复 +15 HP'));});
fs.mkdirSync('reports',{recursive:true});fs.writeFileSync('reports/ui-tests-v0.8.json',JSON.stringify({date:new Date().toISOString(),passed:results.filter(x=>x.ok).length,total:results.length,kind:'Node DOM-fixture contracts; browser checks documented separately',results},null,2));console.log(`UI contracts: ${results.filter(x=>x.ok).length}/${results.length}`);if(results.some(x=>!x.ok))process.exitCode=1;
