'use strict';
// Exercises real controllers and pointer timing. This is not phone/browser QA.
const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm');
const {harness,freeGame,oneStep,copy}=require('./verify-ui-integration');
const Gestures=require('../src/gestures'),Tooltips=require('../src/tooltips');
const results=[];
async function test(name,fn){try{await fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:e.stack});console.error(name,e.stack);}}
function clock(){let time=0,id=0;const timers=new Map();return {setTimeout(fn,ms){timers.set(++id,{fn,at:time+ms});return id;},clearTimeout(id){timers.delete(id);},advance(ms){time+=ms;for(const [id,t] of [...timers])if(t.at<=time){timers.delete(id);t.fn();}}};}
function gestureFixture(){const c=clock(),camera={x:0,y:0,width:460},events=[],api=Gestures.create({camera,width:()=>390,rect:()=>({left:0,top:0,width:390,height:844}),clock:c,hold:e=>events.push('hold'),tap:e=>events.push('tap'),clear:()=>events.push('clear')});const event=(id,x=100,y=100,type='touch')=>({pointerId:id,clientX:x,clientY:y,pointerType:type,button:0});return {c,camera,events,api,event};}
function tooltipFixture(){const c=clock(),listeners=new Map(),tips=[],doc={hidden:false,documentElement:{clientWidth:390,clientHeight:844},body:{appendChild(t){tips.push(t);}},createElement(){return {style:{},setAttribute(){},getBoundingClientRect(){return {width:280,height:70};}};},addEventListener(name,fn){const list=listeners.get(name)||[];list.push(fn);listeners.set(name,list);}};
 const attrs={'data-tooltip':'升级说明 <b>不是标签</b>'},node={isConnected:true,getAttribute:name=>attrs[name],setAttribute(name,value){attrs[name]=value;},removeAttribute(name){delete attrs[name];},contains:n=>n===node,closest(selector){return selector==='#board'?null:node;},getBoundingClientRect(){return {left:10,top:100,width:120,bottom:144};}};
 const api=Tooltips.create(doc,c),event={pointerId:1,pointerType:'touch',clientX:30,clientY:130,target:node};return {c,api,node,tips,event,fire(name,changes={}){const e={...event,preventDefault(){this.prevented=true;},stopImmediatePropagation(){this.stopped=true;},...changes};for(const fn of listeners.get(name)||[])fn(e);return e;}};
}
(async()=>{
 for(const [width,height,coarse] of [[320,568,false],[360,800,true],[390,844,true],[430,932,true],[844,390,true],[1024,768,true],[1300,800,false]])await test(`${width}×${height}: layout profile, camera and real command controls`,async()=>{
  const h=harness({}, {width,height,coarse});await freeGame(h);const mobile=width<=760||coarse&&width<=1200;
  assert.equal(h.document.body.classList.contains('mobile-ui'),mobile);assert.equal(h.document.body.classList.contains('mobile-landscape'),mobile&&width>height);
  assert.equal(h.ui.touchCollapsed,mobile);assert.equal(h.ui.motionMode,mobile?'fast':'standard');
  if(mobile)assert.equal(76*width/h.ui.camera.width,64);
  const u=h.context.Game.ownUnits(h.ui.game).find(u=>oneStep(h,u));h.battle.focusUnit(u.id);assert.equal(!!h.document.querySelector('[data-action="intent-move"]'),!mobile);assert.ok(h.document.querySelector(mobile?'[data-action="drawer-details"]':'[data-action="drawer-unit"]'));
  await h.click(mobile?'[data-action="drawer-details"]':'[data-action="drawer-unit"]');assert.equal(h.ui.drawer,mobile?'details':'unit');assert.ok(h.document.app.innerHTML.includes('技能冷却'));assert.equal(h.errors.length,0);
 });
 await test('An explicitly saved animation preference overrides the phone default',()=>{const h=harness({'six-realms-ui-v08':JSON.stringify({motionMode:'standard'})},{width:390,height:844,coarse:true});assert.equal(h.ui.motionMode,'standard');});
 await test('Rotate a phone: retain committed move and camera scale without issuing another command',async()=>{
  const h=harness({}, {width:390,height:844,coarse:true});await freeGame(h);const u=h.context.Game.ownUnits(h.ui.game).find(u=>oneStep(h,u)),r=oneStep(h,u);h.battle.focusUnit(u.id);h.battle.touchCell(r.q,r.r);await h.flush();await h.finish();assert.equal(h.ui.pendingTouch,null);const before=copy(h.ui.game),scale=h.ui.camera.width/390,center=copy(h.ui.camera),camera=h.ui.camera;
  h.resize(844,390);assert.equal(h.ui.camera,camera);assert.equal(h.ui.camera.width/844,scale);assert.equal(h.ui.pendingTouch,null);assert.equal(h.document.body.classList.contains('mobile-landscape'),true);assert.equal(h.ui.camera.x,center.x);assert.equal(h.ui.camera.y,center.y);assert.deepEqual(copy(h.ui.game),before);
 });
 await test('Headquarters and overview keep the camera object used by pointer gestures',async()=>{const h=harness({}, {width:390,height:844,coarse:true});await freeGame(h);const camera=h.ui.camera;await h.action('overview');assert.equal(h.ui.camera,camera);await h.action('focus-hq');assert.equal(h.ui.camera,camera);assert.equal(76*390/camera.width,64);});
 await test('Opening the tactical map closes a detail panel without issuing a new order',async()=>{const h=harness({}, {width:390,height:844,coarse:true});await freeGame(h);const u=h.context.Game.ownUnits(h.ui.game).find(u=>oneStep(h,u)),r=oneStep(h,u);h.battle.focusUnit(u.id);h.battle.touchCell(r.q,r.r);await h.flush();await h.finish();const n=h.executed.length;h.ui.drawer='building';await h.action('touch-map');assert.equal(h.ui.pendingTouch,null);assert.equal(h.ui.drawer,null);assert.equal(h.executed.length,n);assert.ok(h.document.app.innerHTML.includes('has-touch-map'));assert.ok(h.document.querySelector('[data-action="focus-hq"]'));});
 await test('A garrisoned friendly facility exposes production and deployment from its right icon rail',async()=>{const h=harness({}, {width:390,height:844,coarse:true});await freeGame(h);const s=h.ui.game,b=h.context.Game.ownBuildings(s).find(b=>b.type==='factory'),u=h.context.Game.normalizeUnit({id:'MOBILE_GARRISON',type:'lighttank',owner:s.actor,q:b.q,r:b.r});s.units=s.units.filter(x=>x.q!==b.q||x.r!==b.r);s.units.push(u);h.context.Game.vision(s);h.battle.focusUnit(u.id);await h.click('[data-action="drawer-production"]');assert.ok(h.document.querySelector('.production-card'));assert.equal(h.document.getElementById('production-type'),null);assert.ok(h.document.querySelector('[data-action="set-deployment"]'));assert.ok(h.document.app.innerHTML.includes(' 0/3'));assert.equal(h.ui.tile.q,b.q);});
 await test('Long-press inspection preserves selection and never issues a move or attack',async()=>{const h=harness({}, {width:390,height:844,coarse:true});await freeGame(h);const s=h.ui.game,u=h.context.Game.ownUnits(s).find(u=>oneStep(h,u)),r=oneStep(h,u);h.battle.focusUnit(u.id);const before=copy(s);h.battle.inspectCell(r.q,r.r);assert.equal(h.ui.drawer,'tile');assert.equal(h.ui.selected,u.id);assert.equal(h.executed.length,0);assert.deepEqual(copy(s),before);assert.ok(h.document.app.innerHTML.includes('格子情报'));});
 await test('Inspecting a fogged tile does not expose the hidden enemy or current facility health',async()=>{
  const h=harness({}, {width:390,height:844,coarse:true});await freeGame(h);const s=h.ui.game,id=h.env.viewer(),enemy=s.units.find(u=>u.owner!==id);s.settings.fog=true;s.vision[id]={ground:[],air:[]};s.explored[id]=[];s.knownBuildings[id]={};h.battle.inspectCell(enemy.q,enemy.r);
  const html=h.document.app.innerHTML.slice(h.document.app.innerHTML.indexOf('aria-label="格子情报"'));assert.ok(html.includes('未探明'));assert.ok(!html.includes(h.context.GameData.byId[enemy.type].name));assert.ok(!html.includes('HP '+enemy.hp));
 });
 await test('Backgrounding during an action saves committed state and returns paused; AI stays stopped',async()=>{
  const h=harness({}, {width:390,height:844,coarse:true});await freeGame(h);const s=h.ui.game,u=h.context.Game.ownUnits(s).find(u=>oneStep(h,u)),r=oneStep(h,u);const task=h.env.act({kind:'move',unitId:u.id,q:r.q,r:r.r});await h.flush();assert.equal(h.ui.busy,true);
  h.document.hidden=true;h.document.dispatch('visibilitychange',{});await h.flush();await task;assert.equal(h.ui.paused,true);assert.equal(h.ui.backgroundPause,true);assert.equal(h.saved.at(-1).options.label,'切到后台自动保存');assert.equal(h.saved.at(-1).entry.snapshot.units.find(x=>x.id===u.id).q,r.q);
  const after=copy(s);h.document.hidden=false;h.document.dispatch('visibilitychange',{});await h.tick(3000);assert.deepEqual(copy(s),after);assert.equal(h.ui.paused,true);await h.action('pause');assert.equal(h.ui.paused,false);assert.equal(h.ui.backgroundPause,false);
 });
 await test('A manually paused game is not resumed by visibility changes',async()=>{const h=harness();await freeGame(h);await h.action('pause');h.document.hidden=true;h.document.dispatch('visibilitychange',{});h.document.hidden=false;h.document.dispatch('visibilitychange',{});assert.equal(h.ui.paused,true);assert.equal(h.ui.backgroundPause,false);});
 await test('Returning from a suspended background timer does not add the inactive minutes to play time',async()=>{const h=harness();await freeGame(h);h.document.hidden=true;h.document.dispatch('visibilitychange',{});h.elapse(600000);h.document.hidden=false;h.document.dispatch('visibilitychange',{});await h.action('pause');await h.tick(100);assert.equal(h.ui.game.activeMillis,100);});
 await test('Touch help is accessible in the battlefield and explains all essential gestures',async()=>{const h=harness({}, {width:390,height:844,coarse:true});await freeGame(h);await h.click('[data-action="drawer-touchHelp"]');const html=h.document.app.innerHTML;for(const text of ['双指缩放','长按','撤销移动','自动保存并暂停'])assert.ok(html.includes(text),text);});
 await test('A normal tap still selects once and never becomes a hold',()=>{const f=gestureFixture();f.api.down(f.event(1));f.c.advance(300);f.api.up(f.event(1));f.c.advance(1000);assert.deepEqual(f.events,['tap']);});
 await test('Holding for 650ms opens intel once and never becomes a tap on release',()=>{const f=gestureFixture();f.api.down(f.event(1));f.c.advance(649);assert.deepEqual(f.events,[]);f.c.advance(1);f.api.up(f.event(1));f.c.advance(1000);assert.deepEqual(f.events,['clear','hold']);});
 await test('Dragging cancels long press and cannot issue an action',()=>{const f=gestureFixture();f.api.down(f.event(1));f.api.move(f.event(1,120));f.c.advance(1000);f.api.up(f.event(1,120));assert.deepEqual(f.events,['clear']);assert.notEqual(f.camera.x,0);});
 await test('Pinching cancels hold; lifting the second finger cannot turn into an order',()=>{const f=gestureFixture();f.api.down(f.event(1,100));f.api.down(f.event(2,200));f.api.move(f.event(2,280));f.c.advance(1000);f.api.up(f.event(2,280));f.api.up(f.event(1,100));assert.deepEqual(f.events,['clear']);assert.ok(f.camera.width<460);});
 await test('Pointer cancellation removes the queued hold',()=>{const f=gestureFixture();f.api.down(f.event(1));f.api.cancel();f.c.advance(1000);f.api.up(f.event(1));assert.deepEqual(f.events,['clear']);});
 await test('Mouse orders are not delayed by the touch hold timer',()=>{const f=gestureFixture();f.api.down(f.event(1,100,100,'mouse'));f.c.advance(1000);f.api.up(f.event(1,100,100,'mouse'));assert.deepEqual(f.events,['tap']);});
 await test('Holding a facility button displays literal explanation and suppresses its release click',()=>{const f=tooltipFixture();f.fire('pointerdown');f.c.advance(649);assert.equal(f.tips.length,0);f.c.advance(1);assert.equal(f.tips[0].textContent,'升级说明 <b>不是标签</b>');f.fire('pointerup');const click=f.fire('click');assert.equal(click.prevented,true);assert.equal(click.stopped,true);assert.equal(f.fire('click').stopped,undefined);});
 await test('A quick button tap has no tooltip and remains a normal click',()=>{const f=tooltipFixture();f.fire('pointerdown');f.c.advance(200);f.fire('pointerup');f.c.advance(1000);assert.equal(f.tips.length,0);assert.equal(f.fire('click').stopped,undefined);});
 await test('Touch pointerout after releasing a held button keeps its explanation visible',()=>{const f=tooltipFixture();f.fire('pointerdown');f.c.advance(650);f.fire('pointerup');f.fire('pointerout',{relatedTarget:null});assert.equal(f.tips[0].hidden,false);f.fire('pointerdown');assert.equal(f.tips[0].hidden,true);});
 await test('Tooltip hold is cancelled by scrolling, dragging, cancellation or multi-touch',()=>{for(const cancel of ['scroll','pointermove','pointercancel','pointerdown']){const f=tooltipFixture();f.fire('pointerdown');f.c.advance(200);f.fire(cancel,cancel==='pointermove'?{clientX:70}:cancel==='pointerdown'?{pointerId:2}:{});f.c.advance(1000);assert.ok(!f.tips.length||f.tips[0].hidden,cancel);}});
 await test('Terrain cache reuses connected art but invalidates when neighbouring terrain changes',async()=>{const h=harness();await freeGame(h);let calls=0;const original=h.context.GameArt.terrainMarkupContext;h.context.GameArt.terrainMarkupContext=(...args)=>{calls++;return original(...args);};h.ui.game.cells=h.ui.game.cells.map(c=>({...c}));const first=h.battle.board();assert.ok(calls>0);const n=calls;assert.equal(h.battle.board(),first);assert.equal(calls,n);const visibleKeys=new Set(Array.from(first.matchAll(/data-cell="([^"]+)"/g),m=>m[1]));const c=h.ui.game.cells.find(c=>visibleKeys.has(h.context.Hex.key(c.q,c.r))&&h.ui.game.explored[h.env.viewer()].includes(h.context.Hex.key(c.q,c.r)));c.terrain=c.terrain==='plain'?'forest':'plain';assert.notEqual(h.battle.board(),first);assert.ok(calls>n);});
 await test('All 38 models retain front, rear, sea and land mobile forms plus their original fallbacks',()=>{
  const h=harness({}, {width:390,height:844,coarse:true}),A=h.context.GameAnime;for(const d of h.context.GameData.units){const a=A.asset(d.id);assert.ok(A.portrait(d.id).includes('assets/mobile/units/portraits/'+d.id+'.webp'));assert.ok(A.portrait(d.id).includes('data-png-fallback="'+a.portrait+'"'));assert.ok(A.avatar(d.id).includes('assets/mobile/units/avatars/'+d.id+'.webp'));for(const form of a.forms)for(const rear of [false,true]){const uri=A.formPath(d.id,form,rear),png=A.formPath(d.id,form,rear,true);assert.ok(fs.existsSync(uri),uri);assert.ok(fs.existsSync(png),png);const attrs={},image={setAttribute(name,value){attrs[name]=value;}};A.face({querySelectorAll:selector=>selector==='[data-character-image]'?[image]:[],setAttribute(){}},d.id,form,rear?5:1);assert.equal(attrs.href,uri);assert.equal(attrs['data-png-fallback'],png);}}
 });
 await test('Encoded art covers all 198 originals, preserves WebP format and stays within a 12 MiB mobile budget',()=>{
  const manifest=JSON.parse(fs.readFileSync('assets/mobile/manifest.json','utf8'));assert.equal(manifest.files,198);assert.equal(new Set(manifest.assets.map(a=>a.source)).size,198);let bytes=0;for(const a of manifest.assets){const b=fs.readFileSync(a.uri);assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.toString('ascii',8,12),'WEBP');assert.equal(b.length,a.bytes);assert.equal(fs.statSync(a.source).size,a.originalBytes);bytes+=b.length;}assert.equal(bytes,manifest.bytes);assert.ok(bytes<12*1024*1024);assert.ok(bytes<manifest.originalBytes*.2);
 });
 await test('A failed mobile image retries PNG once, then permits the vector fallback',()=>{
  const handlers=[],context={GameData:require('../src/data'),GameMobile:{imagePath:uri=>uri.replace('assets/units/','assets/mobile/units/').replace('.png','.webp')},document:{addEventListener(name,fn){if(name==='error')handlers.push(fn);}}};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync('src/anime.js','utf8'),context);
  const attrs={href:'assets/mobile/units/chibi/infantry.webp','data-png-fallback':'assets/units/chibi/infantry.png'},styles=[],target={tagName:'image',getAttribute:name=>attrs[name],setAttribute(name,value){attrs[name]=value;},closest(){return {querySelector(){return {style:{setProperty(name,value){styles.push([name,value]);}}};},querySelectorAll(){return [{style:{}},{style:{}}];}};}};handlers[0]({target});assert.equal(attrs.href,'assets/units/chibi/infantry.png');assert.equal(styles.length,0);handlers[0]({target});assert.deepEqual(styles,[['display','inline']]);
 });
 await test('Responsive CSS defines safe areas, scrolling drawers and independent bottom panels without relying on :has()',()=>{
  const css=fs.readFileSync('mobile.css','utf8'),html=fs.readFileSync('index.html','utf8');assert.ok(html.includes('viewport-fit=cover'));assert.ok(html.includes('src/mobile.js'));for(const token of ['safe-area-inset-bottom','--viewport-height','--turn-height','--hud-top','.mobile-ui.mobile-landscape','.mobile-context-rail','.mobile-popup-backdrop','.mobile-map-panel','overscroll-behavior:contain','min-height:44px'])assert.ok(css.includes(token),token);assert.ok(!css.includes(':has('));
 });
 const report={date:new Date().toISOString(),scope:'Real UI controllers in VM, synthetic pointer timing and CSS contracts at 7 viewport profiles. No browser, phone, FPS or touch hardware measurement.',total:results.length,passed:results.filter(r=>r.ok).length,results};fs.writeFileSync('reports/mobile-tests-v1.1.3.json',JSON.stringify(report,null,2));console.log(`Mobile: ${report.passed}/${report.total} groups passed`);if(report.total!==report.passed)process.exitCode=1;
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
