(function(root){'use strict';
 const D=root.GameData||(typeof require!=='undefined'&&require('./data'));
 const families={infantry:'P',walker:'P',heavyinfantry:'P',marine:'P',assaultmarine:'P',heavymarine:'P',antitank:'P',lighttank:'T',tank:'T',heavy:'T',antiair:'T',missileaa:'T',longrangeaa:'T',destroyer:'T',amphibious:'T',lightartillery:'W',artillery:'R',heavyartillery:'R',scout:'W',engineer:'W',jammer:'G',helicopter:'H'};
 const amphibious=['marine','assaultmarine','heavymarine','amphibious'];
 const states=['idle','selected','move','transition','attack','skill','hit','exit','deploy','capture'];
 const frontLeft=new Set(['lighttank','tank','heavy','lightartillery','artillery','navaldestroyer','cruiser','battleship']);
 const muzzles={infantry:[.84,.52],walker:[.81,.51],heavyinfantry:[.81,.55],antitank:[.2,.36],lighttank:[.13,.53],tank:[.1,.5],heavy:[.1,.46],lightartillery:[.15,.4],artillery:[.2,.25],heavyartillery:[.87,.18],antiair:[.84,.45],missileaa:[.68,.3],longrangeaa:[.58,.29],navaldestroyer:[.18,.54],cruiser:[.24,.53],battleship:[.2,.3],marine:[.82,.53],assaultmarine:[.83,.5],heavymarine:[.82,.55],aafrigate:[.82,.52],aamissileship:[.67,.28],areaaship:[.58,.25],scout:[.87,.38],engineer:[.76,.52],jammer:[.86,.38],destroyer:[.9,.33],amphibious:[.81,.55],submarine:[.76,.61],lightbomber:[.5,.67],tacticalbomber:[.5,.67],bomber:[.5,.67],helicopter:[.83,.5]};
 const headings=new Map(), mirrorSafe=new Set(['lighttank','tank','heavy','amphibious','lightartillery','artillery','heavyartillery','antiair','missileaa','longrangeaa','lightfighter','fighter','heavyfighter','lightbomber','bomber','tacticalbomber','helicopter','aafrigate','cruiser','battleship','submarine','navaldestroyer','aamissileship','areaaship']);
 const times={direct:[[140,300,620],[50,100,220],[0,40,120]],guided:[[180,480,760],[65,140,260],[0,40,160]],indirect:[[180,520,820],[65,160,280],[0,40,160]],sniper:[[340,500,820],[100,150,280],[0,40,160]],entrench:[[120,430,620],[40,130,220],[0,40,120]],anchor:[[100,360,620],[35,110,220],[0,40,120]],scan:[[100,380,640],[35,115,220],[0,40,120]],repair:[[120,430,720],[40,130,250],[0,40,160]],jam:[[100,360,640],[35,110,220],[0,40,120]],deploy:[[0,120,340],[0,40,140],[0,0,100]],capture:[[0,260,440],[0,90,160],[0,0,100]]};
 const movement={P:[180,80,40],T:[200,85,40],R:[200,85,40],W:[170,75,40],G:[170,75,40],N:[190,80,40],A:[140,60,40],H:[170,75,40]};
 const registry=Object.fromEntries(D.units.map(d=>[d.id,{id:d.id,name:d.name,portrait:`assets/units/portraits/${d.id}.png`,avatar:`assets/units/avatars/${d.id}.png`,thumbnail:`assets/units/thumbnails/${d.id}.png`,chibi:`assets/units/chibi/${d.id}.png`,forms:amphibious.includes(d.id)?['land','sea']:[d.branch==='air'?'air':d.branch==='navy'?'sea':'land'],family:families[d.id]||(d.branch==='air'?'A':'N'),states,pivot:[.5,.84],muzzle:muzzles[d.id]||[.82,.48],rearMuzzle:[.73,.35],toolTip:[.78,.62],sensor:[.5,.2],hitCenter:[.5,.52],shadow:[.5,.84],version:'1.0'}]));
 function asset(id){return registry[id]||null;}
 function family(id,domain){return domain==='sea'?'N':registry[id]?.family||'T';}
 function timeline(kind,mode='standard'){const row=(times[kind]||times.direct)[mode==='reduced'?2:mode==='fast'?1:0];return {prepare:0,launch:row[0],impact:row[1],settle:row[2]};}
 function clip(step){if(step.kind!=='shot')return times[step.kind]?step.kind:'deploy';if(step.skill==='sniper')return 'sniper';return ['mortar','bomb'].includes(step.projectile)?'indirect':['missile','torpedo'].includes(step.projectile)?'guided':'direct';}
 function moveTiming(id,domain,mode,count){const k=mode==='reduced'?2:mode==='fast'?1:0,settle=[60,30,0][k],cap=[1400,650,400][k],base=movement[family(id,domain)][k];return {step:Math.min(base,(cap-settle)/Math.max(1,count)),settle,cap};}
 function orientation(id,direction=1){direction=((direction%6)+6)%6;const rear=direction>=4,logicalMirror=[2,3,4].includes(direction);return {rear,mirror:mirrorSafe.has(id)&&(logicalMirror!==(!rear&&frontLeft.has(id))),direction};}
 function direction(a,b){return ((Math.round(Math.atan2(b.y-a.y,b.x-a.x)/(Math.PI/3))%6)+6)%6;}
 function formPath(id,domain,rear=false){const name=id+(amphibious.includes(id)&&domain==='land'?'-land':'');return `assets/units/${rear?'rear':'chibi'}/${name}.png`;}
 function remember(instanceId,id,a,b){const d=direction(a,b);headings.set(instanceId,d);return d;}
 function face(glyph,id,domain,d){const o=orientation(id,d);for(const img of glyph?.querySelectorAll?.('[data-character-image]')||[])img.setAttribute('href',formPath(id,domain,o.rear));for(const skin of glyph?.querySelectorAll?.('.chibi-skin')||[])skin.setAttribute('transform',o.mirror?'translate(100 0) scale(-1 1)':'');glyph?.setAttribute?.('data-facing',d);}
 function layout(shared=false){return {x:shared?14:0,y:shared?18:18,width:shared?44:62,height:shared?44:62,pivot:[.5,.84]};}
 function point(id,name,direction=1){const a=asset(id),o=orientation(id,direction),p=name==='muzzle'&&o.rear?a?.rearMuzzle:a?.[name];return p?[o.mirror?1-p[0]:p[0],p[1]]:[.5,.52];}
 function anchor(id,name,center,shared=false,direction=1){const l=layout(shared),p=point(id,name,direction);return {x:center.x+l.x+(p[0]-.5)*l.width,y:center.y+l.y+(p[1]-.84)*l.height};}
 function portrait(id,cls='character-portrait'){const a=asset(id);return a?`<img class="${cls}" src="${cls==='character-card'?a.thumbnail:a.portrait}" alt="${a.name} · 机装少女立绘" loading="lazy" decoding="async">`:'';}
 function avatar(id){const a=asset(id);return a?`<img class="character-avatar" src="${a.avatar}" alt="${a.name}" loading="lazy" decoding="async">`:'';}
 function icon(id){const d=D.byId[id];if(id==='engineer')return '<path d="M45 35h10v10h10v10H55v10H45V55H35V45h10z"/>';if(id==='jammer')return '<path d="M50 30v16m-14-9 8 10m20-10-8 10M37 55q13-17 26 0m-20 8q7-8 14 0" fill="none" stroke-width="3"/>';if(d.dedicatedAA)return '<circle cx="50" cy="45" r="10" fill="none"/><path d="M50 31v28M36 45h28"/>';if(d.branch==='air')return '<path d="M50 29l7 18 19 12H56l-6 13-6-13H24l19-12z"/>';if(d.branch==='navy')return '<path d="M29 49h42l-10 15H39zM43 35h14v13H43z"/>';if(d.infantry)return '<circle cx="50" cy="37" r="7"/><path d="M44 47h12v16H44zM58 46v20"/>';return '<rect x="31" y="44" width="38" height="19" rx="5"/><path d="M50 47V29" stroke-width="5"/>';}
 function markup(id,side='union',domain='land',instanceId='catalogue'){
  const a=asset(id);if(!a)return '';const color=side==='red'?'#E58C84':'#59CBB4',naval=domain==='sea',air=domain==='air',emblem=side==='red'?'<path d="M50 84l5 9H45z"/>':'<circle cx="50" cy="89" r="4" fill="none"/>';
  const key='chibi-'+[instanceId,id,side,domain].join('-').replace(/[^a-zA-Z0-9_-]/g,'_'),o=orientation(id,headings.get(instanceId)),image=`<g class="chibi-skin" transform="${o.mirror?'translate(100 0) scale(-1 1)':''}"><image href="${formPath(id,domain,o.rear)}" data-character-image="${id}" x="0" y="0" width="100" height="100" preserveAspectRatio="xMidYMid meet"/></g>`;
  return `<g class="unit-art unit-${id} anime-chibi" data-model="${id}" data-form="${domain}" data-family="${family(id,domain)}"><defs><mask id="${key}-rig"><rect width="100" height="100" fill="white"/><rect x="24" y="12" width="52" height="42" fill="black"/></mask><clipPath id="${key}-head"><rect x="24" y="12" width="52" height="42"/></clipPath></defs><g class="chibi-shadow"><ellipse cx="50" cy="89" rx="25" ry="6" fill="#17364b" opacity=".18"/></g>${naval?'<g class="chibi-water" fill="none" stroke="#dcf5ee" stroke-width="2"><path d="M15 87q35 10 70 0M22 94q28 8 56 0"/></g>':''}${air?'<g class="chibi-engine" fill="#76b3c4" opacity=".45"><path d="M22 72l-3 15 7-4M78 72l3 15-7-4"/></g>':''}<g class="chibi-rig" mask="url(#${key}-rig)">${image}</g><g class="chibi-body" clip-path="url(#${key}-head)">${image}</g><g class="chibi-fallback" style="display:none" fill="#e6eee9" stroke="#17364b" stroke-width="2"><circle cx="50" cy="34" r="13"/><path d="M37 48h26v28H37zM42 76v9m16-9v9"/>${icon(id)}</g><g class="chibi-far-symbol" fill="#17364b" stroke="${color}" stroke-width="2"><circle cx="50" cy="50" r="23" fill="#f3f6f0"/>${icon(id)}</g><g class="chibi-weapon" fill="none" stroke="${color}" stroke-width="1.4" opacity="0"><path d="M68 48h17M79 43l6 5-6 5"/></g><g class="chibi-terminal" fill="${color}" opacity="0"><rect x="64" y="63" width="12" height="9" rx="2"/><path d="M70 60v15M62 67h16" stroke="${color}"/></g><g class="chibi-emblem" stroke="${color}" stroke-width="2">${emblem}</g></g>`;
 }
 function pose(glyph,state,progress,mode='standard'){
  if(!glyph?.querySelector)return;const body=glyph.querySelector('.chibi-body'),weapon=glyph.querySelector('.chibi-weapon'),terminal=glyph.querySelector('.chibi-terminal');
  const quiet=mode==='reduced',phase=Math.sin(Math.PI*progress);
  if(body){const bob=!quiet&&state==='move'?Math.sin(progress*Math.PI*4)*1.5:0;body.setAttribute('transform',`translate(0 ${bob})`);body.setAttribute('opacity',state==='exit'?Math.max(0,1-progress):'1');}
  if(weapon){weapon.setAttribute('opacity',state==='attack'?.85:'0');weapon.setAttribute('transform',`translate(${-phase*(quiet?0:3)} 0)`);}
  if(terminal)terminal.setAttribute('opacity',['capture','skill','deploy'].includes(state)?(quiet?1:Math.max(.2,phase)):'0');
  const rig=glyph.querySelector('.chibi-rig');if(rig){const clan=glyph.querySelector('.anime-chibi')?.getAttribute('data-family');const recoil=state==='attack'&&!quiet?phase*2:0,float=!quiet&&state==='move'&&['N','A','H'].includes(clan)?Math.sin(progress*Math.PI)*.9:0;rig.setAttribute('transform',`translate(${-recoil} ${float})`);}
  glyph.setAttribute('data-motion-state',state);
 }
 const api={registry,asset,family,timeline,clip,moveTiming,formPath,layout,anchor,portrait,avatar,markup,pose,states,amphibious,orientation,direction,remember,face,headings,mirrorSafe,point,frontLeft};root.GameAnime=api;if(typeof module!=='undefined')module.exports=api;
 root.document?.addEventListener('error',e=>{const parent=e.target?.closest?.('[data-model]');if(!parent)return;parent.querySelector('.chibi-fallback')?.style.setProperty('display','inline');for(const part of parent.querySelectorAll('.chibi-body,.chibi-rig'))part.style.display='none';},true);
})(typeof window!=='undefined'?window:globalThis);
