(function(root){'use strict';
 const defaults={battle:.75,movement:.45,ui:.65,ambience:.30,bgm:.40,voice:.70};
 const chapters={menu:{name:'雾海的来信',bpm:88,root:60,texture:'harp'},briefing:{name:'出发前的接线',bpm:94,root:60,texture:'glass'},C01:{name:'一盏灯的方向',bpm:100,root:60,texture:'wood'},C02:{name:'织回光的线路',bpm:104,root:62,texture:'glass'},C03:{name:'向海风交接',bpm:112,root:60,texture:'strings'},C04:{name:'云间的坐标',bpm:116,root:65,texture:'air'},C05:{name:'重甲之后的晨光',bpm:108,root:57,texture:'metal'},C06:{name:'让航道保持呼吸',bpm:120,root:62,texture:'pulse'},C07:{name:'黎明共同供给',bpm:124,root:60,texture:'ensemble'},win:{name:'灯再次亮起',bpm:88,root:60,texture:'harp'},loss:{name:'仍有下一条路',bpm:82,root:57,texture:'wood'},draw:{name:'下一条共同航路',bpm:88,root:60,texture:'glass'}};
 const melody=[0,2,7,4,2,0,4,7,9,7,4,2,5,4,2,0,0,4,7,12,9,7,4,2,5,7,9,7,4,2,7,0];
 let groups={...defaults},music=true,voiceEnabled=false,masterLevel=.45,muted=false,paused=false,hidden=false,unlocked=false,context=null,master=null,timer=0,current=null,beat=0,nextAt=0,voiceAt=-Infinity,session=0;
 const voiceHistory=new Map();const sources=new Set(),groupNodes=new Map(),voiceLines={infantry:['前哨就位。','灯亮着，继续向前。'],tank:['棱镜，收到。','炮架稳定，穿甲装填。'],marine:['浪锋准备离岸。','港口接通了！'],engineer:['工具都齐了。','这条线还能修好。'],reconplane:['纸鸢，看得到。','新的坐标，大家收好。'],jammer:['联队频道清楚。','切换频段，短时干扰。']};
 try{const p=JSON.parse(root.localStorage?.getItem('six-realms-audio-v1')||'{}');for(const key of Object.keys(defaults))if(Number.isFinite(p.groups?.[key]))groups[key]=Math.max(0,Math.min(1,p.groups[key]));music=p.music!==false;voiceEnabled=p.voiceEnabled===true;}catch{}
 function persist(){try{root.localStorage?.setItem('six-realms-audio-v1',JSON.stringify({groups,music,voiceEnabled}));}catch{}}
 function settings(){return {groups:{...groups},music,voiceEnabled,muted,paused,hidden,unlocked,track:current?.id||null,sources:sources.size,beat,source:'original procedural score / local synthesis'};}
 function groupFor(name){if(['infantry','vehicle','ship','jet','helicopter','track','wheel','leg','wing','transition'].includes(name))return 'movement';if(['turn','cancel','select','confirm','invalid','produce','upgrade','construct','capture','deploy'].includes(name))return 'ui';return 'battle';}
 function effectGain(name){return muted||hidden?0:groups[groupFor(name)];}
 function killSources(){for(const n of [...sources]){try{n.stop();}catch{}try{n.disconnect();}catch{}sources.delete(n);}}
 function halt(){if(timer)root.clearTimeout(timer);timer=0;killSources();}
 function allowed(){return context&&unlocked&&!muted&&!paused&&!hidden&&music&&groups.bgm>0&&masterLevel>0&&current?.active;}
 function gain(){if(master&&context)master.gain.setValueAtTime(muted?0:masterLevel*.26,context.currentTime);for(const [name,node] of groupNodes)node.gain.setValueAtTime(groups[name],context.currentTime);}
 async function unlock(){if(unlocked){resume();return true;}const Constructor=root.AudioContext||root.webkitAudioContext;if(!Constructor)return false;try{if(!context){context=new Constructor();master=context.createGain();const limiter=context.createDynamicsCompressor();limiter.threshold.value=-16;limiter.knee.value=18;limiter.ratio.value=4;master.connect(limiter);limiter.connect(context.destination);for(const key of ['bgm','voice']){const bus=context.createGain();bus.connect(master);groupNodes.set(key,bus);}gain();}if(context.state==='suspended')await context.resume();unlocked=context.state==='running';resume();return unlocked;}catch{return false;}}
 function note(midi,start,length,layer,level){if(!allowed()||sources.size>=18)return;const o=context.createOscillator(),g=context.createGain(),bus=groupNodes.get('bgm');const texture=(chapters[current?.id]||chapters.menu).texture;o.type=layer==='base'?'triangle':layer==='pulse'?'triangle':['harp','wood','metal'].includes(texture)?'triangle':'sine';o.frequency.value=440*Math.pow(2,(midi-69)/12);const peak=level*(layer==='base'?.22:layer==='pulse'?.28:.42);g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(peak,start+.025);g.gain.exponentialRampToValueAtTime(.0001,start+length);o.connect(g);g.connect(bus);sources.add(o);o.onended=()=>{sources.delete(o);o.disconnect();g.disconnect();};o.start(start);o.stop(start+length+.02);}
 function notesAt(index,profile){const n=index%192,chord=[0,5,9,7][Math.floor(n/16)%4],out=[];if(n%4===0)for(const interval of [0,7,12])out.push({midi:profile.root+chord+interval-12,length:2.8,layer:'base',gain:.12});if(n%2===0)out.push({midi:profile.root+melody[Math.floor(n/2)%melody.length],length:1.1,layer:'melody',gain:.2});if(current?.place==='battle'&&n%2===1)out.push({midi:profile.root+chord-12,length:.18,layer:'pulse',gain:.1});return out;}
 function schedule(){if(!allowed()){timer=0;return;}const profile=chapters[current.id]||chapters.menu,seconds=60/profile.bpm;while(nextAt<context.currentTime+.3){if(nextAt<context.currentTime-.05)nextAt=context.currentTime+.025;for(const n of notesAt(beat,profile))note(n.midi,nextAt,n.length,n.layer,n.gain);beat=(beat+1)%192;nextAt+=seconds;}timer=root.setTimeout(schedule,100);}
 function resume(){if(allowed()&&!timer){nextAt=context.currentTime+.04;schedule();}}
 function setMaster(on,volume){muted=!on;if(Number.isFinite(volume))masterLevel=Math.max(0,Math.min(1,volume));gain();if(muted||masterLevel===0){halt();root.speechSynthesis?.cancel();}else resume();}
 function setGroup(name,value){if(!(name in groups))return;groups[name]=Math.max(0,Math.min(1,Number(value)||0));gain();if(name==='bgm'){if(!groups.bgm)halt();else resume();}if(name==='voice'&&!groups.voice)root.speechSynthesis?.cancel();persist();}
 function setMusic(value){music=!!value;if(!music)halt();else resume();persist();}
 function setVoice(value){voiceEnabled=!!value;if(!voiceEnabled)root.speechSynthesis?.cancel();persist();}
 function setPaused(value){paused=!!value;if(paused){halt();root.speechSynthesis?.cancel();}else resume();}
 function setHidden(value){hidden=!!value;if(hidden){halt();root.speechSynthesis?.cancel();}else resume();}
 function setScene({active=true,place='menu',chapter='menu',result=null}={}){const id=result|| (place==='briefing'?'briefing':place==='battle'?(chapters[chapter]?chapter:'C01'):'menu');if(current?.id===id&&current.place===place){current.active=!!active;if(!active)halt();else resume();return;}halt();session++;current={id,place,active:!!active};beat=0;resume();}
 function stop(){halt();root.speechSynthesis?.cancel();current=null;beat=0;session++;}
 function say(id,kind='selected',{ai=false,visible=true,preview=false,onSubtitle=()=>{}}={}){const now=root.performance?.now?.()||Date.now();if(!preview&&!voiceEnabled||muted||masterLevel<=0||paused||hidden||!unlocked||ai||!visible||groups.voice<=0||!preview&&(now-voiceAt<8000||now-(voiceHistory.get(id+':'+kind)||-Infinity)<20000))return false;voiceAt=now;voiceHistory.set(id+':'+kind,now);const lines=voiceLines[id]||[`${Dname(id)}，收到。`,'联队线路已接通。'],line=lines[kind==='selected'?0:1]||lines[0];onSubtitle(line);const synth=root.speechSynthesis,voices=synth?.getVoices?.().filter(v=>v.localService&&/^zh/.test(v.lang));if(!voices?.length||!root.SpeechSynthesisUtterance)return false;const speech=new root.SpeechSynthesisUtterance(line);speech.voice=voices[0];speech.lang='zh-CN';speech.volume=masterLevel*groups.voice;speech.rate=1;speech.pitch=1;voiceAt=now;synth.cancel();synth.speak(speech);return true;}
 function Dname(id){return root.GameData?.byId[id]?.name||id;}
 const api={settings,defaults,chapters,melody,notesAt,groupFor,effectGain,unlock,setMaster,setGroup,setMusic,setVoice,setPaused,setHidden,setScene,stop,say};root.GameAudio=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
