(function(root){'use strict';
 const C=root.GameContent||(typeof require!=='undefined'&&require('./content')),G=root.Game||(typeof require!=='undefined'&&require('./game')),M=root.GameMaps||(typeof require!=='undefined'&&require('./maps'));
 const newProgress=()=>({version:'0.7',unlocked:['C01'],completed:{},clues:[],seenScenes:[],history:[],failures:{},activeMillis:0,complete:false});
 function create(id,progress=newProgress(),settings={}){if(!progress.unlocked.includes(id))throw Error('该章节尚未解锁');const s=G.create(M.campaign(id),{...settings,deferStart:true});s.story={queue:[],seen:[],history:[],progress:M.clone(progress),combatLocked:false,ending:false,completionMethod:null,lastEvent:0,helpDismissed:false,report:null};if(id==='C01'&&!progress.seenScenes.includes('PROLOGUE'))enqueue(s,'PROLOGUE');enqueue(s,s.mission.scenes.intro);return s;}
 function enqueue(s,id){if(!s.story.seen.includes(id)&&!s.story.queue.includes(id))s.story.queue.push(id);}
 function optional(s){const opt=s.mission.optionalGoal,p=G.player(s,'union');if(opt.kind.includes('owns_')){const b=G.building(s,`${s.mission.id}-${opt.buildingKey}`);return b?.owner==='union'&&(!opt.kind.includes('healthy')||G.buildingActive(b));}if(opt.kind==='successful_skill_count'){const kind={'应急修复':'first_successful_repair','主动扫描':'first_successful_scan','链路干扰':'first_successful_jam'}[opt.skill];return s.events.filter(e=>e.actor==='union'&&e.kind===kind).length>=opt.minimum;}if(opt.kind==='alive_branches_on_completion')return opt.branches.every(branch=>G.ownUnits(s,'union').some(u=>root.GameData?.byId[u.type].branch===branch||(typeof require!=='undefined'&&require('./data').byId[u.type].branch===branch)));return false;}
 function ending(s,method){const st=s.story;if(st.ending)return;st.ending=true;st.combatLocked=true;st.completionMethod=method;st.report={method,optional:optional(s),round:s.round,activeMillis:s.activeMillis,clue:s.mission.clue,stats:M.clone(G.player(s,'union').stats),brief:method==='assisted'?'协同部队接替当前战斗，以下是共同整理的交接报告。':s.settings.victoryMode==='own_all_registered_buildings'?'本区所有建筑完成交接。':'核心指挥点已完成交接，各站点正在按停火约定确认。',damagedHQ:G.building(s,G.player(s,'red').originalHqId).hp<=0?'备用介质已取出，设备恢复另列维修。':null};enqueue(s,s.mission.scenes.mid);enqueue(s,s.mission.scenes.outro);if(s.mission.id==='C07')enqueue(s,'EPILOGUE');}
 function after(s){if(!s.story)return;const st=s.story,events=s.events.slice(st.lastEvent);st.lastEvent=s.events.length;if(!st.ending){if(events.some(e=>e.actor==='union'&&s.mission.midTrigger.events.includes(e.kind))||G.player(s,'union').ownTurnIndex>=3)enqueue(s,s.mission.scenes.mid);if(s.result?.winner==='union')ending(s,'tactical');else if(s.result&&!st.failureRecorded){st.failureRecorded=true;st.progress.failures[s.mission.id]=(st.progress.failures[s.mission.id]||0)+1;}}}
 function confirm(s){const st=s.story,id=st.queue.shift();if(!id)return null;st.seen.push(id);st.history.push(id);if(!st.progress.seenScenes.includes(id))st.progress.seenScenes.push(id);st.progress.history.push({id,chapter:s.mission.id,method:st.completionMethod});if(id===s.mission.scenes.intro&&!st.combatLocked){G.begin(s);after(s);}if(id===s.mission.scenes.outro){st.progress.failures[s.mission.id]=0;const old=st.progress.completed[s.mission.id];st.progress.completed[s.mission.id]={method:st.completionMethod,status:st.completionMethod==='assisted'?'assisted_completed':'tactical_completed',report:st.report,tacticalMedal:old?.tacticalMedal||st.completionMethod==='tactical',optionalMedal:old?.optionalMedal||st.completionMethod==='tactical'&&st.report.optional,bestTactical:old?.bestTactical||st.completionMethod==='tactical'};if(!st.progress.clues.includes(s.mission.clue))st.progress.clues.push(s.mission.clue);if(s.mission.nextMission&&!st.progress.unlocked.includes(s.mission.nextMission))st.progress.unlocked.push(s.mission.nextMission);}if(id==='EPILOGUE')st.progress.complete=true;s.revision++;return id;}
 function assist(s){if(!s.story||s.story.ending)return false;s.story.stoppedBattle=M.clone({units:s.units,buildings:s.buildings,players:s.players,actor:s.actor,round:s.round,enemyPlan:s.enemyPlan,result:s.result});ending(s,'assisted');s.revision++;return true;}
 function help(s){const advice=[],units=G.ownUnits(s,'union');for(const u of units){if(G.canAct(s,u))continue;const b=s.buildings.find(b=>!G.captureReason(s,u,b));if(b)advice.push({text:`${u.type} 可接管 ${b.storyLabel||b.type}`,unitId:u.id,q:u.q,r:u.r});const t=s.units.find(t=>!G.attackReason(s,u,t));if(t)advice.push({text:`${u.type} 可攻击当前可见敌军`,unitId:u.id,q:u.q,r:u.r});if(u.type==='engineer'){const repair=[...units,...s.buildings].find(t=>!G.skillReason(s,u,t));if(repair)advice.push({text:'工程车可修复受损己方目标',unitId:u.id,q:u.q,r:u.r});}}if(!advice.length){const u=units.find(u=>u.ap>0);if(u)advice.push({text:'选中有行动点的部队，沿道路接近目标；保留总部守军。',unitId:u.id,q:u.q,r:u.r});else advice.push({text:'结束己方回合，领取收入并恢复行动点。'});}return advice.slice(0,3);}
 function timeHelp(s){if(s.story.ending||s.result)return false;const budget=s.mission.budget[s.settings.victoryMode==='own_all_registered_buildings'?'allBuildings':'hq']*60000;return !s.story.helpDismissed&&(s.activeMillis>budget||(s.story.progress.failures[s.mission.id]||0)>=2);}
 const api={newProgress,create,enqueue,optional,after,confirm,assist,help,timeHelp,ending};root.Campaign=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
