(function (root) {
  'use strict';
  // Model level describes the series; tier is the facility requirement. Specials have no model level.
  const factions = {
  "union": {
    "name": "晨潮协作联队",
    "short": "晨潮联队",
    "accent": "#59cbb4",
    "body": "#a6b5b1",
    "dark": "#435753",
    "symbol": "○"
  },
  "red": {
    "name": "静海统筹军",
    "short": "静海军",
    "accent": "#ef8a78",
    "body": "#b2988c",
    "dark": "#604b45",
    "symbol": "△"
  }
};
  const systems = [
    {"id":"infantry","name":"步兵","branch":"army","facility":"barracks","role":"占领 / 地面守备","text":"各级保持免耗能，逐级强化地面作战和生存；占领是全部单位的通用能力。"},
    {"id":"armor","name":"装甲车","branch":"army","facility":"factory","role":"推进 / 攻坚","text":"轻坦、主战与重坦；装甲和火力提升，以成本或机动换取优势。"},
    {"id":"artillery","name":"炮兵","branch":"army","facility":"factory","role":"间接火力 / 压制","text":"全序列采用间接火力，移动后不能攻击；保留近距离盲区。"},
    {"id":"landaa","name":"陆地防空","branch":"army","facility":"factory","role":"对空 / 陆地掩护","text":"主动对空火力逐级增加射程与强度，地面火力较弱；遭直接攻击后执行强化反击。"},
    {"id":"ship","name":"船舰","branch":"navy","facility":"port","role":"海战 / 沿岸支援","text":"水面舰队主序列，驱逐舰和巡洋舰兼顾防空，战列舰专注远程炮击。"},
    {"id":"marine","name":"海军陆战队","branch":"navy","facility":"port","role":"登陆 / 占领","text":"三个等级均为免耗能两栖步兵，逐级提高突击与防护。"},
    {"id":"navalaa","name":"海洋防空","branch":"navy","facility":"port","role":"对空 / 舰队掩护","text":"专门防空舰序列，仅在海洋移动；主动对空强、对海对陆弱。"},
    {"id":"recon","name":"侦察","branch":"air","facility":"airfield","role":"空中侦察 / 观察","text":"逐级强化视野与部署距离，保持低火力；配合迷雾与主动扫描。"},
    {"id":"fighter","name":"战斗","branch":"air","facility":"airfield","role":"制空 / 护航","text":"三级均能对空，地面和海洋目标伤害较弱。"},
    {"id":"bomber","name":"轰炸","branch":"air","facility":"airfield","role":"对地 / 对海打击","text":"逐级强化载荷与部署距离，不能攻击空中目标。"}
  ];
  // Each unit has explicit production time and firing-after-movement rules.
  const units = [
    {"stage":"launch","layer":"surface","branch":"army","category":"light","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":1,"vision":3,"damage":30,"bonusLight":10,"bonusArmor":0,"amphibious":false,"infantry":true,"targets":["land","sea"],"energyPerStep":0,"tier":1,"skill":"驻守","skillText":"驻守己方城市时获得 10 点地形减伤（被动）。","silhouette":"两人小队 / 步枪 / 背包","blurb":"用最小的预算，守住最重要的一格。","id":"infantry","code":"IF-09","name":"前哨","type":"步枪步兵","role":"低成本 / 占领","cost":35,"hp":80,"armor":0,"move":3,"facility":"barracks","strengths":"最便宜的部队，不消耗能源，适合守城与占领。","weakness":"抗装甲能力弱，不能渡海。","tactic":"用步兵控制后方城市，把金钱和能源留给主战部队。","antiAir":false,"system":"infantry","specialRole":"","buildTurns":1,"fireAfterMove":true,"modelLevel":1,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"id":"walker","code":"IN-02","name":"哨兵","type":"突击步兵","role":"反轻型 / 占领","category":"light","stage":"launch","cost":50,"hp":100,"armor":10,"move":3,"minRange":1,"maxRange":2,"vision":3,"damage":40,"bonusLight":10,"bonusArmor":0,"capture":true,"indirect":false,"counter":true,"skill":"构筑掩体","skillText":"地形减伤 +10，持续到下次己方回合开始；冷却 2 回合。","strengths":"清除侦察车与支援车，在废墟中守住据点。","weakness":"射程短，正面对抗坦克效率低；普通步兵不能进入海洋。","silhouette":"三人小队 / 短枪 / 识别肩章","tactic":"以废墟为支点，在棱镜掩护下占领城市与能源站。","blurb":"站稳一格，守住整条战线。","branch":"army","facility":"barracks","tier":2,"energyPerStep":0,"layer":"surface","targets":["land","sea"],"amphibious":false,"infantry":true,"antiAir":false,"system":"infantry","specialRole":"","buildTurns":1,"fireAfterMove":true,"modelLevel":2,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","category":"light","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":3,"damage":50,"bonusLight":10,"bonusArmor":0,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":true,"energyPerStep":0,"layer":"surface","antiAir":false,"fireAfterMove":true,"specialRole":"","skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","id":"heavyinfantry","code":"IN-03","name":"壁垒","type":"重装步兵","system":"infantry","branch":"army","facility":"barracks","tier":3,"buildTurns":2,"cost":80,"hp":140,"armor":20,"move":2,"role":"重装步兵 / 据点推进","strengths":"保持占领能力，以护甲和生命承受轻型火力，适合推进与守住据点。","weakness":"机动低，仍缺乏高效反装甲火力，怕炮兵与轰炸。","tactic":"随装甲部队进入据点，由反坦克步兵补足反装甲能力。","silhouette":"三人小队 / 厚肩甲 / 前排防护盾","blurb":"让步兵在火线下，也能守住阵地。","targets":["land","sea"],"modelLevel":3},
    {"stage":"launch","layer":"surface","branch":"army","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":3,"damage":40,"bonusLight":10,"bonusArmor":0,"amphibious":false,"infantry":false,"targets":["land","sea"],"energyPerStep":1,"tier":1,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"窄履带 / 小炮塔 / 短炮管","blurb":"在重装到来之前，抢下主动权。","id":"lighttank","code":"LT-11","name":"雨燕","type":"轻型坦克","role":"快速装甲 / 支援","cost":90,"hp":120,"armor":10,"move":4,"facility":"factory","strengths":"造价与能耗低于主战坦克，适合早期推进。","weakness":"装甲较薄，不能进入海洋，正面对抗主战坦克效率低。","tactic":"伴随步兵推进，避免和主战坦克正面对射。","antiAir":false,"system":"armor","specialRole":"","buildTurns":1,"fireAfterMove":true,"modelLevel":1,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"id":"tank","code":"MB-03","name":"棱镜","type":"主战坦克","role":"主战 / 推进","category":"armored","stage":"launch","cost":140,"hp":160,"armor":20,"move":3,"minRange":1,"maxRange":3,"vision":3,"damage":60,"bonusLight":0,"bonusArmor":10,"capture":true,"indirect":false,"counter":true,"skill":"穿甲弹","skillText":"进行一次普通攻击，忽略目标 10 点装甲；冷却 2 回合。","strengths":"稳定的生命与火力，是联合编队的推进核心。","weakness":"耗能高于轻型坦克，受到反装甲歼击车的高效克制。","silhouette":"菱形炮塔 / 对称履带 / 单根中长炮管","tactic":"用射程覆盖中心据点，清除守军后直接接管建筑。","blurb":"装甲与火力之间，最可靠的答案。","branch":"army","facility":"factory","tier":2,"energyPerStep":2,"layer":"surface","targets":["land","sea"],"amphibious":false,"infantry":false,"antiAir":false,"system":"armor","specialRole":"","buildTurns":1,"fireAfterMove":true,"modelLevel":2,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"id":"heavy","code":"HV-07","name":"磐石","type":"重型攻坚坦克","role":"攻坚 / 承伤","category":"armored","stage":"launch","cost":220,"hp":220,"armor":30,"move":2,"minRange":1,"maxRange":2,"vision":2,"damage":70,"bonusLight":0,"bonusArmor":20,"capture":true,"indirect":false,"counter":true,"skill":"锚定防线","skillText":"装甲 +20、不能移动，持续到下次己方回合开始；冷却 3 回合。","strengths":"短距离推进与核心攻坚，可在狭路吸收火力。","weakness":"昂贵、视野短、机动低，仍怕反装甲集火。","silhouette":"超宽双层履带 / 双炮口 / 厚重矩形塔","tactic":"在中后期狭路推进；绕行与夺点比硬碰更有效。","blurb":"当战线必须向前，它便向前。","branch":"army","facility":"factory","tier":3,"energyPerStep":3,"layer":"surface","targets":["land","sea"],"amphibious":false,"infantry":false,"antiAir":false,"system":"armor","specialRole":"","buildTurns":2,"fireAfterMove":true,"modelLevel":3,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","category":"light","capture":true,"indirect":true,"counter":false,"minRange":2,"maxRange":3,"vision":2,"damage":50,"bonusLight":10,"bonusArmor":0,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":1,"layer":"surface","antiAir":false,"fireAfterMove":false,"specialRole":"","skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","id":"lightartillery","code":"AR-01","name":"火萤","type":"轻型榴弹炮","system":"artillery","branch":"army","facility":"factory","tier":1,"buildTurns":1,"cost":110,"hp":80,"armor":0,"move":2,"role":"基础炮兵 / 间接支援","strengths":"低门槛间接火力，越过遮挡打击第二线目标。","weakness":"脆弱、射程短于高级炮兵；相邻格盲区，移动后不能攻击。","tactic":"躲在步兵和轻坦之后，提前占据炮位。","silhouette":"轻型轮架 / 单炮管 / 两个支撑脚","blurb":"以更小的投入，为前线提供炮火。","targets":["land","sea"],"modelLevel":1},
    {"id":"artillery","code":"AR-05","name":"弧光","type":"自行榴弹炮","role":"间接火力 / 压制","category":"armored","stage":"launch","cost":180,"hp":110,"armor":10,"move":2,"minRange":2,"maxRange":4,"vision":2,"damage":60,"bonusLight":10,"bonusArmor":10,"capture":true,"indirect":true,"counter":false,"skill":"震荡弹","skillText":"造成普通伤害 -10（至少 10），目标下次回合移动预算 -1（至少 1）；冷却 2 回合。","strengths":"越过山脊与废墟，攻击友军视野中的目标。","weakness":"不能攻击相邻格；移动后不能攻击；不能反击。","silhouette":"宽大平台 / 抬升短粗炮 / 四个支撑脚","tactic":"留在第二线，侦察提供视野，主战单位负责保护。","blurb":"跨过遮挡，将压力送到后方。","branch":"army","facility":"factory","tier":2,"energyPerStep":2,"layer":"surface","targets":["land","sea"],"amphibious":false,"infantry":false,"antiAir":false,"system":"artillery","specialRole":"","buildTurns":1,"fireAfterMove":false,"modelLevel":2,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","category":"armored","capture":true,"indirect":true,"counter":false,"minRange":2,"maxRange":5,"vision":2,"damage":80,"bonusLight":10,"bonusArmor":20,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":3,"layer":"surface","antiAir":false,"fireAfterMove":false,"specialRole":"","skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","id":"heavyartillery","code":"AR-03","name":"雷砧","type":"重型远程炮","system":"artillery","branch":"army","facility":"factory","tier":3,"buildTurns":2,"cost":260,"hp":140,"armor":20,"move":2,"role":"重型炮兵 / 远程攻坚","strengths":"远程火力和重型炮弹压制坚固目标，越过地形遮挡。","weakness":"需要友军保护和观察，移动后不能攻击，近距离有盲区。","tactic":"在主战坦克后建立炮位，由侦察单位提供目标信息。","silhouette":"宽履带 / 长重炮 / 四角稳定支架","blurb":"用一条更远的火线，推动战场。","targets":["land","sea"],"modelLevel":3},
    {"stage":"launch","layer":"surface","branch":"army","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":3,"vision":3,"damage":30,"bonusLight":-10,"bonusArmor":0,"amphibious":false,"infantry":false,"targets":["land","sea","air"],"energyPerStep":1,"tier":1,"skill":"防空反击","skillText":"遭直接攻击且满足射程与目标权限时，以标准伤害的150%反击；每己方回合最多一次。","silhouette":"雷达盘 / 四联炮 / 履带底盘","blurb":"为地面的每一次推进，留出安全的天空。","id":"antiair","code":"AA-12","name":"天幕","type":"自行防空车","role":"陆地防空 / 基础掩护","cost":120,"hp":100,"armor":10,"move":3,"bonusAir":40,"facility":"factory","strengths":"一级工厂即可提供主动对空火力；保护地面编队的基本防空选择。","weakness":"对地、对海火力较弱；当前不会自动拦截针对友军的空袭。","tactic":"保护能源站与工厂，和战斗机共同争夺空域。","antiAir":true,"system":"landaa","specialRole":"","buildTurns":1,"fireAfterMove":true,"modelLevel":1,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":4,"vision":4,"damage":30,"bonusLight":-10,"bonusArmor":0,"bonusAir":60,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":2,"layer":"surface","antiAir":true,"fireAfterMove":true,"specialRole":"","skill":"防空反击","skillText":"遭直接攻击且满足射程与目标权限时，以标准伤害的150%反击；每己方回合最多一次。","id":"missileaa","code":"AA-02","name":"穹盾","type":"导弹防空车","system":"landaa","branch":"army","facility":"factory","tier":2,"buildTurns":1,"cost":180,"hp":130,"armor":20,"move":3,"role":"主力防空 / 中程覆盖","strengths":"比基础防空车拥有更远的射程和更强的对空伤害。","weakness":"地面火力弱、移动耗能更高；当前没有自动保护友军的拦截。","tactic":"部署在装甲推进线与重要设施之间，主动清除进入射程的飞机。","silhouette":"雷达盘 / 双导弹箱 / 中型履带","blurb":"把地面部队的防空边界，向外推一格。","targets":["land","sea","air"],"modelLevel":2},
    {"stage":"launch","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":5,"vision":5,"damage":30,"bonusLight":-10,"bonusArmor":0,"bonusAir":80,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":2,"layer":"surface","antiAir":true,"fireAfterMove":true,"specialRole":"","skill":"防空反击","skillText":"遭直接攻击且满足射程与目标权限时，以标准伤害的150%反击；每己方回合最多一次。","id":"longrangeaa","code":"AA-03","name":"星垒","type":"远程防空平台","system":"landaa","branch":"army","facility":"factory","tier":3,"buildTurns":2,"cost":260,"hp":160,"armor":20,"move":2,"role":"强化防空 / 远程覆盖","strengths":"长射程对空火力限制高级飞机靠近重点区域。","weakness":"昂贵、机动低、地面自卫差；射程覆盖不等于自动拦截。","tactic":"守卫总部与纵深生产设施，配合前排单位防止被地面部队突入。","silhouette":"宽底盘 / 四导弹箱 / 高雷达桅杆","blurb":"为关键阵地，划出更远的防空边界。","targets":["land","sea","air"],"modelLevel":3},
    {"stage":"launch","layer":"surface","branch":"navy","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":3,"vision":3,"damage":60,"bonusLight":0,"bonusArmor":10,"amphibious":false,"infantry":false,"targets":["land","sea","air"],"energyPerStep":2,"tier":1,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"细长舰体 / 双小炮塔 / 中央烟囱","blurb":"让海上的通道，成为自己的通道。","id":"navaldestroyer","code":"NV-13","name":"潮刃","type":"驱逐舰","cost":240,"hp":180,"armor":20,"move":4,"bonusAir":10,"facility":"port","strengths":"通用护航与沿岸支援，可以攻击空中目标。","weakness":"只能进入海洋，面对战列舰需要编队支援。","tactic":"掩护海军陆战队接近海岸，保护海上能源平台。","role":"护航 / 防空","antiAir":true,"system":"ship","specialRole":"","buildTurns":1,"fireAfterMove":true,"modelLevel":1,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","layer":"surface","branch":"navy","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":3,"vision":3,"damage":70,"bonusLight":0,"bonusArmor":10,"amphibious":false,"infantry":false,"targets":["land","sea","air"],"energyPerStep":3,"tier":2,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"宽长舰体 / 三炮塔 / 高舰桥","blurb":"在舰队中央，把火力送到海岸。","id":"cruiser","code":"NV-15","name":"巡岚","type":"巡洋舰","cost":340,"hp":220,"armor":30,"move":3,"bonusAir":20,"facility":"port","strengths":"均衡的海上主力，可提供防空与沿岸炮击。","weakness":"成本与能耗高于驱逐舰。","tactic":"作为海军编队中心，支援陆战队推进。","role":"海上主战 / 防空","antiAir":true,"system":"ship","specialRole":"","buildTurns":1,"fireAfterMove":true,"modelLevel":2,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","layer":"surface","branch":"navy","category":"armored","capture":true,"indirect":true,"counter":false,"minRange":2,"maxRange":4,"vision":3,"damage":100,"bonusLight":0,"bonusArmor":20,"amphibious":false,"infantry":false,"targets":["land","sea"],"energyPerStep":4,"tier":3,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"超宽舰体 / 三座双联主炮 / 重型舰桥","blurb":"一条海岸线，都在舰炮的考虑之内。","id":"battleship","code":"NV-16","name":"镇海","type":"战列舰","cost":480,"hp":300,"armor":40,"move":2,"facility":"port","strengths":"远距离舰炮与高生命，能压制海上与沿岸目标。","weakness":"最贵舰船、最低海上机动；不能攻击空军，相邻格在射程盲区。","tactic":"在驱逐舰护航下远程支援，不单独进入狭窄海峡。","role":"远程舰炮 / 压制","antiAir":false,"system":"ship","specialRole":"","buildTurns":2,"fireAfterMove":true,"modelLevel":3,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","layer":"surface","branch":"navy","category":"light","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":3,"damage":40,"bonusLight":0,"bonusArmor":0,"amphibious":true,"infantry":true,"targets":["land","sea"],"energyPerStep":0,"tier":1,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"登陆艇底座 / 两名步兵 / 条纹肩章","blurb":"舰队抵达的地方，战线也能抵达。","id":"marine","code":"AM-17","name":"浪锋","type":"海军陆战步兵","cost":55,"hp":90,"armor":0,"move":3,"facility":"port","strengths":"可以在海洋航行和上岸占领；按步兵规则全程免耗能。","weakness":"海上脆弱，无法正面迎战舰船。","tactic":"由舰船掩护接近海岸，再占领城市、能源站与港口。","role":"登陆 / 占领","antiAir":false,"system":"marine","specialRole":"","buildTurns":1,"fireAfterMove":true,"modelLevel":1,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","category":"light","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":3,"damage":50,"bonusLight":10,"bonusArmor":0,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":true,"infantry":true,"energyPerStep":0,"layer":"surface","antiAir":false,"fireAfterMove":true,"specialRole":"","skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","id":"assaultmarine","code":"AM-02","name":"破浪","type":"突击陆战队","system":"marine","branch":"navy","facility":"port","tier":2,"buildTurns":1,"cost":85,"hp":120,"armor":10,"move":3,"role":"主力陆战队 / 登陆突击","strengths":"两栖、免耗能、可占领，比基础陆战队更适合清除海岸守军。","weakness":"不能正面替代舰船，仍缺乏专业反装甲火力。","tactic":"在防空舰和两栖轻坦支持下清理登陆场并占领设施。","silhouette":"登陆艇 / 三人小队 / 突击装备","blurb":"先建立登陆场，再把战线推向内陆。","targets":["land","sea"],"modelLevel":2},
    {"stage":"launch","category":"light","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":3,"damage":60,"bonusLight":10,"bonusArmor":0,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":true,"infantry":true,"energyPerStep":0,"layer":"surface","antiAir":false,"fireAfterMove":true,"specialRole":"","skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","id":"heavymarine","code":"AM-03","name":"礁盾","type":"重装陆战队","system":"marine","branch":"navy","facility":"port","tier":3,"buildTurns":2,"cost":125,"hp":160,"armor":20,"move":2,"role":"重装陆战队 / 登陆据点","strengths":"以更强防护和火力争夺重要海岸据点，仍为可占领的两栖步兵。","weakness":"价格和生产等待较高、机动慢，在海上仍需舰队保护。","tactic":"完成抢滩后守住港口、能源站和城市，让基础陆战队负责较远的夺点。","silhouette":"宽登陆艇 / 厚甲小队 / 防护盾","blurb":"在浪潮之后，留下稳固的阵地。","targets":["land","sea"],"modelLevel":3},
    {"stage":"launch","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":3,"vision":4,"damage":30,"bonusLight":0,"bonusArmor":0,"bonusAir":40,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":2,"layer":"surface","antiAir":true,"fireAfterMove":true,"specialRole":"","skill":"防空反击","skillText":"遭直接攻击且满足射程与目标权限时，以标准伤害的150%反击；每己方回合最多一次。","id":"aafrigate","code":"NA-01","name":"云帆","type":"防空护卫舰","system":"navalaa","branch":"navy","facility":"port","tier":1,"buildTurns":1,"cost":220,"hp":150,"armor":10,"move":4,"role":"基础海防空 / 机动护航","strengths":"一级军港即可生产，较低成本提供专门的海上对空火力。","weakness":"对舰和对陆火力弱，只能在海洋行动；不自动拦截空袭。","tactic":"陪伴陆战队与海上能源平台守军，主动清除低阶飞机。","silhouette":"窄舰体 / 单防空炮 / 圆形雷达","blurb":"让最早出海的编队，也有防空选择。","targets":["land","sea","air"],"modelLevel":1},
    {"stage":"launch","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":4,"vision":4,"damage":40,"bonusLight":-10,"bonusArmor":0,"bonusAir":60,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":3,"layer":"surface","antiAir":true,"fireAfterMove":true,"specialRole":"","skill":"防空反击","skillText":"遭直接攻击且满足射程与目标权限时，以标准伤害的150%反击；每己方回合最多一次。","id":"aamissileship","code":"NA-02","name":"海幕","type":"防空导弹舰","system":"navalaa","branch":"navy","facility":"port","tier":2,"buildTurns":1,"cost":320,"hp":200,"armor":20,"move":3,"role":"主力海防空 / 中程掩护","strengths":"更强对空导弹与更大射程，为主力舰队提供主动防空火力。","weakness":"对海主炮弱，不能替代巡洋舰；当前无自动拦截机制。","tactic":"与巡洋舰分工，对空由海幕处理，对舰由巡洋舰承担。","silhouette":"中型舰体 / 双导弹阵列 / 高雷达","blurb":"把制空压力，接到舰队之外。","targets":["land","sea","air"],"modelLevel":2},
    {"stage":"launch","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":5,"vision":5,"damage":40,"bonusLight":-10,"bonusArmor":0,"bonusAir":80,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":4,"layer":"surface","antiAir":true,"fireAfterMove":true,"specialRole":"","skill":"防空反击","skillText":"遭直接攻击且满足射程与目标权限时，以标准伤害的150%反击；每己方回合最多一次。","id":"areaaship","code":"NA-03","name":"穹海","type":"区域防空舰","system":"navalaa","branch":"navy","facility":"port","tier":3,"buildTurns":2,"cost":440,"hp":260,"armor":30,"move":3,"role":"强化海防空 / 远程覆盖","strengths":"高生存与远程对空火力，适合保护高价值舰队和海上能源平台。","weakness":"成本高、耗能高、对舰输出低；覆盖区暂不自动触发拦截。","tactic":"随战列舰保持纵深，依靠其他舰船阻止敌方水面单位接近。","silhouette":"宽舰体 / 四组导弹阵列 / 大型相控阵","blurb":"为远海的重装火力，提供防空依托。","targets":["land","sea","air"],"modelLevel":3},
    {"stage":"launch","category":"light","capture":true,"indirect":false,"counter":false,"minRange":1,"maxRange":1,"vision":5,"damage":20,"bonusLight":0,"bonusArmor":0,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":1,"layer":"air","antiAir":false,"fireAfterMove":true,"specialRole":"","skill":"主动扫描","skillText":"视野 +2，持续到下次己方回合开始；冷却 2 个己方回合。","id":"reconplane","code":"RC-A1","name":"纸鸢","type":"轻型侦察机","system":"recon","branch":"air","facility":"airfield","tier":1,"buildTurns":1,"cost":90,"hp":60,"armor":0,"move":5,"role":"基础空中侦察 / 前线观察","strengths":"低成本、低能耗、视野优于常规低阶飞机，能跨越地形观察。","weakness":"生命低、火力弱、不能对空；应在防空射程外提供观察。","tactic":"在防空范围边缘观察，用友军火力处理发现的目标。","silhouette":"窄长机翼 / 单引擎 / 腹部观察镜","blurb":"用一架轻机，先看清前方。","targets":["land","sea"],"modelLevel":1},
    {"stage":"launch","category":"light","capture":true,"indirect":false,"counter":false,"minRange":1,"maxRange":1,"vision":6,"damage":20,"bonusLight":0,"bonusArmor":0,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":1,"layer":"air","antiAir":false,"fireAfterMove":true,"specialRole":"","skill":"主动扫描","skillText":"视野 +2，持续到下次己方回合开始；冷却 2 个己方回合。","id":"tacticalrecon","code":"RC-A2","name":"望隼","type":"战术侦察机","system":"recon","branch":"air","facility":"airfield","tier":2,"buildTurns":1,"cost":140,"hp":80,"armor":0,"move":7,"role":"主力空中侦察 / 战术观察","strengths":"更大的视野和部署距离，为多个方向提供观察。","weakness":"火力与防护偏低，需要避开敌方战斗机和防空单位。","tactic":"保持在己方火力覆盖内，以视野帮助炮兵和舰队选择目标。","silhouette":"双尾翼 / 长翼 / 大型腹部镜头","blurb":"看见一个方向，也看见另一条路线。","targets":["land","sea"],"modelLevel":2},
    {"stage":"launch","category":"light","capture":true,"indirect":false,"counter":false,"minRange":1,"maxRange":2,"vision":7,"damage":30,"bonusLight":0,"bonusArmor":0,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":2,"layer":"air","antiAir":false,"fireAfterMove":true,"specialRole":"","skill":"主动扫描","skillText":"视野 +2，持续到下次己方回合开始；冷却 2 个己方回合。","id":"longrangerecon","code":"RC-A3","name":"天眼","type":"远程侦察机","system":"recon","branch":"air","facility":"airfield","tier":3,"buildTurns":2,"cost":210,"hp":100,"armor":10,"move":9,"role":"强化空中侦察 / 纵深观察","strengths":"最长观察半径与高机动，适合观察纵深和海上航路。","weakness":"火力弱，远程移动耗能较高，不能自行夺取制空权。","tactic":"观察后方生产和能源点，交由轰炸机与炮兵实施打击。","silhouette":"超长平直翼 / 双引擎 / 大型传感器","blurb":"把远方的信息，送回指挥线。","targets":["land","sea"],"modelLevel":3},
    {"stage":"launch","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":4,"damage":40,"bonusLight":0,"bonusArmor":0,"bonusAir":20,"bonusLand":-20,"bonusSea":-20,"amphibious":false,"infantry":false,"energyPerStep":2,"layer":"air","antiAir":true,"fireAfterMove":true,"specialRole":"","skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","id":"lightfighter","code":"FT-01","name":"青隼","type":"轻型战斗机","system":"fighter","branch":"air","facility":"airfield","tier":1,"buildTurns":1,"cost":170,"hp":100,"armor":0,"move":6,"role":"基础制空 / 轻型护航","strengths":"一级机场即可获得对空能力，能应对侦察机和低阶空袭。","weakness":"防护与对空火力低于主力战斗机，对陆海输出较弱。","tactic":"与地面防空共同应对空袭，避免单独追入敌方防空区。","silhouette":"窄后掠翼 / 单引擎 / 小机身","blurb":"最早起飞的制空力量。","targets":["land","sea","air"],"modelLevel":1},
    {"stage":"launch","layer":"air","branch":"air","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":5,"damage":50,"bonusLight":0,"bonusArmor":0,"amphibious":false,"infantry":false,"targets":["land","sea","air"],"energyPerStep":3,"tier":2,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"后掠机翼 / 单驾驶舱 / 单尾翼","blurb":"为整个编队，赢下天空的主动。","id":"fighter","code":"AF-20","name":"苍隼","type":"战斗机","cost":260,"hp":130,"armor":10,"move":7,"bonusAir":30,"bonusLand":-20,"bonusSea":-20,"facility":"airfield","strengths":"空军主战单位，对空加成 +30，航程 7。","weakness":"对地和对海伤害 -20，耗能较高。","tactic":"优先夺取制空权，再支援地面。","role":"空中主战 / 防空","antiAir":true,"system":"fighter","specialRole":"","buildTurns":1,"fireAfterMove":true,"modelLevel":2},
    {"stage":"launch","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":3,"vision":5,"damage":60,"bonusLight":0,"bonusArmor":0,"bonusAir":40,"bonusLand":-20,"bonusSea":-20,"amphibious":false,"infantry":false,"energyPerStep":4,"layer":"air","antiAir":true,"fireAfterMove":true,"specialRole":"","skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","id":"heavyfighter","code":"FT-03","name":"霄刃","type":"重型战斗机","system":"fighter","branch":"air","facility":"airfield","tier":3,"buildTurns":2,"cost":340,"hp":170,"armor":20,"move":7,"role":"强化制空 / 重型护航","strengths":"更强对空火力、射程与生存，是后期护航与空战主力。","weakness":"价格和能耗高，仍不能替代专门轰炸机的对地输出。","tactic":"保护轰炸机与侦察机，优先处理敌方战斗机。","silhouette":"宽后掠翼 / 双引擎 / 双尾翼","blurb":"为重要出击，争取更多空中空间。","targets":["land","sea","air"],"modelLevel":3},
    {"stage":"launch","category":"armored","capture":true,"indirect":false,"counter":false,"minRange":1,"maxRange":2,"vision":3,"damage":50,"bonusLight":10,"bonusArmor":10,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":2,"layer":"air","antiAir":false,"fireAfterMove":true,"specialRole":"","skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","id":"lightbomber","code":"BM-01","name":"鸣雷","type":"轻型轰炸机","system":"bomber","branch":"air","facility":"airfield","tier":1,"buildTurns":1,"cost":190,"hp":100,"armor":0,"move":5,"role":"基础轰炸 / 近程支援","strengths":"早期对陆、对海打击，以低于高级轰炸机的成本提供空中火力。","weakness":"生命低、攻击和部署距离较短，不能对空且不能反击。","tactic":"在战斗机或防空支持下打击暴露目标。","silhouette":"短平直翼 / 双引擎 / 单尾翼","blurb":"让第一轮空袭，有明确的预算。","targets":["land","sea"],"modelLevel":1},
    {"stage":"launch","category":"armored","capture":true,"indirect":false,"counter":false,"minRange":1,"maxRange":3,"vision":4,"damage":60,"bonusLight":10,"bonusArmor":10,"bonusAir":0,"bonusLand":0,"bonusSea":0,"amphibious":false,"infantry":false,"energyPerStep":3,"layer":"air","antiAir":false,"fireAfterMove":true,"specialRole":"","skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","id":"tacticalbomber","code":"BM-02","name":"惊雷","type":"战术轰炸机","system":"bomber","branch":"air","facility":"airfield","tier":2,"buildTurns":1,"cost":270,"hp":140,"armor":10,"move":7,"role":"主力轰炸 / 纵深支援","strengths":"载荷和部署距离较均衡，承担常规对陆与对海空中打击。","weakness":"持续转场耗能较高，不能对空，需要护航。","tactic":"配合战斗机清理高价值地面和海洋目标。","silhouette":"宽平直翼 / 双引擎 / 双尾翼","blurb":"把稳定火力，送到更深的战线。","targets":["land","sea"],"modelLevel":2},
    {"stage":"launch","layer":"air","branch":"air","category":"armored","capture":true,"indirect":false,"counter":false,"minRange":1,"maxRange":3,"vision":4,"damage":80,"bonusLight":10,"bonusArmor":20,"amphibious":false,"infantry":false,"targets":["land","sea"],"energyPerStep":4,"tier":3,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"宽平直机翼 / 四引擎 / 双尾翼","blurb":"把长航程，变成对后方的持续压力。","id":"bomber","code":"AF-21","name":"远雷","type":"远程轰炸机","cost":360,"hp":180,"armor":10,"move":9,"facility":"airfield","strengths":"三类飞机中航程最长，能够攻击陆地与海洋目标。","weakness":"不能攻击空中单位；每移动一格耗能 4，需要制空掩护。","tactic":"打击后方工厂和敌方舰队，让战斗机承担护航职责。","role":"远程对地 / 对海","antiAir":false,"system":"bomber","specialRole":"","buildTurns":2,"fireAfterMove":true,"modelLevel":3,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"id":"scout","code":"RC-01","name":"游隼","type":"侦察车","role":"侦察 / 机动","category":"light","stage":"launch","cost":70,"hp":80,"armor":0,"move":5,"minRange":1,"maxRange":2,"vision":5,"damage":30,"bonusLight":10,"bonusArmor":0,"capture":true,"indirect":false,"counter":true,"skill":"主动扫描","skillText":"视野 +2，持续到下次己方回合开始；冷却 2 回合。","strengths":"先手探路、侧翼骚扰、追击残血步兵，可利用机动快速占领空置建筑。","weakness":"装甲为零，不能在重火力前停留。","silhouette":"窄长车身 / 四个外露车轮 / 环形天线","tactic":"沿道路迂回，用视野为弧光提供炮击目标。","blurb":"先一步看见战场，先一步改变战局。","branch":"army","facility":"factory","tier":1,"energyPerStep":1,"layer":"surface","targets":["land","sea"],"amphibious":false,"infantry":false,"antiAir":false,"system":null,"specialRole":"地面侦察","buildTurns":1,"fireAfterMove":true,"modelLevel":null,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"id":"engineer","code":"SP-06","name":"织补","type":"战地工程车","role":"修复 / 后勤","category":"light","stage":"launch","cost":100,"hp":100,"armor":10,"move":3,"minRange":1,"maxRange":1,"vision":3,"damage":20,"bonusLight":0,"bonusArmor":0,"capture":true,"indirect":false,"counter":false,"skill":"应急修复","skillText":"修复相邻友军或己方建筑 40 HP，不超过上限；不能修复自己；无冷却。","strengths":"修复友军装甲和陆地建筑，维持前线。","weakness":"攻击很弱，不能反击；被侦察车绕后时需要保护。","silhouette":"方形货舱 / 双机械臂 / 大型十字标记","tactic":"在前排背后一格修复，安全时接管空置设施，避免孤军冒进。","blurb":"把一次损失，变成下一轮的机会。","branch":"army","facility":"factory","tier":1,"energyPerStep":1,"layer":"surface","targets":["land","sea"],"amphibious":false,"infantry":false,"antiAir":false,"system":null,"specialRole":"战地修复","buildTurns":1,"fireAfterMove":true,"modelLevel":null,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","layer":"surface","branch":"army","category":"light","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":3,"damage":30,"bonusLight":-10,"bonusArmor":40,"amphibious":false,"infantry":true,"targets":["land","sea"],"energyPerStep":0,"tier":2,"skill":"伏击","skillText":"本回合未移动时，对装甲攻击 +10（被动）。","silhouette":"两人小队 / 肩扛发射器 / 短三脚架","blurb":"不是每一辆坦克，都需要另一辆坦克来阻挡。","id":"antitank","code":"IF-10","name":"猎矛","type":"反坦克步兵","role":"反装甲 / 守备","cost":65,"hp":80,"armor":0,"move":2,"facility":"barracks","strengths":"免耗能、造价低于坦克，以专门火力防守装甲通道。","weakness":"机动慢、容易被突击步兵与轰炸机清除。","tactic":"借废墟掩护，让坦克在射程内付出推进代价。","antiAir":false,"system":null,"specialRole":"反装甲步兵","buildTurns":1,"fireAfterMove":true,"modelLevel":null,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"id":"jammer","code":"EW-08","name":"脉冲","type":"电子战平台","role":"干扰 / 辅助","category":"light","stage":"launch","cost":130,"hp":90,"armor":0,"move":4,"minRange":1,"maxRange":2,"vision":4,"damage":30,"bonusLight":0,"bonusArmor":0,"capture":true,"indirect":false,"counter":true,"skill":"链路干扰","skillText":"距离 1–2、可见且射线通畅的敌军，下次回合仅获得 1 AP；不可叠加；冷却 3 回合。","strengths":"削弱关键单位移动后攻击的能力，协助突破防线。","weakness":"直接伤害低、无装甲，技能不能连续压制同一目标。","silhouette":"圆形磁盘 / 三支天线 / 六足底盘","tactic":"在主战单位保护下，让对方火力错过一个节拍。","blurb":"改变的不是火力，而是行动的时机。","branch":"army","facility":"factory","tier":2,"energyPerStep":1,"layer":"surface","targets":["land","sea"],"amphibious":false,"infantry":false,"antiAir":false,"system":null,"specialRole":"电子战","buildTurns":1,"fireAfterMove":true,"modelLevel":null,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"id":"destroyer","code":"AT-04","name":"长钉","type":"反装甲歼击车","role":"反装甲 / 伏击","category":"armored","stage":"launch","cost":160,"hp":140,"armor":20,"move":2,"minRange":1,"maxRange":3,"vision":3,"damage":60,"bonusLight":-10,"bonusArmor":40,"capture":true,"indirect":false,"counter":true,"skill":"定点狙击","skillText":"本回合尚未移动时，可进行伤害 +20 的直射攻击；冷却 2 回合。","strengths":"对装甲目标加成 +40，能迅速瓦解坦克推进。","weakness":"机动低，对轻型目标伤害较差，容易被绕开。","silhouette":"低矮车身 / 超长磁轨炮 / 后置稳定鳍","tactic":"守住长直通道，用游隼看见对方主战部队。","blurb":"让每一次穿透，都恰好落在要害。","branch":"army","facility":"factory","tier":3,"energyPerStep":2,"layer":"surface","targets":["land","sea"],"amphibious":false,"infantry":false,"antiAir":false,"system":null,"specialRole":"重型反装甲","buildTurns":2,"fireAfterMove":true,"modelLevel":null,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","layer":"surface","branch":"navy","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":3,"damage":40,"bonusLight":10,"bonusArmor":0,"amphibious":true,"infantry":false,"targets":["land","sea"],"energyPerStep":1,"tier":2,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"浮力侧舱 / 短炮塔 / 轻履带","blurb":"越过海岸，而不是停在海岸。","id":"amphibious","code":"AM-18","name":"涉潮","type":"两栖轻型坦克","cost":120,"hp":120,"armor":10,"move":4,"seaEnergyPerStep":2,"facility":"port","strengths":"既能航行也能登陆，提供轻装甲支援。","weakness":"海上每格耗能 2，陆地每格 1；防护弱于主战坦克，没有两栖重坦型号。","tactic":"和陆战队一起登陆，清理守军后由任一部队接管建筑。","role":"登陆 / 装甲支援","antiAir":false,"system":null,"specialRole":"登陆装甲支援","buildTurns":1,"fireAfterMove":true,"modelLevel":null,"bonusAir":0,"bonusLand":0,"bonusSea":0},
    {"stage":"launch","layer":"surface","branch":"navy","category":"armored","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":3,"damage":60,"bonusLight":0,"bonusArmor":30,"amphibious":false,"infantry":false,"targets":["land","sea"],"energyPerStep":2,"tier":2,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"胶囊舰体 / 低矮围壳 / 无炮塔","blurb":"从波浪之间，截断对手的航线。","id":"submarine","code":"NV-14","name":"潜锋","type":"潜艇","cost":260,"hp":140,"armor":10,"move":4,"facility":"port","strengths":"高效打击装甲舰船，也能通过巡航导弹攻击陆地目标。","weakness":"生命偏低，首版没有隐身或独立潜航层，也没有防空能力。","tactic":"从侧翼威胁巡洋舰，避开沿岸交叉火力。","role":"反舰 / 沿岸打击","antiAir":false,"system":null,"specialRole":"反舰专精","buildTurns":1,"fireAfterMove":true,"modelLevel":null,"bonusAir":0,"bonusLand":-10,"bonusSea":10},
    {"stage":"launch","layer":"air","branch":"air","category":"light","capture":true,"indirect":false,"counter":true,"minRange":1,"maxRange":2,"vision":4,"damage":40,"bonusLight":20,"bonusArmor":0,"amphibious":false,"infantry":false,"targets":["land","sea"],"energyPerStep":2,"tier":1,"skill":"基础作战","skillText":"以该体系的移动与普通攻击规则为核心，不另加主动技能。","silhouette":"十字旋翼 / 细长机身 / 尾桨","blurb":"越过地形，及时出现在需要的位置。","id":"helicopter","code":"AF-19","name":"蜂鸟","type":"武装直升机","cost":160,"hp":90,"armor":0,"move":4,"facility":"airfield","strengths":"轻型空中支援，越过山脊与水域清除步兵。","weakness":"不能攻击空军，受到战斗机和防空车克制。","tactic":"抓住缺乏防空的侧翼，保留足够能源再定位。","role":"轻型空中支援","antiAir":false,"system":null,"specialRole":"对地 / 对海支援","buildTurns":1,"fireAfterMove":true,"modelLevel":null,"bonusAir":0,"bonusLand":0,"bonusSea":0}
  ];
  units.sort((a,b)=>{
    const order=u=>u.system?systems.findIndex(s=>s.id===u.system):systems.length+['army','navy','air'].indexOf(u.branch);
    return order(a)-order(b)||a.tier-b.tier||a.cost-b.cost;
  });
  const terrain = {
  "plain": {
    "name": "荒原",
    "cost": 1,
    "defense": 0,
    "blocks": false,
    "color": "#263d3b",
    "text": "基础通行，适合常规推进。"
  },
  "road": {
    "name": "道路",
    "cost": 1,
    "defense": 0,
    "blocks": false,
    "color": "#3e5049",
    "text": "本次移动全程进入道路，预算 +1。"
  },
  "rubble": {
    "name": "碎石",
    "cost": 2,
    "defense": 10,
    "blocks": false,
    "color": "#405650",
    "text": "消耗 2 移动预算，减伤 10。"
  },
  "ruins": {
    "name": "工业废墟",
    "cost": 2,
    "defense": 20,
    "blocks": true,
    "color": "#354541",
    "text": "消耗 2，减伤 20，遮挡经过的射线。"
  },
  "water": {
    "name": "河滩",
    "cost": 2,
    "defense": 0,
    "blocks": false,
    "color": "#214c55",
    "text": "陆地浅水地形；游隼进入仅消耗 1，普通舰船不可进入。"
  },
  "ocean": {
    "name": "海洋",
    "cost": 1,
    "defense": 0,
    "blocks": false,
    "color": "#173e54",
    "text": "只允许舰船、两栖部队与空军通过；普通陆军无法进入。"
  },
  "coast": {
    "name": "海岸",
    "cost": 2,
    "defense": 0,
    "blocks": false,
    "color": "#5b6850",
    "text": "陆地格；两栖部队可登陆，普通舰船不可上岸。"
  },
  "ridge": {
    "name": "山脊",
    "cost": Infinity,
    "defense": 0,
    "blocks": true,
    "color": "#4b5147",
    "text": "不可进入，遮挡经过的射线。"
  }
};
  const buildings = [
    {"id":"hq","name":"指挥总部","group":"economy","cost":0,"maxLevel":1,"upgrades":[],"money":[60],"energy":[4],"hp":240,"armor":20,"place":"陆地 / 场景预设","text":"固定基础收入与储备供能；场景预设，所有单位都可占领。"},
    {"id":"city","name":"行政城市","group":"economy","cost":140,"maxLevel":3,"upgrades":[120,200],"money":[35,55,80],"energy":[0,0,0],"hp":160,"armor":10,"place":"普通陆地","text":"稳定税收；经济骨干，提升等级增加金钱产出。"},
    {"id":"market","name":"商贸中心","group":"economy","cost":100,"maxLevel":3,"upgrades":[100,160],"money":[25,40,60],"energy":[0,0,0],"hp":120,"armor":0,"place":"普通陆地","text":"低成本经济投资；不能招募单位。"},
    {"id":"energyfield","name":"陆地能源站","group":"resource","cost":120,"maxLevel":3,"upgrades":[100,160],"money":[0,0,0],"energy":[10,16,24],"hp":120,"armor":0,"place":"陆地能源点","text":"提供装甲、舰船和空军机动所需的能源。"},
    {"id":"energyplatform","name":"海上能源平台","group":"resource","cost":200,"maxLevel":3,"upgrades":[160,240],"money":[0,0,0],"energy":[16,24,36],"hp":140,"armor":10,"place":"海洋能源点","text":"更高供能能力，需要舰队与防空保护；属于海洋目标。"},
    {"id":"barracks","name":"步兵营","group":"production","cost":100,"maxLevel":3,"upgrades":[120,180],"money":[0,0,0],"energy":[0,0,0],"hp":160,"armor":10,"place":"普通陆地","text":"步兵与对应特殊单位；Ⅰ / Ⅱ / Ⅲ级逐级解锁，高级设施保留低级型号。"},
    {"id":"factory","name":"装甲工厂","group":"production","cost":180,"maxLevel":3,"upgrades":[160,240],"money":[0,0,0],"energy":[0,0,0],"hp":200,"armor":20,"place":"普通陆地","text":"装甲车、炮兵、陆地防空与对应特殊单位；Ⅰ / Ⅱ / Ⅲ级逐级解锁，高级设施保留低级型号。"},
    {"id":"port","name":"军港","group":"production","cost":160,"maxLevel":3,"upgrades":[160,240],"money":[0,0,0],"energy":[0,0,0],"hp":180,"armor":10,"place":"邻接海洋的陆地海岸","text":"船舰、海军陆战队、海洋防空与对应特殊单位；Ⅰ / Ⅱ / Ⅲ级逐级解锁，高级设施保留低级型号。"},
    {"id":"airfield","name":"机场","group":"production","cost":200,"maxLevel":3,"upgrades":[200,280],"money":[0,0,0],"energy":[0,0,0],"hp":160,"armor":10,"place":"普通陆地","text":"侦察、战斗、轰炸与对应特殊单位；Ⅰ / Ⅱ / Ⅲ级逐级解锁，高级设施保留低级型号。"}
  ];
  const branches = {"army":"陆军","navy":"海军","air":"空军"};
  const states = {"land":"陆地","sea":"海洋","air":"空中"};
  const economy = {"initialMoney":600,"initialEnergy":60,"moneyCap":3000,"energyCap":300,"unitCap":24};
  const levels = {1:'Ⅰ级·基础型',2:'Ⅱ级·主力型',3:'Ⅲ级·强化型'};
  for(const u of units){u.dedicatedAA=['antiair','missileaa','longrangeaa','aafrigate','aamissileship','areaaship'].includes(u.id);if(u.dedicatedAA){u.skill='防空反击';u.skillText='遭直接攻击后，按标准伤害的 1.5 倍反击；每己方回合一次。';}}
  terrain.road.text='整个己方回合仅进入道路时，累计移动预算 +1；首次进入非道路即失去加成。';
  // v1.1.6: aviation keeps terrain freedom and specialist roles, with a smaller
  // endurance/movement budget. Old HP is retained only for proportional save migration.
  const balance={version:1,legacyAirHp:{reconplane:60,tacticalrecon:80,longrangerecon:100,lightfighter:100,fighter:130,heavyfighter:170,lightbomber:100,tacticalbomber:140,bomber:180,helicopter:90},air:{
    reconplane:{hp:50,damage:15,move:4},tacticalrecon:{hp:65,damage:15,move:5},longrangerecon:{hp:80,armor:0,damage:20,move:7},
    lightfighter:{hp:85,damage:35,move:5,bonusLand:-25,bonusSea:-25},fighter:{hp:105,armor:5,damage:40,move:6,bonusLand:-30,bonusSea:-30},heavyfighter:{hp:135,armor:10,damage:50,move:6,maxRange:2,bonusAir:35,bonusLand:-35,bonusSea:-35},
    lightbomber:{hp:80,damage:40,move:4,bonusArmor:5,bonusLight:5},tacticalbomber:{hp:110,armor:5,damage:50,move:5,maxRange:2,bonusArmor:5,bonusLight:5},bomber:{hp:135,armor:5,damage:60,move:7,bonusArmor:10,bonusLight:5},helicopter:{hp:75,damage:30,vision:3,bonusLight:10}
  }};
  for(const u of units)if(balance.air[u.id])Object.assign(u,balance.air[u.id]);
  const combat = {minDamage:10,step:10,damageMode:'fixed'};
  const data = {version:'0.7',balance,combat,factions,systems,units,terrain,buildings,branches,states,economy,levels,
    systemById:Object.fromEntries(systems.map(s=>[s.id,s])),
    buildingById:Object.fromEntries(buildings.map(b=>[b.id,b])),byId:Object.fromEntries(units.map(u=>[u.id,u]))};
  root.GameData = data;
  if (typeof module !== 'undefined' && module.exports) module.exports = data;
})(typeof window !== 'undefined' ? window : globalThis);
