(function(root){'use strict';
 const D=root.GameData||(typeof require!=='undefined'&&require('./data')),H=root.Hex||(typeof require!=='undefined'&&require('./grid')),M=root.GameMaps||(typeof require!=='undefined'&&require('./maps'));
 const clone=M.clone,ordered=list=>[...list].sort((a,b)=>a.id.localeCompare(b.id)),loc=(a,b)=>a.q===b.q&&a.r===b.r;
 const gridCache=new WeakMap();const cell=(s,p)=>{if(!p)return null;let map=gridCache.get(s.cells);if(!map){map=new Map(s.cells.map(c=>[H.key(c.q,c.r),c]));gridCache.set(s.cells,map);}return map.get(H.key(p.q,p.r));},unit=(s,id)=>s.units.find(u=>u.id===id),building=(s,id)=>s.buildings.find(b=>b.id===id),occupied=(s,p)=>s.units.find(u=>loc(u,p)&&u.hp>0);
 const player=(s,id=s.actor)=>s.players.find(p=>p.id===id),allied=(s,a,b)=>!!a&&!!b&&player(s,a)?.teamId===player(s,b)?.teamId;
 const alive=s=>s.players.filter(p=>!p.eliminated),ownUnits=(s,id=s.actor)=>s.units.filter(u=>u.owner===id&&u.hp>0),ownBuildings=(s,id=s.actor)=>s.buildings.filter(b=>b.owner===id);
 // Only command headquarters and production facilities have structural HP.
 const hasBuildingHealth=b=>!!b&&(b.type==='hq'||D.buildingById[b.type]?.group==='production');
 const buildingActive=b=>!!b&&b.state==='complete'&&(!hasBuildingHealth(b)||b.hp>0);
 const buildingRecoveryRate=b=>[.05,.075,.1][b.level-1]||.05;
 function normalizeBuilding(b){const d=D.buildingById[b.type],normal={...clone(b),state:b.state||'complete',stock:b.stock||[],order:b.order||null};normal.maxHp=hasBuildingHealth(b)?(normal.state==='foundation'?d.hp/2:d.hp):null;normal.hp=hasBuildingHealth(b)?(b.hp??normal.maxHp):null;return normal;}
 function repairCost(b){const d=D.buildingById[b.type];return {money:Math.ceil((d.cost||d.hp)*b.level/2),energy:Math.ceil(d.hp/20)};}
 function repairBuildingReason(s,b){if(!b||b.owner!==s.actor)return '只能修复己方设施';if(!hasBuildingHealth(b))return '收入据点没有建筑生命值';if(b.state!=='complete')return '施工建筑不能重建';if(b.hp>0)return '只有被摧毁的设施需要付费重建';const guard=occupied(s,b);if(guard&&!allied(s,b.owner,guard.owner))return '设施内仍有敌军';const cost=repairCost(b),resources=player(s).resources;if(resources.money<cost.money)return '重建金钱不足';if(resources.energy<cost.energy)return '重建能源不足';return null;}
 const count=(s,id=s.actor)=>ownUnits(s,id).length+ownBuildings(s,id).reduce((n,b)=>n+b.stock.length+(b.order?.kind==='unit'?1:0),0);
 const difficultyProfiles=Object.freeze({easy:Object.freeze({id:'easy',hp:85,damage:85,armor:90,resources:100,intelligence:0}),standard:Object.freeze({id:'standard',hp:100,damage:100,armor:100,resources:100,intelligence:1}),hard:Object.freeze({id:'hard',hp:100,damage:100,armor:100,resources:100,intelligence:2}),hell:Object.freeze({id:'hell',hp:120,damage:120,armor:110,resources:150,intelligence:3})});
 function difficulty(value='standard'){const id=typeof value==='object'?value?.settings?.difficulty:value;const mapped=({training:'easy',challenge:'hard'}[id]||id);return Object.hasOwn(difficultyProfiles,mapped)?mapped:'standard';}
 function profile(s,owner){return difficultyProfiles[player(s,owner)?.controller==='ai'?difficulty(s):'standard'];}
 function unitStats(s,u){const d=D.byId[u.type],p=s?.players?profile(s,u.owner):difficultyProfiles.standard;return {...d,hp:Math.round(d.hp*p.hp/100),damage:Math.round(d.damage*p.damage/100),armor:Math.round(d.armor*p.armor/100),damageMultiplier:p.damage/100,difficulty:p.id};}
 function tuneUnit(s,u){const d=D.byId[u.type],max=unitStats(s,u).hp,oldMax=u.maxHp??d.hp;u.hp=Math.min(max,Math.max(1,Math.round((u.hp??oldMax)*max/oldMax)));u.maxHp=max;u.difficultyApplied=player(s,u.owner)?.controller==='ai'?difficulty(s):'player';return u;}
 function normalizeUnit(u,s){const d=D.byId[u.type],normal={...u,hp:u.hp??d.hp,maxHp:d.hp,ap:2,counterRemaining:1,spentMove:0,roadEligible:true,movedSinceOwnStart:false,repairUsed:false,cooldownReady:0,status:{}};return s?.players?tuneUnit(s,normal):normal;}
 function teams(count,preset){const ids=Array.from({length:count},(_,i)=>`P${i+1}`);let team=ids,order=ids;if(preset==='2v2'&&count===4){team=['A','A','B','B'];order=['P1','P3','P2','P4'];}if(preset==='3v3'&&count===6){team=['A','A','A','B','B','B'];order=['P1','P4','P2','P5','P3','P6'];}if(preset==='2v2v2'&&count===6){team=['A','A','B','B','C','C'];order=['P1','P3','P5','P2','P4','P6'];}return {team,order};}
 function create(map,settings={}){const campaign=!!map.mission,seatIds=map.seats.map(x=>x.id),setup=teams(map.playerCount,settings.teams||'ffa');let turnOrder=campaign?seatIds:setup.order;const first=settings.startIndex??0;turnOrder=[...turnOrder.slice(first),...turnOrder.slice(0,first)];const s={schemaVersion:'game-0.7',ruleVersion:'0.7',mode:campaign?'campaign':'free',map:clone(map),cells:M.cells(map),deposits:clone(map.deposits),settings:{difficulty:'standard',victoryMode:'capture_hq',fog:true,...settings,difficulty:difficulty(settings.difficulty)},players:seatIds.map((id,i)=>({id,name:campaign?(id==='union'?'联合协调队':'赤岩防卫军'):(settings.names?.[i]||`指挥官 ${i+1}`),teamId:campaign?id:setup.team[i],controller:campaign?(id==='union'?'local_human':'ai'):(settings.controllers?.[i]|| (i?'ai':'local_human')),factionStyle:i%2?'red':'union',color:['#63dbc2','#f18d79','#78baff','#d3a0f7','#efce71','#8cc679'][i],resources:campaign?clone(map.mission.initialResources[id]):{money:600,energy:60},ownTurnIndex:0,eliminated:false,originalHqId:map.seats[i].originalHqId,hqGuardId:map.seats[i].hqGuardId,stats:{produced:0,captures:0,constructed:0,repaired:0,upgraded:0,energy:0,kills:0,damage:0},exercise:{}})),units:map.initialUnits.map(normalizeUnit),buildings:map.buildings.map(b=>normalizeBuilding({...b,owner:seatIds.includes(b.owner)?b.owner:null,stock:[],order:null})),turnOrder,actor:turnOrder[0],round:1,pendingPlayers:[...turnOrder],turnStarted:false,revision:0,nextId:1,result:null,logs:[],events:[],vision:{},explored:{},knownBuildings:{},revealed:{},activeMillis:0,drawVotes:[],handoffRequired:false,mission:campaign?clone(map.mission):null,enemyPlan:campaign?map.mission.enemyProductionPlan.map((p,i)=>({...p,id:`plan-${i}`,state:'pending'})):[],story:null,aiDifficultyVersion:1,facilityRulesVersion:1};for(const u of s.units)tuneUnit(s,u);for(const p of s.players){const multiplier=profile(s,p.id).resources/100;p.resources.money=Math.min(3000,Math.round(p.resources.money*multiplier));p.resources.energy=Math.min(300,Math.round(p.resources.energy*multiplier));s.explored[p.id]=campaign||s.mode==='free'?s.cells.map(c=>H.key(c.q,c.r)):[];s.knownBuildings[p.id]=Object.fromEntries(s.buildings.map(b=>[b.id,clone(b)]));s.revealed[p.id]=[];}vision(s);if(!settings.deferStart)begin(s);return s;}
 function visible(s,pid,e){if(!s.settings.fog||s.mission?.fog===false)return true;if(allied(s,pid,e.owner))return true;const v=s.vision[pid];if(!v)return false;const type=e.type&&D.byId[e.type]?H.domain(e,cell(s,e)):(e.type==='energyplatform'?'sea':'land');return (type==='air'?v.air:v.ground).includes(H.key(e.q,e.r))||(s.revealed[pid]||[]).includes(e.id);}
 function vision(s){for(const p of s.players){const partners=alive(s).filter(x=>x.teamId===p.teamId),ground=new Set(),air=new Set();for(const a of partners){for(const u of ownUnits(s,a.id)){const ud=D.byId[u.type],range=ud.vision+(u.status.scan?2:0),flying=ud.branch==='air';for(const c of s.cells)if(H.distance(u,c)<=range){air.add(H.key(c.q,c.r));if(flying||H.los(s.cells,u,c))ground.add(H.key(c.q,c.r));}}for(const b of ownBuildings(s,a.id)){ground.add(H.key(b.q,b.r));air.add(H.key(b.q,b.r));if(buildingActive(b))for(const c of s.cells)if(H.distance(b,c)<=1){ground.add(H.key(c.q,c.r));air.add(H.key(c.q,c.r));}}for(const id of s.revealed[a.id]||[]){const e=unit(s,id);if(e){ground.add(H.key(e.q,e.r));air.add(H.key(e.q,e.r));}}}s.vision[p.id]={ground:[...ground],air:[...air]};s.explored[p.id]=[...new Set([...s.explored[p.id],...ground,...air])];for(const b of s.buildings)if(visible(s,p.id,b)||allied(s,p.id,s.knownBuildings[p.id][b.id]?.owner))s.knownBuildings[p.id][b.id]=clone(b);}}
 function emit(s,kind,text,entities=[],extra={}){const audiences=s.players.filter(p=>kind==='turn'?allied(s,p.id,s.actor):entities.some(e=>allied(s,p.id,e.owner)||visible(s,p.id,e))||extra.oldOwner&&allied(s,p.id,extra.oldOwner)).map(p=>p.id);if(!entities.length)audiences.push(...s.players.map(p=>p.id));const messages=Object.fromEntries(audiences.map(id=>[id,entities.every(e=>allied(s,id,e.owner)||visible(s,id,e))?text:extra.oldOwner&&allied(s,id,extra.oldOwner)?'己方建筑已被接管':entities.some(e=>allied(s,id,e.owner))?'己方部队受到攻击或发生损失':'当前视野内发生军事行动']));s.logs.push({revision:s.revision,kind,text,messages,audiences:[...new Set(audiences)],...extra});if(s.logs.length>600)s.logs.shift();s.events.push({kind,actor:s.actor,round:s.round,ownTurn:player(s)?.ownTurnIndex,...extra});if(s.events.length>600)s.events.shift();}
 function income(s,id){const gain=ownBuildings(s,id).filter(buildingActive).reduce((n,b)=>{const d=D.buildingById[b.type];n.money+=d.money[b.level-1]||0;n.energy+=d.energy[b.level-1]||0;return n;},{money:0,energy:0});const multiplier=profile(s,id).resources/100;return {money:Math.round(gain.money*multiplier),energy:Math.round(gain.energy*multiplier)};}
 function deploymentCell(s,b){if(!b||D.buildingById[b.type]?.group!=='production')return null;if(b.deployment)return cell(s,b.deployment);const home=cell(s,b);return b.type==='port'&&home?.terrain!=='ocean'?H.neighbors(b).map(c=>cell(s,c)).find(c=>c?.terrain==='ocean')||home:home;}
 function deploymentPositionReason(s,b,c){if(!b||D.buildingById[b.type]?.group!=='production')return '该建筑不是出产设施';if(!c||!cell(s,c)||H.distance(b,c)>1)return '部署格必须是设施格或邻格';if(!D.units.some(d=>d.facility===b.type&&Number.isFinite(H.cost(d.id,c))))return '该地形不支持此设施单位';const models=[...b.stock.map(x=>x.type),...(b.order?.kind==='unit'?[b.order.type]:[])];if(models.some(type=>!D.byId[type]||!Number.isFinite(H.cost(type,c))))return '部署格不支持在制或库存型号';return null;}
 function deploymentReason(s,b,c){const reason=facilityReason(s,b);if(reason)return reason;const position=deploymentPositionReason(s,b,c);if(position)return position;if(!visible(s,s.actor,c))return '部署格不在当前视野内';return null;}
 function releaseStock(s,b,stock,c,automatic=false){const deployed=normalizeUnit({id:`UNIT-${s.nextId++}`,type:stock.type,owner:b.owner,q:c.q,r:c.r},s);if(automatic&&b.owner!==s.actor)deployed.ap=0;s.units.push(deployed);b.stock=b.stock.filter(x=>x.id!==stock.id);player(s,b.owner).exercise.deployment=true;emit(s,'deployment',`${player(s,b.owner).name}：${D.byId[stock.type].type} ${automatic?'自动出库':'完成部署'}`,[deployed,b],{buildingId:b.id,stockId:stock.id,type:stock.type,unitId:deployed.id,q:c.q,r:c.r,automatic,owner:b.owner,actor:b.owner,ownTurn:player(s,b.owner).ownTurnIndex});return deployed;}
 function flushDeployments(s,released=new Set()){if(s.result||s.story?.combatLocked)return [];const deployed=[];for(const b of ordered(s.buildings)){if(released.has(b.id)||!b.owner||player(s,b.owner)?.eliminated||b.hp<=0||b.state!=='complete'||D.buildingById[b.type]?.group!=='production'||!b.stock.length)continue;const c=deploymentCell(s,b),stock=b.stock[0];if(!c||occupied(s,c)||!Number.isFinite(H.cost(stock.type,c)))continue;if(count(s,b.owner)>24)continue;deployed.push(releaseStock(s,b,stock,c,true));released.add(b.id);}return deployed;}
 function completeProduction(s){for(const b of ordered(s.buildings)){const p=player(s,b.owner);if(!p||p.eliminated||b.hp<=0||b.state!=='complete'||b.order?.kind!=='unit'||b.order.readyOwnTurn>p.ownTurnIndex||b.stock.length>=3)continue;const o=b.order;b.stock.push({id:o.id,type:o.type,sourceId:b.id});b.order=null;p.stats.produced++;p.exercise.production=true;if(D.byId[o.type].tier===3)p.exercise.tier3=true;emit(s,'production',`${p.name}：${D.byId[o.type].type} 完成生产`,[b],{type:o.type,buildingId:b.id,owner:b.owner,actor:b.owner,ownTurn:p.ownTurnIndex});}}
 function settleDeployments(s,released=new Set()){if(s.result||s.story?.combatLocked)return;flushDeployments(s,released);completeProduction(s);flushDeployments(s,released);}
 function begin(s){if(s.result||s.turnStarted)return;const p=player(s),released=new Set();p.ownTurnIndex++;for(const u of ownUnits(s)){delete u.status.entrench;delete u.status.anchor;delete u.status.scan;if(u.status.jam&&u.status.jam.protectedUntil<=p.ownTurnIndex)delete u.status.jam;}
  const gain=income(s,p.id);p.resources.money=Math.min(3000,p.resources.money+gain.money);p.resources.energy=Math.min(300,p.resources.energy+gain.energy);
  for(const b of ordered(ownBuildings(s))){if(hasBuildingHealth(b)&&b.hp<=0)continue;let completed=false;if(b.state==='foundation'&&b.readyOwnTurn<=p.ownTurnIndex){const old=b.maxHp;b.state='complete';if(hasBuildingHealth(b)){b.maxHp=D.buildingById[b.type].hp;b.hp=Math.min(b.maxHp,b.hp+b.maxHp-old);}else b.hp=b.maxHp=null;delete b.readyOwnTurn;completed=true;}if(b.order?.kind==='upgrade'&&b.order.readyOwnTurn<=p.ownTurnIndex){b.level++;b.order=null;p.stats.upgraded++;p.exercise.upgrade=true;}if(!completed&&hasBuildingHealth(b)&&buildingActive(b)&&b.hp<b.maxHp){const gain=Math.min(b.maxHp-b.hp,Math.ceil(b.maxHp*buildingRecoveryRate(b)));b.hp+=gain;emit(s,'buildingRecovery',`${D.buildingById[b.type].name} 自动恢复 ${gain} HP`,[b],{buildingId:b.id,amount:gain,hp:b.hp});}}
  // Existing FIFO entries release first, so a ready order can use the freed
  // queue slot. A spawned unit immediately occupies the one deployment cell.
  settleDeployments(s,released);
  for(const u of ownUnits(s)){u.ap=2;u.spentMove=0;u.roadEligible=true;u.movedSinceOwnStart=false;u.counterRemaining=1;u.repairUsed=false;u.movePenalty=0;if(u.status.shock){if(u.status.shock.turn===p.ownTurnIndex)u.movePenalty=1;else if(u.status.shock.turn<p.ownTurnIndex)delete u.status.shock;}if(u.status.jam?.turn===p.ownTurnIndex)u.ap=1;}
  s.turnStarted=true;vision(s);checkVictory(s);emit(s,'turn',`${p.name} 第 ${p.ownTurnIndex} 回合：收入 ¤${gain.money} / ⚡${gain.energy}`,ownBuildings(s),{income:gain});}
 function end(s){const prev=player(s);for(const u of ownUnits(s))u.ap=0;s.revealed[prev.id]=[];s.pendingPlayers=s.pendingPlayers.filter(id=>id!==prev.id&&!player(s,id).eliminated);if(!s.pendingPlayers.length){s.round++;s.pendingPlayers=s.turnOrder.filter(id=>!player(s,id).eliminated);}const index=s.turnOrder.indexOf(prev.id);for(let n=1;n<=s.turnOrder.length;n++){const id=s.turnOrder[(index+n)%s.turnOrder.length];if(s.pendingPlayers.includes(id)){s.actor=id;break;}}s.turnStarted=false;s.handoffRequired=player(s).controller==='local_human'&&alive(s).filter(p=>p.controller==='local_human').length>1;begin(s);}
 function canAct(s,u){return s.result?'对局已结束':!s.turnStarted?'回合尚未开始':!u||u.hp<=0?'单位不存在':u.owner!==s.actor?'只能操作当前玩家的单位':u.ap<1?'行动点已耗尽':null;}
 function movement(s,u){
  if(canAct(s,u)||u.status.anchor)return new Map();
  const base=Math.max(1,D.byId[u.type].move-(u.movePenalty||0)),air=D.byId[u.type].branch==='air';
  // Friendly cells are transit nodes, but never legal stopping cells.
  const routes=H.routes(s.cells,u,u.type,c=>{const other=occupied(s,c);return other&&other.id!==u.id&&!allied(s,u.owner,other.owner)&&visible(s,u.owner,other);},base+1-u.spentMove,{budget:base,spent:u.spentMove,roadEligible:u.roadEligible,air});
  for(const [k,p] of routes){const other=occupied(s,p);if(other&&other.id!==u.id&&visible(s,u.owner,other)||p.cost+u.spentMove>base+(!air&&u.roadEligible&&p.road?1:0)||p.energy>player(s,u.owner).resources.energy)routes.delete(k);}
  return routes;
 }
 function combatTarget(s,a,t){if(t&&!D.byId[t.type]){const guard=occupied(s,t);if(guard&&guard.owner&&!allied(s,a?.owner,guard.owner)&&visible(s,a?.owner,guard))return guard;}return t;}
 function shelter(s,t){return D.byId[t?.type]&&s.buildings.find(b=>loc(b,t)&&hasBuildingHealth(b)&&buildingActive(b)&&allied(s,b.owner,t.owner));}
 function splitDamage(s,t,raw){const b=shelter(s,t),shared=b?Math.min(b.hp,Math.floor(raw/4)):0;return {damage:Math.min(t.hp,raw-shared),buildingId:shared?b.id:null,buildingDamage:shared,buildingHp:b?b.hp-shared:null};}
 function attackReason(s,a,t,counter=false){t=combatTarget(s,a,t);if(!a||!t||a.hp<=0)return '目标已经失去作战能力';if(!D.byId[t.type]&&!hasBuildingHealth(t))return '收入据点只能占领，不能攻击';if(t.hp<=0)return '目标已经失去作战能力';if(!counter){const err=canAct(s,a);if(err)return err;if(!t.owner||allied(s,a.owner,t.owner))return '目标不是敌方';if(!visible(s,a.owner,t))return '目标不在当前视野内';if(!D.byId[a.type].fireAfterMove&&a.movedSinceOwnStart)return '炮兵移动后无法开火';}const ad=D.byId[a.type],td=D.byId[t.type],state=td?H.domain(t,cell(s,t)):'land',as=H.domain(a,cell(s,a)),range=H.distance(a,t);if(state==='air'&&!ad.antiAir)return '该单位没有对空能力';if(range<ad.minRange||range>ad.maxRange)return '目标不在射程内';if(as!=='air'&&state!=='air'&&!ad.indirect&&!H.los(s.cells,a,t))return '射线被山脊或废墟阻挡';if(counter&&(!ad.counter||a.counterRemaining<1))return '无法反击或反击次数已用尽';return null;}
 function standardDamage(s,a,t,skill=''){const ad=D.byId[a.type],td=D.byId[t.type],state=td?H.domain(t,cell(s,t)):(t.type==='energyplatform'?'sea':'land'),category=td?.category||'armored';let armor=(td?unitStats(s,t).armor:D.buildingById[t.type].armor)+(t.status?.anchor?20:0);if(skill==='pierce')armor=Math.max(0,armor-10);let cover=0;if(td&&state!=='air'){cover=D.terrain[cell(s,t).terrain].defense||0;if(t.status.entrench)cover+=10;}
  let extra=skill==='sniper'?20:skill==='shock'?-10:0;if(a.type==='antitank'&&!a.movedSinceOwnStart&&category==='armored')extra+=10;return Math.max(10,Math.round((ad.damage+(category==='armored'?ad.bonusArmor:ad.bonusLight)+(state==='air'?ad.bonusAir:state==='sea'?ad.bonusSea:ad.bonusLand)+extra)*unitStats(s,a).damageMultiplier)-armor-cover);}
 function attackPreview(s,a,t,skill=''){t=combatTarget(s,a,t);const reason=attackReason(s,a,t);if(reason)return {reason};const standard=standardDamage(s,a,t,skill),hit=splitDamage(s,t,standard),targetHp=t.hp-hit.damage;let counterHit={damage:0,buildingDamage:0,buildingId:null,buildingHp:null},counterReason='建筑不反击';if(D.byId[t.type]){counterReason=targetHp<=0?'目标将被击毁':D.byId[a.type].indirect?'间接攻击不触发反击':attackReason(s,t,a,true);if(!counterReason)counterHit=splitDamage(s,a,Math.floor(standardDamage(s,t,a)*(D.byId[t.type].dedicatedAA?1.5:.5)));}return {...hit,targetId:t.id,standard,counter:counterHit.damage,counterBuildingId:counterHit.buildingId,counterBuildingDamage:counterHit.buildingDamage,counterBuildingHp:counterHit.buildingHp,targetHp,attackerHp:a.hp-counterHit.damage,counterReason,counterRemaining:t.counterRemaining};}
 function ruin(s,b){b.hp=0;b.state='complete';b.maxHp=D.buildingById[b.type].hp;b.order=null;b.stock=[];delete b.readyOwnTurn;for(const p of s.enemyPlan)if(`${s.mission?.id}-${p.facility}`===b.id&&p.state==='pending')p.state='cancelled';}
 function hurt(s,t,amount,source){const loss=Math.min(t.hp,amount);t.hp-=loss;const scorer=player(s,source.owner);scorer.stats.damage+=loss;if(t.hp<=0){if(D.byId[t.type]){s.units=s.units.filter(u=>u.id!==t.id);scorer.stats.kills++;}else ruin(s,t);}return loss;}
 function attack(s,a,t,skill=''){t=combatTarget(s,a,t);const preview=attackPreview(s,a,t,skill);if(preview.reason)return preview.reason;a.ap=0;const cover=building(s,preview.buildingId),counterCover=building(s,preview.counterBuildingId);if(cover)hurt(s,cover,preview.buildingDamage,a);hurt(s,t,preview.damage,a);if(t.hp>0&&skill==='shock'&&D.byId[t.type]&&!t.status.shock){t.status.shock={turn:player(s,t.owner).ownTurnIndex+1};}if(preview.counter>0||preview.counterBuildingDamage>0){t.counterRemaining--;if(counterCover)hurt(s,counterCover,preview.counterBuildingDamage,t);hurt(s,a,preview.counter,t);if(D.byId[t.type].dedicatedAA)player(s,t.owner).exercise.aaCounter=true;}emit(s,'first_legal_attack',`${D.byId[a.type].type} 攻击 ${D.byId[t.type]?.type||D.buildingById[t.type].name}：${preview.damage}${cover?`，设施分担 ${preview.buildingDamage}`:''}，反击 ${preview.counter}`,[a,t,...[cover,counterCover].filter(Boolean)],{preview});return null;}
 function captureReason(s,u,b){const err=canAct(s,u);if(err)return err;if(!b)return '建筑不存在';if(allied(s,u.owner,b.owner))return '不能占领己方或盟友建筑';if(!visible(s,u.owner,b))return '建筑不在当前视野内';if(!loc(u,b))return '占领必须到达建筑本格';const g=occupied(s,b);if(g&&!allied(s,u.owner,g.owner))return '建筑格内仍有敌方守军';return null;}
 function clearOrders(b){b.order=null;b.stock=[];}
 function eliminate(s,id,capturedId=null){const p=player(s,id);if(!p||p.eliminated)return;p.eliminated=true;p.resources={money:0,energy:0};s.units=s.units.filter(u=>u.owner!==id);for(const b of ownBuildings(s,id)){clearOrders(b);if(b.id!==capturedId){b.owner=null;if(b.state==='foundation'){b.state='complete';b.maxHp=hasBuildingHealth(b)?D.buildingById[b.type].hp:null;b.level=1;b.hp=hasBuildingHealth(b)?0:null;delete b.readyOwnTurn;}}}s.pendingPlayers=s.pendingPlayers.filter(x=>x!==id);emit(s,'elimination',`${p.name} 已出局`,[],{playerId:id});}
 function capture(s,u,b,extra={}){const reason=captureReason(s,u,b);if(reason)return reason;const old=b.owner;clearOrders(b);b.owner=u.owner;if(b.state==='foundation'){b.state='complete';b.level=1;b.hp=hasBuildingHealth(b)?0:null;b.maxHp=hasBuildingHealth(b)?D.buildingById[b.type].hp:null;delete b.readyOwnTurn;}u.ap=0;s.lastCaptureId=b.id;player(s).stats.captures++;player(s).exercise.capture=true;if(H.domain(u,cell(s,u))==='sea')player(s).exercise.seaCapture=true;for(const plan of s.enemyPlan)if(`${s.mission?.id}-${plan.facility}`===b.id&&plan.state==='pending')plan.state='cancelled';const kind=s.mission&&old==='red'&&D.buildingById[b.type].group==='production'?'first_capture_enemy_production_facility':s.mission?.id==='C07'&&b.key==='NC'?'first_capture_central_city':'capture';emit(s,kind,`${player(s).name} 接管 ${D.buildingById[b.type].name}`,[u,b],{oldOwner:old,buildingId:b.id,unitId:u.id,q:u.q,r:u.r,...extra});if(!s.mission&&s.settings.victoryMode==='capture_hq'){const seat=s.players.find(p=>p.originalHqId===b.id);if(seat&&!allied(s,seat.id,u.owner))eliminate(s,seat.id,b.id);}return null;}
 function tileReason(s,type,c,owner=s.actor,ignoreTemporary=false){if(!c)return '格子不存在';if(type==='hq')return '总部只能由地图预设';if(s.buildings.some(b=>loc(b,c)))return '该格已有建筑';if(!ignoreTemporary&&!visible(s,owner,c))return '该格不在当前视野内';const o=occupied(s,c);if(!ignoreTemporary&&o&&!allied(s,owner,o.owner))return '敌方单位占用该格';const support=ownBuildings(s,owner).some(b=>['hq','city'].includes(b.type)&&buildingActive(b)&&H.distance(b,c)<=2);if(!support)return '需要在己方完好总部或城市两格内';const hasDeposit=(which)=>s.deposits[which]?.some(p=>p[0]===c.q&&p[1]===c.r);if(type==='energyplatform')return c.terrain==='ocean'&&hasDeposit('sea')?null:'海上平台需要海洋能源点';if(!['plain','road','coast'].includes(c.terrain))return '建筑需要平地、道路或海岸';if(type==='energyfield'&&!hasDeposit('land'))return '能源站需要陆地能源点';if(type==='port'&&(c.terrain!=='coast'||!H.neighbors(c).some(n=>cell(s,n)?.terrain==='ocean')))return '军港需要邻海的海岸';return null;}
 function constructReason(s,type,c){if(s.mission&&!s.mission.constructionEnabled)return '本关禁止新建建筑';if(!D.buildingById[type])return '建筑型号不存在';if(ownBuildings(s).some(b=>b.state==='foundation'))return '每方同时只能新建一座建筑';const err=tileReason(s,type,c);if(err)return err;if(player(s).resources.money<D.buildingById[type].cost)return '金钱不足';return null;}
 function facilityReason(s,b){return !b||b.owner!==s.actor?'只能操作己方建筑':hasBuildingHealth(b)&&b.hp<=0?'设施已损毁，请付费重建':b.state!=='complete'?'建筑尚未完工':null;}
 function productionReason(s,b,type){const err=facilityReason(s,b);if(err)return err;const d=D.byId[type];if(!d||d.facility!==b.type)return '单位与设施不匹配';if(b.level<d.tier)return '设施等级不足';if(s.mission&&(d.tier>s.mission.authorizationCeilings[b.type]||!s.mission.playerProductionWhitelist.includes(type))&&s.actor==='union')return '本关生产授权尚未开放';if(s.mission&&s.actor==='red'&&!s.enemyPlan.some(plan=>plan.state==='pending'&&plan.unit===type&&`${s.mission.id}-${plan.facility}`===b.id&&plan.earliestOwnTurn<=player(s).ownTurnIndex))return '本关敌方有限生产计划未授权';if(b.order)return '设施正在生产或升级';if(b.stock.length>=3)return '设施库存已满';if(count(s)>=24)return '部队、库存与订单合计已达 24';if(player(s).resources.money<d.cost)return '金钱不足';const destination=deploymentCell(s,b);if(!destination||!Number.isFinite(H.cost(type,destination)))return '当前部署格不支持该型号，请先设置部署格';return null;}
 function upgradeReason(s,b){const err=facilityReason(s,b);if(err)return err;const d=D.buildingById[b.type];if(b.level>=d.maxLevel)return '建筑已达最高等级';if(s.mission&&b.level>=(s.mission.authorizationCeilings[b.type]||3))return '本关升级授权尚未开放';if(b.order)return '设施正在生产或升级';if(player(s).resources.money<d.upgrades[b.level-1])return '金钱不足';return null;}
 function deployReason(s,b,stock,c){const err=facilityReason(s,b);if(err)return err;if(!stock||stock.sourceId!==b.id||D.byId[stock.type]?.facility!==b.type||!b.stock.some(x=>x.id===stock.id))return '库存不属于此设施';if(!c||H.distance(b,c)>1)return '只能部署到设施格或邻格';if(!visible(s,s.actor,c))return '部署格不在视野内';if(occupied(s,c))return '该格已有单位';if(!Number.isFinite(H.cost(stock.type,c)))return '该单位无法部署到此地形';return null;}
 function skillReason(s,u,target){const err=canAct(s,u);if(err)return err;const skill=D.byId[u.type].skill;if(['基础作战','驻守','伏击','防空反击'].includes(skill))return '该技能为被动或基础作战';if(player(s).ownTurnIndex<u.cooldownReady)return `技能冷却至第 ${u.cooldownReady} 己方回合`;
  if(skill==='应急修复'){if(u.repairUsed)return '本回合已经修复过';if(!target||target.owner!==u.owner||target.id===u.id)return '需要另一己方单位或建筑';if(!visible(s,u.owner,target)||H.distance(u,target)>1)return '修复需要同格或邻格且可见';if(D.byId[target.type]&&H.distance(u,target)!==1)return '单位修复需要邻格';if(target.state==='foundation')return '不能修复施工建筑';if(!D.byId[target.type]){if(!hasBuildingHealth(target))return '收入据点没有建筑生命值';if(target.hp<=0)return '废墟请在设施管理中付费重建';if(target.hp>=target.maxHp/2)return '设施主动修复上限为 50%，等待自动恢复';}if(target.hp>=target.maxHp)return '目标生命值已满';if(target.repairedOnOwnerTurn===player(s,target.owner).ownTurnIndex)return '目标本回合已经接受修复';return null;}
  if(skill==='链路干扰'){if(!target||!D.byId[target.type]||allied(s,u.owner,target.owner)||!visible(s,u.owner,target)||H.distance(u,target)<1||H.distance(u,target)>2)return '需要一至两格内可见敌方单位';if(target.status.jam)return '目标处于干扰或保护期';if(H.domain(u,cell(s,u))!=='air'&&H.domain(target,cell(s,target))!=='air'&&!H.los(s.cells,u,target))return '干扰射线被阻挡';return null;}
  if(['穿甲弹','震荡弹','定点狙击'].includes(skill)){target=combatTarget(s,u,target);if(skill==='定点狙击'&&u.movedSinceOwnStart)return '狙击需要本回合未移动';if(skill==='震荡弹'&&!D.byId[target?.type])return '震荡弹只能攻击单位';return attackReason(s,u,target);}return null;}
 function skill(s,u,t){const err=skillReason(s,u,t);if(err)return err;const name=D.byId[u.type].skill,now=player(s).ownTurnIndex;u.cooldownReady=name==='应急修复'?now:now+(['锚定防线','链路干扰'].includes(name)?3:2);u.ap=0;if(name==='构筑掩体')u.status.entrench=true;if(name==='锚定防线')u.status.anchor=true;if(name==='主动扫描'){u.status.scan=true;if(D.byId[u.type].branch==='air')player(s).exercise.scan=true;emit(s,'first_successful_scan',`${D.byId[u.type].type} 开启主动扫描`,[u]);}if(name==='应急修复'){const restored=Math.min(D.byId[t.type]?t.maxHp:Math.floor(t.maxHp/2),t.hp+40)-t.hp;t.hp+=restored;u.repairUsed=true;t.repairedOnOwnerTurn=player(s,t.owner).ownTurnIndex;player(s).stats.repaired++;player(s).exercise.repair=true;emit(s,'first_successful_repair',`${D.byId[u.type].type} 修复目标 ${restored} HP`,[u,t]);}if(name==='链路干扰'){t.status.jam={turn:player(s,t.owner).ownTurnIndex+1,protectedUntil:player(s,t.owner).ownTurnIndex+3};emit(s,'first_successful_jam','链路干扰已施加：目标下次己方回合 1 AP',[u,t]);}if(['穿甲弹','震荡弹','定点狙击'].includes(name)){u.ap=1;return attack(s,u,t,{'穿甲弹':'pierce','震荡弹':'shock','定点狙击':'sniper'}[name]);}return null;}
 function recovery(s,p){if(ownUnits(s,p.id).length||ownBuildings(s,p.id).some(b=>b.stock.length||b.order?.kind==='unit'||b.state==='foundation'&&(['city','barracks','factory','port','airfield'].includes(b.type))||buildingActive(b)&&D.buildingById[b.type].group==='production'))return true;const gain=income(s,p.id);if(ownBuildings(s,p.id).some(b=>hasBuildingHealth(b)&&b.state==='complete'&&b.hp===0&&(p.resources.money>=repairCost(b).money||gain.money>0)&&(p.resources.energy>=repairCost(b).energy||gain.energy>0)))return true;return s.cells.some(c=>['barracks','factory','port','airfield'].some(type=>!tileReason(s,type,c,p.id,true)));}
 function checkVictory(s){if(s.result)return;const living=alive(s),teamIds=[...new Set(living.map(p=>p.teamId))];let winner=null,reason=null;if(s.mission&&s.settings.victoryMode==='capture_hq'){const lost=living.find(p=>{const hq=building(s,p.originalHqId);return hq?.owner&&!allied(s,p.id,hq.owner);});if(lost){winner=player(s,building(s,lost.originalHqId).owner).teamId;reason='接管敌方原始总部';}}if(!reason&&teamIds.length===1){winner=teamIds[0];reason='其余队伍全部出局';}else if(!reason&&s.settings.victoryMode==='own_all_registered_buildings'){for(const team of teamIds)if(s.buildings.every(b=>b.owner&&player(s,b.owner)?.teamId===team)){winner=team;reason='接管全部登记建筑';break;}}if(!reason&&living.length&&living.every(p=>!recovery(s,p))){reason='所有存活方均无法恢复生产';}if(reason){s.result={winner,winnerTeamId:winner,winningPlayers:living.filter(p=>p.teamId===winner).map(p=>p.id),triggerBuildingId:s.lastCaptureId||null,reason,round:s.round,activeMillis:s.activeMillis,stats:Object.fromEntries(s.players.map(p=>[p.id,clone(p.stats)])),buildingTotal:s.buildings.length};for(const u of s.units)u.ap=0;emit(s,'result',winner?`队伍 ${winner} 获胜：${reason}`:`平局：${reason}`);}}
 function execute(s,command){if(s.result)return {ok:false,error:'对局已经结束'};if(s.story&&(s.story.combatLocked||s.story.queue.length))return {ok:false,error:'请先阅读并确认当前剧情'};if(command.actor&&command.actor!==s.actor)return {ok:false,error:'当前操作方不匹配'};if(!s.turnStarted)return {ok:false,error:'回合尚未开始'};const u=unit(s,command.unitId),b=building(s,command.buildingId),t=unit(s,command.targetId)||building(s,command.targetId),c=cell(s,command),released=new Set();let err=null;
  switch(command.kind){case 'move':{
   err=canAct(s,u);if(err)break;if(u.status.anchor){err='锚定中不能移动';break;}
   const route=movement(s,u).get(H.key(command.q,command.r));if(!route||!route.path.length){err='没有合法移动路线';break;}
   const blocked=route.path.findIndex(next=>{const other=occupied(s,next);return other&&!allied(s,u.owner,other.owner);});
   if(blocked>=0)s.revealed[s.actor].push(occupied(s,route.path[blocked]).id);
   const path=route.path.slice(0,blocked>=0?blocked:route.path.length);
   // An unseen enemy beyond a friendly column must not leave us stacked on it.
   // Stop at the last free cell and charge only the route actually completed.
   while(path.length&&occupied(s,path[path.length-1]))path.pop();
   let steps=0,sea=false;
   for(const next of path){const cost=H.cost(u.type,next),energy=H.energy(u.type,next);u.q=next.q;u.r=next.r;u.spentMove+=cost;u.roadEligible=u.roadEligible&&next.terrain==='road';u.movedSinceOwnStart=true;player(s).resources.energy-=energy;player(s).stats.energy+=energy;sea ||=next.terrain==='ocean';steps++;vision(s);}
   if(steps){u.ap--;player(s).exercise.move=true;emit(s,sea?'first_sea_move':'move',`${D.byId[u.type].type} 移动 ${steps} 格`,[u],{steps});const destinationBuilding=s.buildings.find(b=>loc(b,u));if(u.ap>=1&&destinationBuilding&&!captureReason(s,u,destinationBuilding))capture(s,u,destinationBuilding,{automatic:true});}
   else emit(s,'collision','路线被新发现的单位阻挡',[u]);break;
  }
   case 'attack':err=attack(s,u,t);break;case 'skill':err=skill(s,u,t);break;case 'capture':err=capture(s,u,b);break;
   case 'construct':err=constructReason(s,command.type,c);if(!err){const d=D.buildingById[command.type];player(s).resources.money-=d.cost;const instance=normalizeBuilding({id:`NEW-${s.nextId++}`,type:d.id,owner:s.actor,q:c.q,r:c.r,level:1,state:'foundation',maxHp:d.hp/2,hp:d.hp/2,readyOwnTurn:player(s).ownTurnIndex+1,stock:[],order:null});s.buildings.push(instance);player(s).stats.constructed++;player(s).exercise.construction=true;emit(s,'construction',`${d.name} 开始建设`,[instance]);}break;
   case 'setDeployment':err=deploymentReason(s,b,c);if(!err){b.deployment={q:c.q,r:c.r};emit(s,'deploymentSetting',`${D.buildingById[b.type].name} 更新部署格`,[b],{buildingId:b.id,stockId:b.stock[0]?.id,q:c.q,r:c.r,owner:b.owner});}break;
   case 'repairBuilding':err=repairBuildingReason(s,b);if(!err){const cost=repairCost(b);player(s).resources.money-=cost.money;player(s).resources.energy-=cost.energy;b.hp=Math.floor(b.maxHp/2);player(s).stats.repaired++;player(s).exercise.repair=true;emit(s,'buildingRepair',`${D.buildingById[b.type].name} 重建至 50% HP`,[b],{buildingId:b.id,amount:b.hp,cost});}break;
   case 'upgrade':err=upgradeReason(s,b);if(!err){player(s).resources.money-=D.buildingById[b.type].upgrades[b.level-1];b.order={id:`ORDER-${s.nextId++}`,kind:'upgrade',readyOwnTurn:player(s).ownTurnIndex+1};}break;
   case 'produce':err=productionReason(s,b,command.type);if(!err){player(s).resources.money-=D.byId[command.type].cost;b.order={id:`ORDER-${s.nextId++}`,kind:'unit',type:command.type,readyOwnTurn:player(s).ownTurnIndex+D.byId[command.type].buildTurns};if(s.mission&&s.actor==='red'){const plan=s.enemyPlan.find(p=>p.state==='pending'&&p.unit===command.type&&`${s.mission.id}-${p.facility}`===b.id);plan.state='submitted';b.order.planId=plan.id;}}break;
   case 'cancel':err=facilityReason(s,b);if(!err&&!b.order)err='没有可取消的订单';if(!err)b.order=null;break;
   case 'deploy':{const stock=b?.stock.find(x=>x.id===command.stockId);err=deployReason(s,b,stock,c);if(!err){releaseStock(s,b,stock,c,false);released.add(b.id);}break;}
   case 'end':end(s);break;case 'surrender':eliminate(s,s.actor);checkVictory(s);if(!s.result)end(s);break;
   case 'drawDecline':s.drawVotes=[];break;case 'drawVote':s.drawVotes=[...new Set([...s.drawVotes,s.actor,...alive(s).filter(p=>p.controller==='ai').map(p=>p.id)])];if(alive(s).every(p=>s.drawVotes.includes(p.id))){s.result={winner:null,winnerTeamId:null,winningPlayers:[],triggerBuildingId:null,reason:'各方同意平局',round:s.round,activeMillis:s.activeMillis,stats:Object.fromEntries(s.players.map(p=>[p.id,clone(p.stats)])),buildingTotal:s.buildings.length};for(const a of s.units)a.ap=0;emit(s,'result','平局：各方同意');}break;default:err='未知指令';
  }if(err)return {ok:false,error:err};if(!['drawVote','drawDecline','end'].includes(command.kind))s.drawVotes=[];s.revision++;vision(s);checkVictory(s);if(!s.result){settleDeployments(s,released);vision(s);checkVictory(s);}return {ok:true,revision:s.revision};}
 const api={hasBuildingHealth,buildingActive,buildingRecoveryRate,normalizeBuilding,repairCost,repairBuildingReason,combatTarget,shelter,splitDamage,deploymentCell,deploymentReason,deploymentPositionReason,flushDeployments,difficulty,difficultyProfiles,profile,unitStats,tuneUnit,create,teams,cell,unit,building,occupied,player,allied,alive,ownUnits,ownBuildings,count,visible,vision,income,begin,execute,canAct,movement,attackReason,standardDamage,attackPreview,captureReason,constructReason,tileReason,productionReason,facilityReason,upgradeReason,deployReason,skillReason,checkVictory,recovery,normalizeUnit};root.Game=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
