(function(root){'use strict';
  const D=root.GameData||(typeof require!=='undefined'&&require('./data'));
  const offsets=[[1,0],[0,1],[-1,1],[-1,0],[0,-1],[1,-1]];
  const key=(q,r)=>`${q},${r}`, distance=(a,b)=>Math.max(Math.abs(a.q-b.q),Math.abs(a.r-b.r),Math.abs(a.q+a.r-b.q-b.r));
  const neighbors=c=>offsets.map(([q,r])=>({q:c.q+q,r:c.r+r}));
  const sort=(a,b)=>a.q-b.q||a.r-b.r;
  function domain(u,c){const d=D.byId[u.type];return d.branch==='air'?'air':d.amphibious?(c.terrain==='ocean'?'sea':'land'):d.branch==='navy'?'sea':'land';}
  function cost(type,c){const d=D.byId[type];if(!c||!d)return Infinity;if(d.branch==='air')return 1;if(d.amphibious&&c.terrain==='ocean')return 1;if(d.branch==='navy'&&!d.amphibious)return c.terrain==='ocean'?1:Infinity;if(c.terrain==='ocean'||c.terrain==='ridge')return Infinity;return type==='scout'&&c.terrain==='water'?1:D.terrain[c.terrain].cost;}
  function energy(type,c){const d=D.byId[type];return d.amphibious&&c.terrain==='ocean'?(d.seaEnergyPerStep??d.energyPerStep):d.energyPerStep;}
  function roundCube(x,y,z){let q=Math.round(x),s=Math.round(y),r=Math.round(z);const dx=Math.abs(q-x),dy=Math.abs(s-y),dz=Math.abs(r-z);if(dx>dy&&dx>dz)q=-s-r;else if(dy>dz)s=-q-r;else r=-q-s;return {q,r};}
  function ray(a,b,epsilon){const n=distance(a,b),line=[];for(let i=1;i<n;i++){const t=i/n;line.push(roundCube(a.q+(b.q-a.q)*t+epsilon,-a.q-a.r+(-b.q-b.r+a.q+a.r)*t+epsilon,a.r+(b.r-a.r)*t-2*epsilon));}return line;}
  const caches=new WeakMap();
  function los(cells,a,b){let cache=caches.get(cells);if(!cache){cache={map:new Map(cells.map(c=>[key(c.q,c.r),c])),lines:new Map()};caches.set(cells,cache);}const id=`${key(a.q,a.r)}:${key(b.q,b.r)}`;if(!cache.lines.has(id))cache.lines.set(id,[ray(a,b,1e-6),ray(a,b,-1e-6)]);return cache.lines.get(id).some(line=>line.every(c=>!D.terrain[cache.map.get(key(c.q,c.r))?.terrain]?.blocks));}
  function routes(cells,start,type,blocked=()=>false,max=Infinity,policy=null){const map=new Map(cells.map(c=>[key(c.q,c.r),c])),best=new Map(),queue=[];const first={q:start.q,r:start.r,cost:0,energy:0,path:[],road:true,tie:''};best.set(key(start.q,start.r)+(policy?'|true':''),first);queue.push(first);
    while(queue.length){queue.sort((a,b)=>a.cost-b.cost||a.energy-b.energy||a.tie.localeCompare(b.tie));const cur=queue.shift();if(best.get(key(cur.q,cur.r)+(policy?'|'+cur.road:''))!==cur)continue;for(const p of neighbors(cur)){const c=map.get(key(p.q,p.r)),step=cost(type,c);if(!c||!Number.isFinite(step)||blocked(c)||cur.cost+step>max)continue;const next={...p,cost:cur.cost+step,energy:cur.energy+energy(type,c),road:cur.road&&c.terrain==='road',path:[...cur.path,c],tie:cur.tie+`${String(p.q+100).padStart(3,'0')},${String(p.r+100).padStart(3,'0')};`};if(policy&&next.cost+policy.spent>policy.budget+(!policy.air&&policy.roadEligible&&next.road?1:0))continue;const stateKey=key(p.q,p.r)+(policy?'|'+next.road:'');const old=best.get(stateKey);if(!old||next.cost<old.cost||next.cost===old.cost&&(next.energy<old.energy||next.energy===old.energy&&next.tie<old.tie)){best.set(stateKey,next);queue.push(next);}}}if(!policy)return best;const results=new Map();for(const next of best.values()){const id=key(next.q,next.r),old=results.get(id);if(!old||next.cost<old.cost||next.cost===old.cost&&(next.energy<old.energy||next.energy===old.energy&&next.tie<old.tie))results.set(id,next);}return results;}
  const api={offsets,key,distance,neighbors,sort,domain,cost,energy,los,routes};root.Hex=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
