(function(root){'use strict';
 const C=root.GameContent||(typeof require!=='undefined'&&require('./content')),H=root.Hex||(typeof require!=='undefined'&&require('./grid')),D=root.GameData||(typeof require!=='undefined'&&require('./data'));
 const clone=x=>JSON.parse(JSON.stringify(x));
 function canonical(x){return JSON.stringify(sortKeys(x));}function sortKeys(x){return Array.isArray(x)?x.map(sortKeys):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sortKeys(x[k])])):x;}
 function sha256(text){const bytes=new TextEncoder().encode(text),bits=bytes.length*8,data=[...bytes,128];while(data.length%64!==56)data.push(0);for(let i=7;i>=0;i--)data.push(Math.floor(bits/2**(i*8))&255);const primes=[],k=[],h=[];for(let n=2;primes.length<64;n++){if(primes.every(p=>n%p)){primes.push(n);k.push((Math.cbrt(n)%1*2**32)>>>0);if(h.length<8)h.push((Math.sqrt(n)%1*2**32)>>>0);}}const rotr=(x,n)=>(x>>>n)|(x<<(32-n));for(let base=0;base<data.length;base+=64){const w=[];for(let i=0;i<16;i++)w[i]=((data[base+i*4]<<24)|(data[base+i*4+1]<<16)|(data[base+i*4+2]<<8)|data[base+i*4+3])>>>0;for(let i=16;i<64;i++){const a=w[i-15],b=w[i-2];w[i]=(w[i-16]+(rotr(a,7)^rotr(a,18)^(a>>>3))+w[i-7]+(rotr(b,17)^rotr(b,19)^(b>>>10)))>>>0;}let [a,b,c,d,e,f,g,j]=h;for(let i=0;i<64;i++){const t1=(j+(rotr(e,6)^rotr(e,11)^rotr(e,25))+((e&f)^(~e&g))+k[i]+w[i])>>>0,t2=((rotr(a,2)^rotr(a,13)^rotr(a,22))+((a&b)^(a&c)^(b&c)))>>>0;j=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}[a,b,c,d,e,f,g,j].forEach((v,i)=>h[i]=(h[i]+v)>>>0);}return h.map(x=>x.toString(16).padStart(8,'0')).join('');}
 function contentHash(map){return sha256(canonical(Object.fromEntries(['id','size','radius','playerCount','terrain','buildings','initialUnits','seats','deposits'].map(k=>[k,map[k]]))));}
 function fixed(size,count){const f=C.free.fixedMaps.find(m=>m.size===size&&m.playerCount===count);if(!f)throw Error('地图尺寸与人数不匹配');return {...clone(f),actualSource:'fixed',generatorVersion:'0.7'};}
 function cells(map){return Object.entries(map.terrain).flatMap(([terrain,list])=>list.map(([q,r])=>({q,r,terrain}))).sort(H.sort);}
 function terrainObject(list){const t=Object.fromEntries(Object.keys(D.terrain).map(k=>[k,[]]));for(const c of [...list].sort(H.sort))t[c.terrain].push([c.q,c.r]);return t;}
 function campaign(id){const mission=clone(C.campaign.missions.find(m=>m.id===id));if(!mission)throw Error('未知章节');const list=[];for(let q=0;q<mission.size[0];q++)for(let r=0;r<mission.size[1];r++)list.push({q,r,terrain:'plain'});for(const rule of mission.terrainRules)for(const c of list){const w=rule.where;const match=w?Object.entries(w).every(([k,v])=>k.endsWith('Max')?c[k[0]]<=v:k.endsWith('Min')?c[k[0]]>=v:c[k[0]]===v):rule.positions.some(p=>p[0]===c.q&&p[1]===c.r);if(match)c.terrain=rule.terrain;}
  const buildings=mission.buildings.map(b=>({...b,id:`${id}-${b.key}`,q:b.position[0],r:b.position[1],hp:b.hp??D.buildingById[b.type].hp,maxHp:D.buildingById[b.type].hp,state:'complete'}));const initialUnits=mission.units.map(u=>({...u,id:`${id}-${u.key}`,q:u.position[0],r:u.position[1],hp:u.hp??D.byId[u.type].hp}));return {id:mission.mapId,size:mission.size,playerCount:2,terrain:terrainObject(list),buildings,initialUnits,deposits:clone(mission.deposits),mission,actualSource:'campaign',seats:['union','red'].map(owner=>({id:owner,originalHqId:`${id}-${mission.originalHQKeys[owner]}`,hqGuardId:`${id}-${owner==='red'?mission.aiPolicy.hqGuardUnitKey:mission.recommendedPlayerHQGuardUnitKey}`}))};}
 function standard(){const list=[];for(let q=0;q<19;q++)for(let r=0;r<13;r++){let t='plain';if(r<=2||r>=10||q===0||q===18)t='ocean';else if(r===3||r===9||q===1||q===17)t='coast';if(q===9&&r>=4&&r<=8)t='water';if(r===6&&q>=2&&q<=16)t='road';if([[6,5],[12,7],[6,7],[12,5]].some(p=>p[0]===q&&p[1]===r))t='ridge';if([[8,5],[10,7]].some(p=>p[0]===q&&p[1]===r))t='ruins';if([[8,7],[10,5]].some(p=>p[0]===q&&p[1]===r))t='rubble';list.push({q,r,terrain:t});}const b=[['hq',2,6],['city',1,7],['market',1,5],['energyfield',2,8],['barracks',2,5],['factory',2,7],['airfield',3,8],['port',3,3]],u=[['infantry',3,6],['infantry',4,6],['scout',4,5],['engineer',3,7],['marine',4,3],['aafrigate',3,2]],buildings=[],initialUnits=[];for(let n=1;n<=2;n++){const owner=`P${n}`,flip=n===2;for(const [type,q,r] of b)buildings.push({id:`STD-${owner}-${type}`,type,owner,q:flip?18-q:q,r:flip?12-r:r,level:1,hp:D.buildingById[type].hp,state:'complete'});u.forEach(([type,q,r],i)=>initialUnits.push({id:`STD-${owner}-${i}`,type,owner,q:flip?18-q:q,r:flip?12-r:r}));}for(const [type,q,r] of [['city',7,6],['city',11,6],['market',6,4],['market',12,8],['energyfield',8,4],['energyfield',10,8],['energyplatform',8,1],['energyplatform',10,11],['factory',9,6]])buildings.push({id:`STD-N-${q}-${r}`,type,owner:null,q,r,level:1,hp:D.buildingById[type].hp,state:'complete'});return {id:'STANDARD',size:'standard',playerCount:2,terrain:terrainObject(list),buildings,initialUnits,seats:[1,2].map(n=>({id:`P${n}`,originalHqId:`STD-P${n}-hq`})),deposits:{land:[[2,8],[16,4],[8,4],[10,8],[3,7],[15,5]],sea:[[8,1],[10,11],[1,2],[17,10]]},actualSource:'standard'};}
 const api={clone,canonical,sha256,contentHash,fixed,cells,terrainObject,campaign,standard};root.GameMaps=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
