(function(root){'use strict';
 function create(env){
  const {ui,D,G,A,H,esc,viewer,knownBuildingAt,board,miniMap,drawer}=env,I=root.GameIcons;
  const icon=(name,label,action,reason='',tip='',cls='')=>I.button(name,label,{action,reason,tip,cls});
  const command=(name,label,cmd,reason='',tip='',cls='')=>I.button(name,label,{command:cmd,reason,tip,cls});
  const warehouse=b=>`<div class="facility-warehouse" data-tooltip="仓库最多3支，左侧队首先出库；部署格空出时自动部署。"><strong>${I.svg('army')} ${b.stock.length}/3</strong>${b.stock.map((stock,i)=>`<span class="warehouse-unit" data-tooltip="${esc(`${i+1} · ${D.byId[stock.type].type} · ${D.byId[stock.type].name}`)}">${root.GameAnime?.avatar(stock.type)||A.unitSvg(stock.type)}<span>${esc(D.byId[stock.type].name)}</span></span>`).join('')}</div>`;
  function context(){const s=ui.game,u=G.unit(s,ui.selected),c=ui.tile,b=c&&knownBuildingAt(c);return {s,u:u&&G.visible(s,viewer(),u)?u:null,b};}
  function eligible(b){const s=ui.game;return b&&b.owner===s.actor&&viewer()===s.actor&&G.visible(s,viewer(),G.building(s,b.id))&&G.player(s).controller==='local_human'&&!s.result&&!s.story?.combatLocked;}
  function blocked(){return ui.paused?'对局已暂停':ui.busy?'行动播放中':'';}
  function facility(b){const s=ui.game,d=D.buildingById[b.type],durable=G.hasBuildingHealth(b),active=G.buildingActive(b),current=G.visible(s,viewer(),G.building(s,b.id));
   return `<section class="panel facility-panel"><div class="facility-heading"><svg viewBox="-50 -50 100 100" aria-hidden="true">${A.buildingMarkup(b.type,G.player(s,b.owner)?.factionStyle,b.level)}</svg><div><h3>${d.name} · ${'ⅠⅡⅢ'[b.level-1]}</h3><small>${esc(G.player(s,b.owner)?.name||'中立')} · ${!current?'最后观测':b.state==='foundation'?'施工中':durable&&b.hp<=0?'已损毁':'运作中'}</small></div></div>${durable?`<p data-tooltip="同格驻军由设施分担25%伤害。所属方回合恢复最大生命值的${Math.round(G.buildingRecoveryRate(b)*1000)/10}%。">HP ${b.hp}/${b.maxHp}</p><div class="bar facility-health"><span style="width:${100*b.hp/b.maxHp}%"></span></div>`:'<p>收入据点</p>'}<div class="facility-income" data-tooltip="每个己方回合开始领取收入。">${I.svg('money')} ${active?d.money[b.level-1]||0:0} ${I.svg('energy')} ${active?d.energy[b.level-1]||0:0}</div>${eligible(b)&&d.group==='production'?configuration(b):''}</section>`;
  }
  function configuration(b){const s=ui.game,c=G.deploymentCell(s,b),order=b.order,p=G.player(s,b.owner);return `<div class="facility-config">${icon('deployment','设置自动部署格','set-deployment',blocked()||G.facilityReason(s,b),`当前部署格 ${c?c.q+','+c.r:'未设置'}。点击后在地图上选择本格或相邻高亮格。`)}${order?`<div class="facility-order">${order.kind==='unit'?root.GameAnime?.avatar(order.type)||'':I.svg('upgrade')}<span>${order.kind==='unit'?D.byId[order.type].type:'升级'} · ${Math.max(0,order.readyOwnTurn-p.ownTurnIndex)}</span>${command('cancel','取消订单',{kind:'cancel',buildingId:b.id},blocked()||G.facilityReason(s,b),'取消不退还资金。')}</div>`:''}</div>${warehouse(b)}`;}
  function production(b){if(!eligible(b)||D.buildingById[b.type].group!=='production')return '<p>选择己方生产设施。</p>';const s=ui.game;return `<div class="production-grid">${D.units.filter(d=>d.facility===b.type).map(d=>{const reason=blocked()||G.productionReason(s,b,d.id);return `<button type="button" class="production-card ${reason?'unavailable':''}" data-cmd="${esc(JSON.stringify({kind:'produce',buildingId:b.id,type:d.id}))}" aria-label="生产${esc(d.type)}，${d.cost}金钱，${d.buildTurns}回合" data-tooltip="${esc(reason||`${d.name} · ${d.skill}：${d.skillText}`)}" ${reason?'disabled':''}>${root.GameAnime?.avatar(d.id)||A.unitSvg(d.id)}<span><b>${d.type}</b><small>${'ⅠⅡⅢ'[d.tier-1]} · ${I.svg('money')}${d.cost} · ${I.svg('pause')}${d.buildTurns}</small></span>${reason?I.svg(d.tier>b.level?'shield':'pause'):I.svg('produce')}</button>`;}).join('')}</div>${configuration(b)}`;}
  function rail(){const {s,u,b}=context(),parts=[];
   if(u&&u.owner===s.actor&&viewer()===s.actor&&G.player(s).controller==='local_human'){const d=D.byId[u.type],skill=I.skills[d.skill];if(skill)parts.push(icon(skill,d.skill,'intent-skill',blocked()||G.canAct(s,u)||(G.player(s).ownTurnIndex<u.cooldownReady?'技能冷却中':''),d.skill+'：'+d.skillText,ui.intent==='skill'?'active':''));}
   if(eligible(b)){const d=D.buildingById[b.type];if(d.group==='production')parts.push(icon('produce','生产部队','drawer-production',blocked()||G.facilityReason(s,b),'点击头像型号即可生产。'));
    parts.push(command('upgrade','升级设施',{kind:'upgrade',buildingId:b.id},blocked()||G.upgradeReason(s,b),`升级费用 ${d.upgrades[b.level-1]||0} 金钱；下一己方回合完成。`));
    if(G.hasBuildingHealth(b)&&b.state==='complete'&&b.hp<=0){const cost=G.repairCost(b);parts.push(command('repair','重建设施',{kind:'repairBuilding',buildingId:b.id},blocked()||G.repairBuildingReason(s,b),`${cost.money}金钱 / ${cost.energy}能源；重建至50%生命。`));}
   }
   if(u||b||ui.tile)parts.push(icon('info','查看详情','drawer-details','','单位、设施与地形的详细资料。'));
   parts.push(icon('undo','撤销移动','undo-move',blocked()||ui.moveUndoReason,'撤销本回合连续移动；恢复行动点、能源、自动占领和出库。探明地形可保留；移动中发现此前不可见敌军后，本回合不可撤销（仍可读档重试）。攻击、生产、换回合或剧情交接后不可撤销。'));
   if(ui.intent||u||b)parts.push(icon('close',ui.intent?'取消技能或配置':'取消选择','clear','','取消选择，不消耗行动。'));
   return `<nav class="mobile-context-rail" aria-label="技能与设施操作">${parts.join('')}</nav>`;
  }
  function choices(){if(!ui.choices)return '';return `<div class="mobile-popup-backdrop" data-dismiss="choices"><section class="battle-drawer hud-panel" role="dialog" aria-modal="true" aria-label="选择技能目标"><div class="dock-title"><strong>选择技能目标</strong>${icon('close','关闭','choices-close')}</div><div class="drawer-content">${ui.choices.map(x=>{const target=G.unit(ui.game,x.command.targetId)||G.building(ui.game,x.command.targetId);return `<button class="skill-target-card" aria-label="${esc(x.label)}" data-cmd="${esc(JSON.stringify(x.command))}" data-tooltip="${esc(x.reason||x.label)}" ${x.reason?'disabled':''}>${D.byId[target?.type]?root.GameAnime?.avatar(target.type)||A.unitSvg(target.type):I.svg('build')}<span>${esc(x.label)}</span>${I.svg('skillRepair')}</button>`;}).join('')}</div></section></div>`;}
  function battle(){const s=ui.game,p=G.player(s),id=viewer(),vp=G.player(s,id),income=G.income(s,id),reason=blocked()||(p.controller!=='local_human'?'AI 行动中':'');
   return `<div class="battle-frame mobile-command-frame ${ui.drawer?'has-drawer':''} ${ui.touchMap?'has-touch-map':''} ${ui.paused?'is-paused':''} ${ui.busy?'is-animating':''}">${board()}<div class="battle-vignette"></div><header class="battle-top"><div class="mobile-economy"><span data-tooltip="每回合收入${income.money}金钱">${I.svg('money')}<b>${vp.resources.money}</b></span><span data-tooltip="每回合收入${income.energy}能源；步兵移动免耗能">${I.svg('energy')}<b>${vp.resources.energy}</b></span><small style="--seat-color:${p.color}" data-tooltip="第${s.round}轮 · ${esc(p.name)} · ${ui.paused?'暂停':p.controller==='ai'?'AI行动中':'玩家行动'}"><i></i>${s.round}</small></div><div class="top-tools">${icon(ui.paused?'play':'pause',ui.paused?'继续游戏':'暂停游戏','pause')}${icon('menu','指挥菜单','drawer-menu')}</div></header><nav class="mobile-navigation" aria-label="战场面板">${icon('army','部队调度','drawer-army')}${icon('build','建设设施','drawer-build',reason)}${icon('flag','战场目标','drawer-objectives')}${icon('log','行动记录','drawer-log')}${icon('help','操作帮助','drawer-touchHelp')}</nav>${rail()}${env.buildingHealth()}<section class="turn-dock mobile-turn-dock"><div class="turn-action">${icon('next','下一支可行动部队','next-unit',reason)}${icon('map',ui.touchMap?'收起小地图':'打开小地图','touch-map')}${command('end','结束回合',{kind:'end'},reason,'结束当前方回合。','primary end-turn')}</div>${ui.touchMap?`<div class="mobile-map-panel hud-panel">${miniMap()}<div class="camera-controls">${icon('zoomOut','缩小地图','zoom-out')}${icon('zoomIn','放大地图','zoom-in')}${icon('home','定位总部','focus-hq')}${icon('overview','查看全图','overview')}</div></div>`:''}</section>${ui.intent?`<div class="mobile-mode-chip" role="status">${I.svg(ui.intent==='skill'?I.skills[D.byId[G.unit(s,ui.selected)?.type]?.skill]||'sniper':ui.intent==='setDeployment'?'deployment':ui.intent==='construct'?'build':'flag')}<span>${ui.intent==='skill'?'点选技能目标':ui.intent==='setDeployment'?'点选部署格':ui.intent==='construct'?'点选建设格':'点选目标'}</span></div>`:''}${p.controller==='ai'?`<div class="mobile-activity" role="status" aria-label="AI正在行动"><span class="thinking-dot"></span></div>`:''}${drawer()}${choices()}</div>`;
  }
  return {battle,production,facility};
 }
 root.GameMobileBattle={create};if(typeof module!=='undefined')module.exports=root.GameMobileBattle;
})(typeof window!=='undefined'?window:globalThis);
