(function(root){'use strict';
 const M=root.GameMaps||(typeof require!=='undefined'&&require('./maps')),H=root.Hex||(typeof require!=='undefined'&&require('./grid')),C=root.GameContent||(typeof require!=='undefined'&&require('./content')),D=root.GameData||(typeof require!=='undefined'&&require('./data'));
 const params=C.free.randomGeneration,k=c=>H.key(c.q,c.r),at=(map,c)=>map.get(k(c)),coord=p=>({q:p[0],r:p[1]}),spread=a=>Math.max(...a)-Math.min(...a);
 function normalizeSeed(seed){let value=String(seed||'').trim().normalize('NFC');if(!value)value=`六域-${Date.now().toString(36)}`;if([...value].length>64)throw Error('种子最多 64 个 Unicode 字符');return value;}
 function fnv(text){let v=2166136261;for(const b of new TextEncoder().encode(text))v=Math.imul(v^b,16777619)>>>0;return v||1831565813;}
 function rng(state){return ()=>{state^=state<<13;state^=state>>>17;state^=state<<5;state>>>=0;return state/4294967296;};}
 function shuffle(list,random){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function groundCost(c){return !c||['ocean','ridge'].includes(c.terrain)?Infinity:['water','ruins','rubble'].includes(c.terrain)?2:1;}
 class Heap{constructor(){this.a=[];}push(x){const a=this.a;a.push(x);let i=a.length-1;while(i){const p=(i-1)>>1;if(this.compare(a[p],x)<=0)break;a[i]=a[p];i=p;}a[i]=x;}compare(a,b){return a.cost-b.cost||H.sort(a,b);}pop(){const a=this.a,x=a[0],v=a.pop();if(a.length){let i=0;while(i*2+1<a.length){let n=i*2+1;if(n+1<a.length&&this.compare(a[n+1],a[n])<0)n++;if(this.compare(v,a[n])<=0)break;a[i]=a[n];i=n;}a[i]=v;}return x;}get length(){return this.a.length;}}
 function distances(list,start,sea=false,removed=null){const map=new Map(list.map(c=>[k(c),c])),best=new Map(),heap=new Heap();if(!start)return best;const first={q:start.q,r:start.r,cost:0,path:[]};heap.push(first);best.set(k(start),first);while(heap.length){const u=heap.pop();if(best.get(k(u))!==u)continue;for(const n of H.neighbors(u)){if(k(n)===removed)continue;const c=at(map,n),step=sea?(c?.terrain==='ocean'?1:Infinity):groundCost(c);if(!Number.isFinite(step))continue;const next={...n,cost:u.cost+step,path:[...u.path,c]};if(!best.has(k(n))||next.cost<best.get(k(n)).cost){best.set(k(n),next);heap.push(next);}}}return best;}
 // Two-unit min-cost flow through split nodes: internal capacity 1, endpoints 2.
 function twoRoutes(list,start,end){const land=list.filter(c=>Number.isFinite(groundCost(c))),index=new Map(land.map((c,i)=>[k(c),i])),graph=Array.from({length:land.length*2},()=>[]),source=index.get(k(start))*2+1,sink=index.get(k(end))*2;if(!Number.isFinite(source)||!Number.isFinite(sink))return null;
  function add(a,b,capacity,cost){const x={to:b,cap:capacity,initial:capacity,cost,rev:graph[b].length},y={to:a,cap:0,initial:0,cost:-cost,rev:graph[a].length};graph[a].push(x);graph[b].push(y);}
  for(let i=0;i<land.length;i++){const c=land[i];add(i*2,i*2+1,k(c)===k(start)||k(c)===k(end)?2:1,0);for(const n of H.neighbors(c)){const j=index.get(k(n));if(j!==undefined)add(i*2+1,j*2,2,groundCost(land[j]));}}
  for(let f=0;f<2;f++){const dist=Array(graph.length).fill(Infinity),prev=[],inQ=[],queue=[source];dist[source]=0;inQ[source]=true;for(let qi=0;qi<queue.length;qi++){const u=queue[qi];inQ[u]=false;graph[u].forEach((e,i)=>{if(e.cap>0&&dist[e.to]>dist[u]+e.cost){dist[e.to]=dist[u]+e.cost;prev[e.to]=[u,i];if(!inQ[e.to]){inQ[e.to]=true;queue.push(e.to);}}});}if(!prev[sink])return null;let cur=sink;while(cur!==source){const [u,i]=prev[cur],e=graph[u][i];e.cap--;graph[cur][e.rev].cap++;cur=u;}}
  const protectedKeys=new Set([k(start),k(end)]);for(let i=0;i<graph.length;i++)for(const e of graph[i])if(e.initial>0&&e.cap<e.initial){protectedKeys.add(k(land[Math.floor(i/2)]));protectedKeys.add(k(land[Math.floor(e.to/2)]));}return protectedKeys;}
 // Impassable ridges use the cost of reaching a bordering cell plus one;
 // this measures which front they obstruct without making ridges traversable.
 function regionCounts(list,seats,types=['ridge','ruins','rubble','water']){const values=seats.map(()=>Object.fromEntries(types.map(t=>[t,0]))),front=seats.map(()=>0),costs=seats.map(s=>distances(list,coord(s.hq)));for(const c of list){if(!types.includes(c.terrain))continue;const ds=costs.map(m=>c.terrain==='ridge'?Math.min(...H.neighbors(c).map(n=>(m.get(k(n))?.cost??Infinity)+1)):m.get(k(c))?.cost??Infinity),min=Math.min(...ds),owners=ds.map((v,i)=>v===min?i:-1).filter(i=>i>=0);if(!Number.isFinite(min)||owners.length!==1)continue;const i=owners[0];if(min<=5)values[i][c.terrain]++;if(min>2&&min<=(costs[i].get('0,0')?.cost??0)&&['ridge','ruins'].includes(c.terrain))front[i]++;}return {values,front};}
 function validate(map,{random=false}={}){const errors=[],list=M.cells(map),grid=new Map(list.map(c=>[k(c),c])),add=(code,text,detail)=>errors.push({code,text,detail});const count=map.playerCount,R=map.radius;if(!C.free.sizePresets.find(p=>p.id===map.size)?.allowedPlayers.includes(count))add('players','规模与人数不匹配');if(grid.size!==list.length||list.length!==1+3*R*(R+1)||list.some(c=>H.distance(c,{q:0,r:0})>R))add('boundary','六边形边界缺格、重复或越界');const quantities=Object.fromEntries(Object.keys(D.terrain).map(t=>[t,map.terrain[t]?.length||0]));for(const [t,n] of Object.entries(quantities)){if(n<3)add('terrain','每种地形至少三格',t);if(random){const [lo,hi]=params.terrainRanges[t];if(n<Math.ceil(lo*list.length)||n>Math.floor(hi*list.length))add('ratios','地形比例超出范围',t);}}
  const units=new Set(map.initialUnits.map(k)),buildings=new Set(map.buildings.map(k));if(units.size!==6*count||map.initialUnits.length!==6*count||buildings.size!==12*count+1||map.buildings.length!==12*count+1)add('assets','建筑或单位数量/坐标错误');if(new Set(map.buildings.map(b=>b.type)).size!==9)add('assets','没有完整九类建筑');
  for(const b of map.buildings){const c=at(grid,b),valid=b.type==='energyplatform'?c?.terrain==='ocean':['plain','road','coast'].includes(c?.terrain);if(!valid||b.level!==1||b.hp!==D.buildingById[b.type].hp||b.order||b.stock?.length)add('legality','建筑地形、等级、生命或初始订单非法',b.id);if(['energyfield','energyplatform'].includes(b.type)&&!map.deposits[b.type==='energyfield'?'land':'sea'].some(p=>p[0]===b.q&&p[1]===b.r))add('deposit','能源建筑缺少对应能源点',b.id);}
  for(const u of map.initialUnits)if(!Number.isFinite(H.cost(u.type,at(grid,u)))||(u.hp??D.byId[u.type].hp)!==D.byId[u.type].hp)add('legality','单位出生地形或生命非法',u.id);
  const ocean=list.filter(c=>c.terrain==='ocean'),sea=distances(list,ocean[0],true);if(sea.size!==ocean.length)add('sea','海洋不是单一连通域');const central=[],expansions=[],perSeat=[];for(const s of map.seats){const hq=coord(s.hq),assets=map.buildings.filter(b=>b.owner===s.id),army=map.initialUnits.filter(u=>u.owner===s.id),ground=distances(list,hq);if(assets.length!==8||army.length!==6||!army.some(u=>u.id===s.hqGuardId&&u.type==='infantry'&&k(u)===k(hq)))add('assets','每席出生包或总部守军不完整',s.id);const gain=assets.reduce((n,b)=>{n.money+=D.buildingById[b.type].money[0];n.energy+=D.buildingById[b.type].energy[0];return n;},{money:0,energy:0});if(gain.money!==120||gain.energy!==14||s.initialMoney!==600||s.initialEnergy!==60)add('assets','初始资金与收入错误',s.id);
   if(map.buildings.some(b=>b.type!=='energyplatform'&&!ground.has(k(b))))add('land','总部无法到达全部陆地建筑',s.id);if(!twoRoutes(list,hq,{q:0,r:0}))add('routes','总部至中央不足两条独立路线',s.id);central.push(ground.get('0,0')?.cost??Infinity);
   const port=assets.find(b=>b.type==='port'),naval=H.neighbors(port).filter(c=>at(grid,c)?.terrain==='ocean');if(naval.length<3||naval.filter(c=>!units.has(k(c))).length<2)add('deploy','港口缺少三邻海格或两个空部署格',s.id);
   for(const type of ['barracks','factory','airfield']){const b=assets.find(x=>x.type===type);const available=[b,...H.neighbors(b)].filter(c=>Number.isFinite(groundCost(at(grid,c)))&&!units.has(k(c)));if(available.length<3)add('deploy','地面设施不足三个空部署格',b?.id);}
   for(const [which,point] of [['land',s.emptyLandDeposit],['sea',s.emptySeaDeposit]]){const p=coord(point),c=at(grid,p);if(buildings.has(k(p))||!map.deposits[which].some(x=>k(coord(x))===k(p))||(which==='land'?!['plain','road','coast'].includes(c?.terrain):c?.terrain!=='ocean')||!assets.some(b=>['hq','city'].includes(b.type)&&H.distance(b,p)<=2))add('deposit','空能源点类型、位置或建设来源错误',s.id);}
   const ship=army.find(u=>u.type==='aafrigate'),nav=distances(list,ship,true),values=s.expansionBuildingIds.map(id=>{const b=map.buildings.find(x=>x.id===id);return b?(b.type==='energyplatform'?nav:ground).get(k(b))?.cost??Infinity:Infinity;});expansions.push(values);perSeat.push({id:s.id,centerCost:central.at(-1),expansionCosts:values});for(let i=0;i<4;i++){const range=i===2?[4,6]:i===3?[2,4]:[3,5];if(values[i]<range[0]||values[i]>range[1])add('fairness','扩张点移动代价超出范围',{seat:s.id,index:i,cost:values[i]});}}
  for(let i=0;i<count;i++)for(let j=i+1;j<count;j++)if(H.distance(coord(map.seats[i].hq),coord(map.seats[j].hq))<params.protectedOriginalHqDistance[map.size])add('hq','总部距离不足');if(Math.max(...central)>params.centralGroundCostMax[map.size]||spread(central)>(count===5?2:1))add('fairness','中央移动预算不公平');for(let i=0;i<4;i++)if(spread(expansions.map(x=>x[i]))>1)add('fairness','同类扩张预算差大于一',i);if(spread(expansions.map(x=>x.reduce((a,b)=>a+b,0)))>2)add('fairness','总扩张预算差大于二');if(random){const cover=regionCounts(list,map.seats);for(const t of ['ridge','ruins','rubble','water'])if(spread(cover.values.map(x=>x[t]))>2)add('cover','近区同类掩体数量不公平',t);if(spread(cover.front)>2)add('cover','前线遮挡数量不公平');const combo=list.some(c=>['water','ruins','rubble'].includes(c.terrain)&&H.neighbors(c).filter(n=>['water','ruins','rubble'].includes(at(grid,n)?.terrain)).length>=2);if(!combo)add('cover','缺少连续三格地形组合');}return {ok:!errors.length,errors,terrainCounts:quantities,perSeat};}
 function orbits(list,count){const grid=new Set(list.map(k)),step=count===3?2:count===6?1:3,groups=[],used=new Set();for(const c of list){if(used.has(k(c)))continue;let p=c,group=[];for(let i=0;i<(count===5?1:6/step);i++){if(grid.has(k(p)))group.push(p);for(let n=0;n<(count===5?6:step);n++)p={q:-p.r,r:p.q+p.r};}group=group.filter((p,i,a)=>a.findIndex(x=>k(x)===k(p))===i).sort(H.sort);group.forEach(p=>used.add(k(p)));groups.push(group);}return groups.sort((a,b)=>H.sort(a[0],b[0]));}
 function skeleton(size,count){const map=M.fixed(size,count),list=M.cells(map),grid=new Map(list.map(c=>[k(c),c])),protectedKeys=new Set(),assets=[...map.buildings.filter(b=>map.seats.some(s=>s.id===b.owner)),...map.initialUnits],deploy=new Set();assets.forEach(c=>protectedKeys.add(k(c)));for(const s of map.seats){const hq=coord(s.hq);for(const c of list)if(H.distance(hq,c)<=2&&Number.isFinite(groundCost(c)))protectedKeys.add(k(c));for(const p of [s.emptyLandDeposit,s.emptySeaDeposit])protectedKeys.add(k(coord(p)));const routes=twoRoutes(list,hq,{q:0,r:0});if(!routes)throw Error('固定骨架缺少两条陆路');for(const id of routes)protectedKeys.add(id);for(const b of map.buildings.filter(b=>b.owner===s.id&&['barracks','factory','airfield'].includes(b.type)))for(const n of [b,...H.neighbors(b)])if(Number.isFinite(groundCost(at(grid,n))))deploy.add(k(n));const port=map.buildings.find(b=>b.owner===s.id&&b.type==='port');for(const n of H.neighbors(port).filter(n=>at(grid,n)?.terrain==='ocean')){protectedKeys.add(k(n));deploy.add(k(n));const nav=distances(list,n,true),outer=list.filter(c=>c.terrain==='ocean'&&H.distance(c,{q:0,r:0})>=map.radius-1).map(c=>nav.get(k(c))).filter(Boolean).sort((a,b)=>a.cost-b.cost||H.sort(a,b))[0];if(!outer)throw Error('固定骨架港口断航');outer.path.forEach(c=>protectedKeys.add(k(c)));}}
  for(const c of list)if(H.distance(c,{q:0,r:0})>=map.radius-1){if(c.terrain!=='ocean')throw Error('外环保护冲突');protectedKeys.add(k(c));}for(const id of deploy)protectedKeys.add(id);map.buildings=map.buildings.filter(b=>map.seats.some(s=>s.id===b.owner)||b.q===0&&b.r===0);for(const which of ['land','sea'])map.deposits[which]=map.deposits[which].filter(p=>map.buildings.some(b=>b.type===(which==='land'?'energyfield':'energyplatform')&&k(b)===k(coord(p)))||map.seats.some(s=>k(coord(which==='land'?s.emptyLandDeposit:s.emptySeaDeposit))===k(coord(p))));return {map,list,protectedKeys,deploy};}
 function candidate(base,landscape,random){const map=M.clone(base.map),list=M.clone(base.list),grid=new Map(list.map(c=>[k(c),c])),protect=base.protectedKeys,groups=orbits(list,map.playerCount);let noise=new Map();for(const group of groups){const value=group.some(c=>protect.has(k(c)))?128:Math.floor(random()*256);group.forEach(c=>noise.set(k(c),value));}for(let pass=0;pass<2;pass++){const next=new Map();for(const c of list){if(protect.has(k(c))){next.set(k(c),128);continue;}const vals=[c,...H.neighbors(c)].map(p=>noise.get(k(p))).filter(v=>v!==undefined);next.set(k(c),Math.floor(vals.reduce((a,b)=>a+b,0)/vals.length));}noise=next;}
  const threshold=params.noise.thresholds[landscape];for(const c of shuffle(list,random)){if(protect.has(k(c)))continue;if(noise.get(k(c))<threshold.expandOceanBelow&&H.neighbors(c).some(n=>at(grid,n)?.terrain==='ocean'))c.terrain='ocean';else if(c.terrain==='ocean'&&noise.get(k(c))>threshold.shrinkOceanAbove)c.terrain='plain';}
  for(const c of list)if(!protect.has(k(c))&&!['ocean','road'].includes(c.terrain))c.terrain='plain';let coastCount=list.filter(c=>c.terrain==='coast').length;for(const group of shuffle(groups,random)){if(coastCount>=Math.ceil(list.length*.08))break;if(group.some(p=>protect.has(k(p))||at(grid,p)?.terrain!=='plain'||!H.neighbors(p).some(n=>at(grid,n)?.terrain==='ocean')))continue;for(const p of group){at(grid,p).terrain='coast';coastCount++;}}
  const forbidden=new Set([...protect,...base.deploy,...map.buildings.map(k),...map.initialUnits.map(k),...map.deposits.land.map(p=>k(coord(p))),...map.deposits.sea.map(p=>k(coord(p)))]),usable=groups.filter(g=>g.every(p=>!forbidden.has(k(p))&&['plain','coast'].includes(at(grid,p)?.terrain)));
  // Random secondary roads stay on legal land; static movement costs remain one.
  let roadCount=list.filter(c=>c.terrain==='road').length;for(const group of shuffle(usable,random).slice(0,12)){if(roadCount+group.length>Math.floor(list.length*.14)||!group.some(p=>H.neighbors(p).some(n=>at(grid,n)?.terrain==='road'))||random()>.45)continue;for(const p of group){at(grid,p).terrain='road';forbidden.add(k(p));roadCount++;}}
  // Place a connected feature first, then finish symmetric terrain budgets.
  const pool=shuffle(usable,random);let combo=false;for(const group of pool){const a=at(grid,group[0]),ns=H.neighbors(a).map(n=>at(grid,n)).filter(c=>c&&!forbidden.has(k(c))&&['plain','coast'].includes(c.terrain));if(ns.length>=2){[a,ns[0],ns[1]].forEach((c,i)=>{c.terrain=['water','rubble','ruins'][i];forbidden.add(k(c));});combo=true;break;}}if(!combo)return null;
  for(const type of ['ridge','ruins','rubble','water']){const target=Math.max(3,Math.ceil(list.length*.015)),max=Math.floor(list.length*params.terrainRanges[type][1]);for(const g of shuffle(usable,random)){let n=list.filter(c=>c.terrain===type).length;if(n>=target)break;if(n+g.length>max||g.some(p=>forbidden.has(k(p))||!['plain','coast'].includes(at(grid,p)?.terrain)))continue;g.forEach(p=>{at(grid,p).terrain=type;forbidden.add(k(p));});}}
  // G05: common cost targets, stable seat order, no unused-seat resource packages.
  const claimed=new Set([...map.buildings.map(k),...map.initialUnits.map(k),...map.deposits.land.map(p=>k(coord(p))),...map.deposits.sea.map(p=>k(coord(p)))]),types=['city','market','energyfield','energyplatform'];for(let ti=0;ti<4;ti++){const type=types[ti],range=ti===2?[4,6]:ti===3?[2,4]:[3,5],target=range[0]+Math.floor(random()*(range[1]-range[0]+1));for(const seat of map.seats){const source=ti===3?map.initialUnits.find(u=>u.owner===seat.id&&u.type==='aafrigate'):coord(seat.hq),paths=distances(list,source,ti===3);let options=list.filter(c=>!claimed.has(k(c))&&(ti===3?c.terrain==='ocean':['plain','road','coast'].includes(c.terrain))&&!map.seats.some(s=>s.id!==seat.id&&H.distance(coord(s.hq),c)<=2)&&(paths.get(k(c))?.cost??Infinity)>=range[0]&&(paths.get(k(c))?.cost??Infinity)<=range[1]&&Math.abs((paths.get(k(c))?.cost??Infinity)-target)<=1);
    options=shuffle(options,random).sort((a,b)=>Math.abs(paths.get(k(a)).cost-target)-Math.abs(paths.get(k(b)).cost-target));const c=options[0];if(!c)return null;const b={id:seat.expansionBuildingIds[ti],type,owner:null,q:c.q,r:c.r,level:1,hp:D.buildingById[type].hp,maxHp:D.buildingById[type].hp,state:'complete'};map.buildings.push(b);claimed.add(k(c));if(ti>=2)map.deposits[ti===2?'land':'sea'].push([c.q,c.r]);}}
  map.terrain=M.terrainObject(list);return map;}
 function repair(map,problem,base,random){const list=M.cells(map),grid=new Map(list.map(c=>[k(c),c]));if(problem.code==='ratios'){const type=problem.detail,[lo,hi]=params.terrainRanges[type],n=map.terrain[type].length,total=list.length;const candidates=shuffle(list.filter(c=>!base.protectedKeys.has(k(c))&&!base.deploy.has(k(c))&&!map.buildings.some(b=>k(b)===k(c))&&!map.initialUnits.some(u=>k(u)===k(c))&&!map.deposits.land.some(p=>k(coord(p))===k(c))&&!map.deposits.sea.some(p=>k(coord(p))===k(c))),random);if(n<Math.ceil(lo*total)){const c=candidates.find(c=>c.terrain==='plain'&&(type!=='ocean'||H.neighbors(c).some(p=>at(grid,p)?.terrain==='ocean')));if(!c)return false;c.terrain=type;}else if(n>Math.floor(hi*total)){const c=candidates.find(c=>c.terrain===type);if(!c)return false;c.terrain='plain';}else return false;map.terrain=M.terrainObject(list);return true;}if(problem.code==='fairness'&&typeof problem.detail==='object'){const {seat,index}=problem.detail,s=map.seats.find(x=>x.id===seat),b=map.buildings.find(x=>x.id===s.expansionBuildingIds[index]),paths=distances(list,index===3?map.initialUnits.find(u=>u.owner===seat&&u.type==='aafrigate'):coord(s.hq),index===3),range=index===2?[4,6]:index===3?[2,4]:[3,5];const c=shuffle(list,random).find(c=>(index===3?c.terrain==='ocean':['plain','road','coast'].includes(c.terrain))&&!map.buildings.some(b=>k(b)===k(c))&&!map.initialUnits.some(u=>k(u)===k(c))&&(paths.get(k(c))?.cost??Infinity)>=range[0]&&(paths.get(k(c))?.cost??Infinity)<=range[1]);if(!c)return false;if(index>=2){const which=index===2?'land':'sea';map.deposits[which]=map.deposits[which].filter(p=>p[0]!==b.q||p[1]!==b.r);map.deposits[which].push([c.q,c.r]);}b.q=c.q;b.r=c.r;return true;}return false;}
 function generate({size='S',playerCount=2,landscapeId='balanced_coast',seed='',forceFailure=false}={}){seed=normalizeSeed(seed);if(!params.landscapeIds.includes(landscapeId))throw Error('未知地貌');const base=skeleton(size,playerCount),diagnostics=[];for(let attempt=0;attempt<40;attempt++){const random=rng(fnv(JSON.stringify(['0.7',size,playerCount,landscapeId,seed,attempt])));let map=candidate(base,landscapeId,random),report=map?validate(map,{random:true}):{ok:false,errors:[{code:'candidate',text:'缺少合法候选'}]},repairs=0;while(map&&!report.ok&&repairs<8&&!forceFailure){const priority=['legality','deposit','land','routes','sea','deploy','fairness','cover','ratios'];const issue=[...report.errors].sort((a,b)=>priority.indexOf(a.code)-priority.indexOf(b.code))[0];if(!repair(map,issue,base,random))break;repairs++;report=validate(map,{random:true});}diagnostics.push({attempt,repairs,errors:report.errors.map(e=>e.code)});if(map&&report.ok&&!forceFailure){map.actualSource='random';map.seed=seed;map.generatorVersion='0.7';map.landscapeId=landscapeId;map.acceptedAttempt=attempt;map.generationReport={attempts:attempt+1,repairs,checks:report,diagnostics};map.contentHash=M.contentHash(map);return map;}}
  const fallback=M.fixed(size,playerCount);Object.assign(fallback,{actualSource:'fixed_fallback',seed,generatorVersion:'0.7',landscapeId,acceptedAttempt:null,generationReport:{attempts:40,diagnostics},fallbackMessage:'随机生成未满足地图条件，使用固定备用地图'});return fallback;}
 const api={skeleton,candidate,normalizeSeed,fnv,rng,shuffle,distances,twoRoutes,regionCounts,validate,generate};root.RandomMap=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
