(function(root){'use strict';
 const M=root.GameMaps||(typeof require!=='undefined'&&require('./maps')),G=root.Game||(typeof require!=='undefined'&&require('./game')),D=root.GameData||(typeof require!=='undefined'&&require('./data'));
 const key='six-realms-v0.7';let memory={autos:[],manual:[],turnStarts:[],progress:null};
 function read(){try{const raw=root.localStorage?JSON.parse(root.localStorage.getItem(key)||'null')||memory:memory;if(!raw.entries)return raw;return {...raw,autos:raw.autos.map(id=>raw.entries[id]).filter(Boolean),manual:raw.manual.map(id=>raw.entries[id]).filter(Boolean),turnStarts:raw.turnStarts.map(id=>raw.entries[id]).filter(Boolean)};}catch{return memory;}}
 function write(data){memory=data;const entries=Object.fromEntries([...data.autos,...data.manual,...data.turnStarts].map(e=>[e.id,e]));const packed={...data,entries,autos:data.autos.map(e=>e.id),manual:data.manual.map(e=>e.id),turnStarts:data.turnStarts.map(e=>e.id)};if(root.localStorage)try{root.localStorage.setItem(key,JSON.stringify(packed));}catch(e){throw Error('浏览器存储空间不足，请导出存档并清理旧存档');}}
 function mergeProgress(old,p){if(!old)return M.clone(p);if(!p)return old;const completed={...old.completed,...p.completed};for(const [id,value] of Object.entries(completed)){value.tacticalMedal=!!(old.completed[id]?.tacticalMedal||p.completed[id]?.tacticalMedal);value.bestTactical=!!(old.completed[id]?.bestTactical||p.completed[id]?.bestTactical);value.optionalMedal=!!(old.completed[id]?.optionalMedal||p.completed[id]?.optionalMedal);}return {...old,...p,completed,unlocked:[...new Set([...old.unlocked,...p.unlocked])].sort(),clues:[...new Set([...old.clues,...p.clues])],seenScenes:[...new Set([...old.seenScenes,...p.seenScenes])],history:[...old.history,...p.history].filter((x,i,a)=>a.findIndex(y=>y.id===x.id&&y.chapter===x.chapter&&y.method===x.method)===i),activeMillis:Math.max(old.activeMillis,p.activeMillis),complete:old.complete||p.complete};}
 function migrate(input){const result=M.clone(input),legacyMap=JSON.stringify(input.map||{}).includes('oilfield')||JSON.stringify(input.map||{}).includes('oilrig');function walk(x){if(!x||typeof x!=='object')return;for(const [oldName,newName] of [['oil','energy'],['initialOil','initialEnergy'],['oilCap','energyCap'],['seaOil','seaEnergyPerStep']])if(Object.hasOwn(x,oldName)){const target=oldName==='oil'&&Object.hasOwn(x,'move')?'energyPerStep':newName;if(Object.hasOwn(x,target)&&M.canonical(x[target])!==M.canonical(x[oldName]))throw Error(`旧字段 ${oldName} 与 ${target} 数值冲突`);x[target]=x[oldName];delete x[oldName];}for(const k of Object.keys(x)){if(['type','typeId'].includes(k)&&['oilfield','oilrig'].includes(x[k]))x[k]=x[k]==='oilfield'?'energyfield':'energyplatform';if(x[k]&&typeof x[k]==='object')walk(x[k]);}}walk(result);if(legacyMap&&result.map?.contentHash){result.migration={sourceHash:result.map.contentHash,terminology:'energy-0.7'};result.map.contentHash=M.contentHash(result.map);}if(result.schemaVersion!=='game-0.7'||result.ruleVersion!=='0.7')throw Error('旧工作台 v0.4 没有完整回合与视野状态，无法直接作为 v0.7 对局恢复；请开始新对局');if(result.mode==='free'&&result.players.some(p=>['union','red'].includes(p.id))){const ids={union:'P1',red:'P2'};for(const p of result.players){p.id=ids[p.id]||p.id;p.teamId=ids[p.teamId]||p.teamId;}for(const e of [...result.units,...result.buildings])e.owner=ids[e.owner]||e.owner;result.actor=ids[result.actor]||result.actor;result.turnOrder=result.turnOrder.map(x=>ids[x]||x);result.pendingPlayers=result.pendingPlayers.map(x=>ids[x]||x);for(const field of ['vision','explored','knownBuildings','revealed'])result[field]=Object.fromEntries(Object.entries(result[field]).map(([k,v])=>[ids[k]||k,v]));}result.settings.difficulty=G.difficulty(result.settings.difficulty);if(result.balanceVersion===undefined){for(const u of result.units){const d=D.byId[u.type],ai=result.players.find(p=>p.id===u.owner)?.controller==='ai',level=result.settings.difficulty,scale=!result.aiDifficultyVersion||!ai?1:level==='easy'?.85:level==='hell'?1.2:1,expected=Math.round((D.balance.legacyAirHp[u.type]||d?.hp)*scale);if(!d||u.maxHp!==expected||!Number.isInteger(u.hp)||u.hp<1||u.hp>expected)throw Error('旧存档单位生命上限非法');if(!result.aiDifficultyVersion){u.hp=Math.max(1,Math.round(u.hp*d.hp/expected));u.maxHp=d.hp;}else G.tuneUnit(result,u);}result.balanceVersion=1;}if(!result.aiDifficultyVersion){for(const u of result.units){const d=D.byId[u.type];if(d&&(u.maxHp!==d.hp||!Number.isInteger(u.hp)||u.hp<1||u.hp>d.hp))throw Error('旧存档单位生命上限非法');if(d)G.tuneUnit(result,u);}result.aiDifficultyVersion=1;}if(result.facilityRulesVersion===undefined){for(const b of [...result.buildings,...Object.values(result.knownBuildings||{}).flatMap(records=>Object.values(records))])if(D.buildingById[b.type]&&!G.hasBuildingHealth(b)){b.hp=b.maxHp=null;}result.facilityRulesVersion=1;}return result;}
 function validate(s){
  if(s.schemaVersion!=='game-0.7'||s.ruleVersion!=='0.7'||!s.map||!Array.isArray(s.cells)||!Array.isArray(s.players)||!Array.isArray(s.units)||!Array.isArray(s.buildings)||!Array.isArray(s.turnOrder)||!Array.isArray(s.pendingPlayers))throw Error('存档格式不完整');
  if(s.balanceVersion!==undefined&&s.balanceVersion!==1)throw Error('平衡规则版本非法');
  if(s.facilityRulesVersion!==undefined&&s.facilityRulesVersion!==1)throw Error('设施规则版本非法');
  if(s.aiDifficultyVersion!==undefined&&s.aiDifficultyVersion!==1||!Object.hasOwn(G.difficultyProfiles,s.settings?.difficulty||'standard')&&!['training','challenge'].includes(s.settings?.difficulty))throw Error('难度配置非法');
  const ids=new Set(),spots=new Set(),owners=new Set(s.players.map(p=>p.id)),grid=new Map(),integer=(n,min,max=Number.MAX_SAFE_INTEGER)=>Number.isInteger(n)&&n>=min&&n<=max;
  if(owners.size!==s.players.length||s.players.length<2||s.players.length>6||!owners.has(s.actor)||!integer(s.round,1)||s.turnOrder.length!==owners.size||new Set(s.turnOrder).size!==owners.size||s.turnOrder.some(id=>!owners.has(id))||new Set(s.pendingPlayers).size!==s.pendingPlayers.length||s.pendingPlayers.some(id=>!owners.has(id)))throw Error('玩家或回合顺序非法');
  for(const c of s.cells){const point=`${c.q},${c.r}`;if(!Number.isInteger(c.q)||!Number.isInteger(c.r)||!D.terrain[c.terrain]||grid.has(point))throw Error('地图格子非法');grid.set(point,c);}
  const located=e=>Number.isInteger(e.q)&&Number.isInteger(e.r)&&grid.has(`${e.q},${e.r}`),reserve=id=>{if(typeof id!=='string'||!id||ids.has(id))throw Error('实例标识重复或非法');ids.add(id);};
  for(const p of s.players){if(!p.resources||!p.teamId||!integer(p.ownTurnIndex,0))throw Error('玩家状态不完整');for(const [k,max] of [['money',3000],['energy',300]])if(!integer(p.resources[k],0,max))throw Error('资源数值非法');for(const field of ['vision','explored','knownBuildings','revealed'])if(!s[field]||!s[field][p.id])throw Error('逐玩家视野状态不完整');}
  for(const u of s.units){const d=D.byId[u.type];if(!d||!located(u)||spots.has(`${u.q},${u.r}`)||!owners.has(u.owner)||!integer(u.hp,1,G.unitStats(s,u).hp)||u.maxHp!==G.unitStats(s,u).hp||!integer(u.ap,0,2)||!integer(u.counterRemaining,0,1)||!integer(u.spentMove,0)||!integer(u.cooldownReady,0)||!u.status)throw Error('单位数据重复或非法');reserve(u.id);spots.add(`${u.q},${u.r}`);}
  const bs=new Set();for(const b of s.buildings){const d=D.buildingById[b.type];if(!d||!located(b)||bs.has(`${b.q},${b.r}`)||b.owner&&!owners.has(b.owner)||!integer(b.level,1,d.maxLevel)||!['complete','foundation'].includes(b.state)||(G.hasBuildingHealth(b)?!integer(b.hp,0,b.maxHp)||b.maxHp!==(b.state==='foundation'?d.hp/2:d.hp):b.hp!==null||b.maxHp!==null)||!Array.isArray(b.stock)||b.stock.length>3)throw Error('建筑数据重复或非法');reserve(b.id);bs.add(`${b.q},${b.r}`);
   if(b.state==='foundation'&&!integer(b.readyOwnTurn,1))throw Error('建设进度非法');
   if(b.deployment!==undefined&&b.deployment!==null){const point=b.deployment;if(typeof point!=='object'||!Number.isInteger(point.q)||!Number.isInteger(point.r)||G.deploymentPositionReason(s,b,G.cell(s,point)))throw Error('设施部署格非法');}
   for(const stock of b.stock){if(!D.byId[stock.type]||D.byId[stock.type].facility!==b.type||stock.sourceId!==b.id)throw Error('库存来源或单位型号非法');reserve(stock.id);}
   if(b.order){if(!['unit','upgrade'].includes(b.order.kind)||!integer(b.order.readyOwnTurn,1)||b.order.kind==='unit'&&D.byId[b.order.type]?.facility!==b.type)throw Error('生产订单非法');reserve(b.order.id);}
  }
  for(const p of s.players)if(G.count(s,p.id)>24)throw Error('单位数量超出上限');
  if(s.map.contentHash&&M.contentHash(s.map)!==s.map.contentHash)throw Error('初始地图内容哈希不一致');return true;
 }
 function pack(s,label){validate(s);const snapshot=M.clone(s);delete snapshot.cells;return {id:`${Date.now()}-${s.revision}`,label,mode:s.mode,map:s.map.id,source:s.map.actualSource,seed:s.map.seed||'',team:s.settings.teams||'ffa',actor:s.actor,goal:s.settings.victoryMode,round:s.round,date:new Date().toISOString(),checksum:M.sha256(M.canonical(snapshot)),snapshot};}
 function save(s,{manual=false,label='自动保存',turnStart=false}={}){const d=read();if(s.story){s.story.progress=mergeProgress(d.progress,s.story.progress);d.progress=M.clone(s.story.progress);}const entry=pack(s,label);if(manual){d.manual.unshift(entry);d.manual=d.manual.slice(0,12);}else {d.autos.unshift(entry);d.autos=d.autos.slice(0,5);}if(turnStart){d.turnStarts.unshift(entry);d.turnStarts=d.turnStarts.slice(0,4);}write(d);return entry;}
 function restore(entry){if(!entry?.snapshot)throw Error('存档没有对局快照');if(entry.checksum!==M.sha256(M.canonical(entry.snapshot)))throw Error('存档校验失败，文件可能不完整');const s=migrate(entry.snapshot);s.cells=s.cells||M.cells(s.map);validate(s);G.vision(s);return s;}
 function importFile(text){const entry=JSON.parse(text),s=restore(entry);save(s,{manual:true,label:entry.label||'导入存档'});return s;}
 function exportFile(s){return JSON.stringify(pack(s,'导出存档'),null,2);}
 function progress(p){const d=read();if(p){d.progress=mergeProgress(d.progress,p);write(d);}return d.progress;}
 function remove(id){const d=read();d.manual=d.manual.filter(e=>e.id!==id);d.autos=d.autos.filter(e=>e.id!==id);d.turnStarts=d.turnStarts.filter(e=>e.id!==id);write(d);}
 const api={read,migrate,validate,pack,save,restore,importFile,exportFile,progress,remove};root.GameStorage=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
