(function(){'use strict';
 const D=GameData,H=Hex,M=GameMaps,G=Game,C=Campaign,S=GameStorage,R=RandomMap,A=GameArt,app=document.getElementById('app'),modal=document.getElementById('modal-root');
 const colors=['#63dbc2','#f18d79','#78baff','#d3a0f7','#efce71','#8cc679'];
 const ui={busy:false,drawer:null,choices:null,buildType:'city',sound:true,ambience:true,motionMode:'standard',volume:.45,view:'home',game:null,preview:null,selected:null,tile:null,intent:null,stockId:null,observer:null,camera:{x:0,y:0,width:900},paused:false,fastAI:true,instantText:true,branch:'all',system:'all',tier:'all',query:'',dialog:null,chainAssist:false};
 try{const preferences=JSON.parse(localStorage.getItem('six-realms-ui-v08')||'{}');ui.sound=preferences.sound!==false;ui.ambience=preferences.ambience!==false;ui.volume=Number.isFinite(preferences.volume)?Math.max(0,Math.min(1,preferences.volume)):.45;ui.fastAI=preferences.fastAI!==false;ui.motionMode=['standard','fast','reduced'].includes(preferences.motionMode)?preferences.motionMode:'standard';}catch{}
 const FX=GameFX;try{const p=JSON.parse(localStorage.getItem('six-realms-ui-v08')||'{}'),legacy=JSON.parse(localStorage.getItem('six-realms-fx-v0.8')||'{}');if(!Object.hasOwn(p,'sound')&&legacy.soundEnabled===false)ui.sound=false;if(!Object.hasOwn(p,'volume')&&Number.isFinite(legacy.volume))ui.volume=Math.max(0,Math.min(1,legacy.volume));if(!Object.hasOwn(p,'ambience')&&legacy.ambienceEnabled===false)ui.ambience=false;}catch{}FX.setSoundEnabled(ui.sound);FX.setVolume(ui.volume);FX.setAmbienceEnabled?.(ui.ambience);
 function savePreferences(){try{localStorage.setItem('six-realms-ui-v08',JSON.stringify({sound:ui.sound,ambience:ui.ambience,volume:ui.volume,fastAI:ui.fastAI,motionMode:ui.motionMode}));}catch{}}
 const settings={size:'S',source:'fixed',playerCount:2,seed:'',landscapeId:'balanced_coast',victoryMode:'capture_hq',teams:'ffa',fog:true,difficulty:'standard',controllers:['local_human','ai','ai','ai','ai','ai'],names:['指挥官 1','指挥官 2','指挥官 3','指挥官 4','指挥官 5','指挥官 6']};
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),btn=(text,action,cls='',disabled='',tip='')=>`<button ${disabled?'disabled':''} class="${cls}" data-action="${action}" ${disabled||tip?`data-tooltip="${esc(disabled||tip)}"`:''}>${text}</button>`;
 function commandButton(text,command,reason='',cls='',tip=''){return `<button class="${cls}" data-cmd="${esc(JSON.stringify(command))}" ${reason?'disabled':''} ${reason||tip?`data-tooltip="${esc(reason||tip)}"`:''}>${text}</button>`;}
 const opt=(value,label,current)=>`<option value="${value}" ${value===String(current)?'selected':''}>${label}</option>`,goalName=v=>v==='capture_hq'?'占领原始总部':'接管全部登记建筑',sourceName=v=>({fixed:'固定地图',random:'随机地图',fixed_fallback:'固定备用地图',campaign:'剧情地图',standard:'标准战场',sandbox:'规则测试场'}[v]||v);
 function difficultyOptions(current){return (GameAI.difficulties||[{id:'easy',name:'简单'},{id:'standard',name:'标准'},{id:'hard',name:'困难'},{id:'hell',name:'地狱'}]).map(d=>opt(d.id,d.name,current)).join('');}
 function difficultyName(value){return ({easy:'简单',training:'简单',standard:'标准',hard:'困难',challenge:'困难',hell:'地狱'})[value]||'标准';}
 function difficultyGuide(){return `<details class="difficulty-guide"><summary>四档人机难度说明</summary><div>${GameAI.difficulties.map(d=>`<article><strong>${esc(d.name)}</strong><p>${esc(d.description)}</p></article>`).join('')}</div><small>难度影响 AI 控制方；困难与地狱都遵守自身视野和行动规则。</small></details>`;}
 function toast(message){const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3800);}
 function save(options={}){try{return S.save(ui.game,options);}catch(e){toast(e.message);}}
 function navigate(view){B.clearTouch?.();FX.cancel();B.releaseKeys();ui.busy=false;ui.drawer=null;ui.choices=null;if(ui.game&&ui.view==='game')save({label:'离开战场'});ui.view=view;ui.dialog=null;modal.innerHTML='';location.hash=view;render();}
 function header(title,text,actions=''){return `<div class="page-head"><div><div class="eyebrow">SIX REALMS / FIELD COMMAND</div><h2>${title}</h2><p>${text}</p></div><div class="actions">${actions}</div></div>`;}
 function home(){const stored=S.read(),latest=stored.autos[0];return `<section class="hero"><div><div class="eyebrow">澄海 · 晨潮协作联队</div><h1>把黎明，<br>送回六域。</h1><p>指挥具有自主意识的机装少女，重联能源节点，打开雾海航路。以陆海空协作，为六域留住共同的晨光。</p><div class="actions">${btn('进入剧情战役 →','campaign','primary')}${btn('自由战役','free')}${btn('视听设置','audio-settings')}${ui.game?btn('返回当前对局','resume'):latest?btn('继续最近存档','latest'):''}</div></div><span class="coordinates">HEX / ENERGY / COMBINED ARMS</span></section><div class="cards"><article class="card"><div class="number">01 / STORY CAMPAIGN</div><h2>把黎明送回六域</h2><p>七个地区，七份记录。从岚岸熄灭的灯火到潮门中央枢纽，保护维修通路，让最低供给重新连接每一个自治区。</p><div class="actions">${btn('查看七章任务','campaign')}</div><div class="meta"><span>7 章 · 23 段对白</span><span>独立关卡 · 可随时存档</span></div></article><article class="card"><div class="number">02 / OPEN CAMPAIGN</div><h2>六域演习</h2><p>自由建设与发展全部 38 种单位。在固定或随机地图上，与 2—6 方指挥官争夺指挥网络。</p><div class="actions">${btn('配置演习','free')}</div><div class="meta"><span>3 种规模 · 9 套固定布局</span><span>本地轮流 / 四档 AI</span></div></article></div>`;}
 function free(){const size=GameContent.free.sizePresets.find(p=>p.id===settings.size),count=settings.playerCount;const teamOptions=[['ffa','各自为战'],...(count===4?[['2v2','2 对 2']]:count===6?[['3v3','3 对 3'],['2v2v2','2 对 2 对 2']]:[])];return header('配置六域演习','从初始据点到完整三军作战。每方 600 金钱 / 60 能源，首次收入后人类为 720 / 74；地狱人机资源有额外加成。')+`<section class="panel"><div class="form-grid"><label>地图规模<select data-setting="size">${GameContent.free.sizePresets.map(p=>opt(p.id,`${p.name} · ${p.cells} 格`,settings.size)).join('')}</select></label><label>地图来源<select data-setting="source">${opt('fixed','固定布局',settings.source)}${opt('random','随机生成',settings.source)}${opt('standard','标准战场 · 247 格',settings.source)}</select></label><label>参与方<select data-setting="playerCount">${(settings.source==='standard'?[2]:size.allowedPlayers).map(n=>opt(n,`${n} 方`,count)).join('')}</select></label><label>地貌<select data-setting="landscapeId" ${settings.source!=='random'?'disabled':''}>${[['balanced_coast','均衡沿岸'],['bay_corridors','海湾走廊'],['island_bridges','群岛桥网']].map(([v,n])=>opt(v,n,settings.landscapeId)).join('')}</select></label><label>随机种子<input data-setting="seed" value="${esc(settings.seed)}" placeholder="留空自动生成 · 1—64 字符" ${settings.source!=='random'?'disabled':''}></label><label>胜利目标<select data-setting="victoryMode">${opt('capture_hq','占领总部 · 消灭其原始席位',settings.victoryMode)}${opt('own_all_registered_buildings','接管全部建筑 · 含新建与废墟',settings.victoryMode)}</select></label><label>阵营关系<select data-setting="teams">${teamOptions.map(([v,n])=>opt(v,n,settings.teams)).join('')}</select></label><label>人机难度<select data-setting="difficulty">${difficultyOptions(settings.difficulty)}</select></label><label>战争迷雾<select data-setting="fog">${opt('true','开启 · 仅当前视野可攻击',settings.fog)}${opt('false','关闭 · 全图可见',settings.fog)}</select></label></div>${difficultyGuide()}<h3>指挥官与控制者</h3><div class="seats">${Array.from({length:count},(_,i)=>`<div class="seat" style="--seat-color:${colors[i]}"><strong>P${i+1} · ${G.teams(count,settings.teams).team[i]}</strong><input aria-label="P${i+1} 名称" maxlength="24" data-name="${i}" value="${esc(settings.names[i])}"><select aria-label="P${i+1} 控制者" data-controller="${i}">${opt('local_human','本地人类玩家',settings.controllers[i])}${opt('ai','AI 指挥官',settings.controllers[i])}</select></div>`).join('')}</div><div class="actions">${btn('生成 / 更新预览','preview','primary')}${btn('返回大厅','home')}</div></section>${ui.preview?previewPanel():''}`;}
 function xy(c){return {x:Math.sqrt(3)*44*(c.q+c.r/2),y:66*c.r};}
 let lastSceneUpdate=-Infinity;
 function updateSoundScene(force=false){
  if(!FX.setScene)return;const audioPlace=ui.view!=='game'?'menu':ui.dialog||ui.game?.story?.queue.length?'briefing':'battle';window.GameAudio?.setScene({active:!document.hidden&&!ui.paused&&!ui.game?.handoffRequired,place:audioPlace,chapter:ui.game?.mission?.id,result:ui.view==='game'&&ui.game?.result?(!ui.game.result.winner?'draw':ui.game.result.winningPlayers?.includes(viewer())?'win':'loss'):null});
  const s=ui.game,active=ui.view==='game'&&s&&!document.hidden&&!ui.paused&&!ui.dialog&&!s.handoffRequired&&!s.result&&!s.story?.queue.length;
  if(!active){FX.setScene({terrain:'plain',active:false});return;}
  const now=performance.now();if(!force&&now-lastSceneUpdate<700)return;lastSceneUpdate=now;
  let terrain='plain',distance=Infinity;const id=viewer();
  for(const c of s.cells){if(!G.visible(s,id,c))continue;const p=xy(c),next=(p.x-ui.camera.x)**2+(p.y-ui.camera.y)**2;if(next<distance){distance=next;terrain=c.terrain;}}
  FX.setScene({terrain,profile:s.mission?.id==='C05'?'crystal':undefined,active:true});
 }
 function bounds(cells){const points=cells.map(xy),xs=points.map(p=>p.x),ys=points.map(p=>p.y);return {x:Math.min(...xs)-50,y:Math.min(...ys)-50,w:Math.max(...xs)-Math.min(...xs)+100,h:Math.max(...ys)-Math.min(...ys)+100};}
 const B=GameBattleUI.create({ui,D,H,G,A,esc,btn,commandButton,xy,bounds,viewer,knownBuildingAt,unitPanel,buildingPanel,exercisePanel,savesPage,render,act,toast,action,home,resultPanel,onCameraChange:updateSoundScene});
 function publicMap(map){const cells=M.cells(map),b=bounds(cells),styles=Object.fromEntries(map.seats.map((s,i)=>[s.id,colors[i]]));return `<svg class="preview-map" role="img" aria-label="初始地图预览" viewBox="${b.x} ${b.y} ${b.w} ${b.h}">${cells.map(c=>{const p=xy(c),build=map.buildings.find(x=>x.q===c.q&&x.r===c.r),unit=map.initialUnits.find(x=>x.q===c.q&&x.r===c.r);return `<g transform="translate(${p.x} ${p.y})">${A.terrainMarkupContext?A.terrainMarkupContext(c,cells):A.terrainMarkup(c.terrain)}${build?`<g transform="scale(.65)">${A.buildingMarkup(build.type,build.owner==='P2'||build.owner==='red'?'red':'union',1)}</g><circle cy="-25" r="8" fill="${styles[build.owner]||'#e3c386'}"/>`:''}${unit?`<circle cy="14" r="5" fill="${styles[unit.owner]||'#6edbbd'}" stroke="#fff"/>`:''}</g>`;}).join('')}</svg>`;}
 function previewPanel(){const m=ui.preview;const turn=G.teams(settings.playerCount,settings.teams).order,index=ui.previewStart,order=[...turn.slice(index),...turn.slice(0,index)];return `<section class="panel" style="margin-top:20px"><div class="preview-grid"><div>${publicMap(m)}<p class="note">预览公开初始地形、建筑与部队。对局开始后按当前视野显示敌军。</p></div><div><div class="eyebrow">MAP BRIEFING</div><h2>${m.id} · ${sourceName(m.actualSource)}</h2>${m.fallbackMessage?`<p class="warning">${m.fallbackMessage}</p>`:''}<div class="info-list"><div><span>格数 / 参与方</span><strong>${M.cells(m).length} / ${m.playerCount}</strong></div><div><span>初始建筑 / 单位</span><strong>${m.buildings.length} / ${m.initialUnits.length}</strong></div><div><span>胜利条件</span><strong>${goalName(settings.victoryMode)}</strong></div><div><span>固定轮换顺序</span><strong>${order.join(' → ')}</strong></div></div>${m.seed?`<p class="note">种子：${esc(m.seed)}<br>生成器 ${m.generatorVersion} · ${m.acceptedAttempt===null?'40 次候选后回退':`候选 ${m.acceptedAttempt??0}`}</p>`:''}<p class="hash">SHA-256 ${m.contentHash||M.contentHash(m)}</p><div class="actions">${btn('开始演习 →','start-free','primary')}${btn('复制种子','copy-seed','small',!m.seed?'固定地图没有种子':'')}</div></div></div></section>`;}
 function campaignPage(){const progress=S.progress()||C.newProgress();return header('把黎明送回六域','七份记录逐步构成完整主线。关卡之间保留线索与完成记录，部队与资源重新配置。')+`<section class="panel" style="margin-bottom:20px"><div class="form-grid"><label>本次任务胜利目标<select id="campaign-goal">${opt('capture_hq','接管敌方原始总部','capture_hq')}${opt('own_all_registered_buildings','接管全部建筑','capture_hq')}</select></label><label>敌军人机难度<select id="campaign-difficulty">${difficultyOptions(settings.difficulty)}</select></label><label><span>字幕</span><span><input type="checkbox" id="instant-text" ${ui.instantText?'checked':''}> 即时显示完整文本</span></label><label><span>AI 动画</span><span><input type="checkbox" id="fast-ai" ${ui.fastAI?'checked':''}> 快速执行</span></label></div>${difficultyGuide()}<h3>已取得的记录 · ${progress.clues.length} / 7</h3><div class="clues">${progress.clues.map(c=>`<span class="tag">${esc(GameContent.clueNames?.[c]||c)}</span>`).join('')||'<small>完成首章后登记第一份线索</small>'}</div>${progress.complete?'<p class="notice">主线已完成。所有地区均可重新进入。</p>':''}${btn('剧情回顾与字幕历史','history','small')}${progress.activeMillis>=150*60000?btn('协同接管后续任务','assist-chain','small'):''}</section><div class="chapters">${GameContent.campaign.missions.map((m,i)=>{const unlocked=progress.unlocked.includes(m.id),done=progress.completed[m.id];return `<article class="chapter ${!unlocked?'locked':''}"><span class="chapter-deco">⬡</span><div class="chapter-no">${m.id} / ${m.region}</div><h3>${esc(m.title)}</h3><p>${esc(m.lesson)}</p><div class="actions"><button class="${unlocked?'primary':''}" data-chapter="${m.id}" ${!unlocked?'disabled':''}>${done?'重新进入':unlocked?'开始任务':'待前章交接'}</button></div>${done?`<p class="note">${done.method==='assisted'?'协同完成':'战术胜利'} · ${done.report.optional?'可选目标达成':'主线记录已取得'}</p>`:''}</article>`;}).join('')}</div>`;}
 function viewer(){const s=ui.game,p=G.player(s);return p.controller==='local_human'&&!p.eliminated?p.id:ui.observer||s.players.find(p=>p.controller==='local_human')?.id||s.actor;}
 function knownBuildingAt(c){const s=ui.game,id=viewer();const b=s.buildings.find(b=>b.q===c.q&&b.r===c.r);return b&&G.visible(s,id,b)?b:Object.values(s.knownBuildings[id]).find(b=>b.q===c.q&&b.r===c.r);}
 function board(){return B.board();}
 function unitPanel(u){const s=ui.game,d=G.unitStats(s,u),p=G.player(s,u.owner),current=u.owner===s.actor&&p.controller==='local_human'&&!s.result,reason=G.canAct(s,u);return `<section class="panel"><div class="selected-header">${A.unitSvg(u.type,p.factionStyle,'',H.domain(u,G.cell(s,u)))}<div><small>${p.name} · ${D.states[H.domain(u,G.cell(s,u))]}</small><h3>${d.type} / ${d.name}</h3><span class="tag">${d.specialRole?'特殊单位':`${d.tier} 级型号`} · 可占领</span></div></div><div class="bar"><span style="width:${100*u.hp/u.maxHp}%"></span></div><div class="stat-grid"><div><small>生命 / 装甲</small>${u.hp}/${u.maxHp} · ${d.armor}</div><div><small>行动 / 反击</small>${u.ap} / ${u.counterRemaining}</div><div><small>射程</small>${d.minRange}—${d.maxRange}</div><div><small>移动已用</small>${u.spentMove}/${Math.max(1,d.move-(u.movePenalty||0))}${u.roadEligible&&d.branch!=='air'?'+1':''}</div><div><small>每格能耗</small>${d.energyPerStep}${d.seaEnergyPerStep?'/海'+d.seaEnergyPerStep:''}</div><div><small>基础伤害</small>${d.damage}</div></div><p class="note">${d.skill}：${d.skillText}<br>技能冷却：${p.ownTurnIndex<u.cooldownReady?`至所属方第 ${u.cooldownReady} 回合`:`已就绪`}</p>${u.status.entrench||u.status.anchor||u.status.scan?`<p class="note">当前强化在所属方第 ${p.ownTurnIndex+1} 回合开始到期。</p>`:""}${u.status.shock?`<p class="note">震荡：所属方第 ${u.status.shock.turn} 回合移动预算 −1。</p>`:""}${d.dedicatedAA?`<p class="notice">反击 150% · 剩余 ${u.counterRemaining}/1</p>`:u.type==='engineer'?`<p class="notice">修复 40 HP · 本回合剩余 ${u.repairUsed?0:1}/1</p>`:''}${u.status.jam?`<p class="notice">干扰：所属方第 ${u.status.jam.turn} 回合 1 AP；第 ${u.status.jam.protectedUntil} 回合开始解除保护。</p>`:''}${u.status.anchor?'<p class="notice">锚定：装甲 +20，不能移动</p>':''}${current?`<div class="actions">${btn('移动','intent-move',ui.intent==='move'?'primary':'',reason||u.status.anchor&&'锚定中')}${btn('攻击','intent-attack',ui.intent==='attack'?'primary':'',reason)}${btn('占领','intent-capture',ui.intent==='capture'?'primary':'',reason)}${!['基础作战','驻守','伏击','防空反击'].includes(d.skill)?btn(d.skill,'intent-skill',ui.intent==='skill'?'primary':'',reason||G.player(s).ownTurnIndex<u.cooldownReady&&`冷却至己方回合 ${u.cooldownReady}`):''}</div>`:''}</section>`;}
 function buildingPanel(b){
  const s=ui.game,current=G.visible(s,viewer(),G.building(s,b.id)),d=D.buildingById[b.type],durable=G.hasBuildingHealth(b),active=G.buildingActive(b),mine=current&&b.owner===s.actor&&G.player(s).controller==='local_human'&&!s.result&&!s.story?.combatLocked;
  const state=b.state==='foundation'?'施工中':durable&&b.hp<=0?'已损毁':'运作中',owner=esc(G.player(s,b.owner)?.name||'中立'),recovery=Math.round(G.buildingRecoveryRate(b)*1000)/10;
  let content=`<section class="panel facility-panel"><div class="facility-heading"><svg viewBox="-50 -50 100 100" aria-hidden="true">${A.buildingMarkup(b.type,G.player(s,b.owner)?.factionStyle,b.level)}</svg><div><h3>${d.name} · ${b.level}级</h3><small>${owner} · ${state}${current?'':' · 最后观测'}</small></div></div><div class="facility-metrics"><span data-tooltip="${esc(durable?`总部和生产设施为同格友军分担25%的伤害，最多分担到自身剩余HP。所属方回合开始恢复最大HP的${recovery}%；废墟不会自行恢复。`:'收入据点没有HP，不提供庇护，只能通过进入本格占领。')}">${durable?`HP <b>${b.hp}/${b.maxHp}</b>`:'收入据点'}</span><span data-tooltip="${esc('仅完工且运作中的建筑提供收入，收入在所属方回合开始结算。')}">¤ <b>${active?d.money[b.level-1]||0:0}</b>　⚡ <b>${active?d.energy[b.level-1]||0:0}</b><small> / 回合</small></span></div>${durable?`<div class="bar facility-health"><span style="width:${100*b.hp/b.maxHp}%"></span></div>`:''}`;
  if(mine){
   content+='<div class="facility-actions">';
   const upgradeErr=G.upgradeReason(s,b);
   content+=commandButton(`升级${b.level<d.maxLevel?' ¤'+d.upgrades[b.level-1]:''}`,{kind:'upgrade',buildingId:b.id},upgradeErr,'',upgradeErr||'下一所属方回合完成升级，保留现有低级型号。升级与生产共用订单槽。');
   if(durable&&b.state==='complete'&&b.hp<=0){const cost=G.repairCost(b);content+=commandButton(`重建 ¤${cost.money} ⚡${cost.energy}`,{kind:'repairBuilding',buildingId:b.id},G.repairBuildingReason(s,b),'primary','消耗金钱与能源，立即恢复至最大HP的50%。后续HP依靠每回合自动恢复，保留设施等级，旧订单和库存不会返还。');}
   if(d.group==='production'){
    const deployment=G.deploymentCell(s,b),occupant=deployment&&G.occupied(s,deployment),occupied=occupant&&G.visible(s,viewer(),occupant),tip=`当前部署格 ${deployment?`(${deployment.q}, ${deployment.r})`:'未设置'}${occupied?'，已有部队':''}。点击按钮后选择本格或兼容邻格；完工单位自动部署，部署格被占用时进入最多三支的先进先出仓库。`;
    content+=btn('设置自动部署格','set-deployment','',G.facilityReason(s,b),tip);
   }
   content+='</div>';
   if(b.order){const ready=b.order.kind==='unit'&&b.order.readyOwnTurn<=G.player(s,b.owner).ownTurnIndex;content+=`<div class="facility-order" data-tooltip="${esc('生产按所属方回合推进，仓库满时完工订单等待。取消订单不会退还资金。')}"><span>${b.order.kind==='unit'?D.byId[b.order.type].type:'设施升级'} · ${ready?'等待出库':`剩余 ${Math.max(0,b.order.readyOwnTurn-G.player(s,b.owner).ownTurnIndex)} 回合`}</span>${commandButton('取消',{kind:'cancel',buildingId:b.id},G.facilityReason(s,b),'small','取消当前订单，不退还金钱。')}</div>`;}
   if(d.group==='production'){
    const models=D.units.filter(u=>u.facility===b.type),first=models.find(u=>!G.productionReason(s,b,u.id))||models[0];
    content+=`<label class="facility-model-select" data-tooltip="${esc('高级设施可以继续生产低级单位。选择型号查看头像和成本；不满足等级、资源或授权时无法下单。')}">生产型号<select id="production-type">${models.map(u=>`<option value="${u.id}" ${u.id===first.id?'selected':''}>${u.tier>b.level?'🔒 ':''}${u.specialRole?'★ ':''}${u.type} · ${u.tier}级 · ¤${u.cost}</option>`).join('')}</select></label><div id="production-preview">${productionView(first.id)}</div>${btn('生产','produce','primary',G.productionReason(s,b,first.id),'提交一笔生产订单。部队、订单和库存合计上限24；每设施仓库最多三支。')}`;
    content+=`<div class="facility-warehouse" data-tooltip="仓库按生产顺序等待，左边第一支先部署。部署格空出后自动出库；每次设施最多部署一支，最多暂存三支。"><strong>仓库 ${b.stock.length}/3</strong>${b.stock.map((stock,i)=>`<span class="warehouse-unit" data-tooltip="${esc(`${i+1}. ${D.byId[stock.type].type} · ${D.byId[stock.type].name}；${i===0?'下一支自动部署':'等待队首出库'}`)}">${window.GameAnime?.avatar(stock.type)||A.unitSvg(stock.type)}<span>${esc(D.byId[stock.type].name)}</span></span>`).join('')||'<small>空</small>'}</div>`;
   }
  }
  return content+'</section>';
 }

 function exercisePanel(p){const records=[['move','移动'],['capture','占领'],['production','生产与部署'],['construction','新建'],['repair','工程修复'],['upgrade','升级'],['seaCapture','海上夺点'],['scan','空军侦察'],['aaCounter','专职防空反击'],['tier3','Ⅲ级生产']];return `<details style="margin-top:12px"><summary>演习记录 · ${records.filter(([k])=>k==='production'?p.exercise.production&&p.exercise.deployment:p.exercise[k]).length}/10</summary><div class="exercise">${records.map(([k,n])=>`<span class="${k==='production'?p.exercise.production&&p.exercise.deployment?'done':'':p.exercise[k]?'done':''}">${k==='production'?p.exercise.production&&p.exercise.deployment?'✓':'○':p.exercise[k]?'✓':'○'} ${n}</span>`).join('')}</div></details>`;}
 function battle(){return B.battle();}
 function resultPanel(){const s=ui.game,report=s.story?.report,winner=s.result?.winner,trigger=G.building(s,s.result?.triggerBuildingId),title=report?.method==='assisted'?'协同交接完成':winner?'队伍 '+winner+' 获胜':'对局结束';return `<section class="result"><div class="eyebrow">AFTER ACTION REPORT</div><h2>${title}</h2><p>${esc(report?.brief||s.result?.reason||'任务交接完成')}${report?.damagedHQ?'<br>'+report.damagedHQ:''}</p>${trigger?`<p class="note">触发建筑：${esc(trigger.storyLabel||D.buildingById[trigger.type].name)} · ${trigger.id} · (${trigger.q},${trigger.r})</p>`:''}${s.result?.winningPlayers?.length?`<p class="note">获胜成员：${s.result.winningPlayers.map(id=>esc(G.player(s,id).name)).join('、')}</p>`:''}<p>${s.map.id} · ${sourceName(s.map.actualSource)} · ${difficultyName(G.difficulty(s))}难度 · ${s.round} 轮 · 活跃 ${Math.floor(s.activeMillis/60000)} 分钟${s.map.seed?' · 种子 '+esc(s.map.seed):''}</p>${report?`<div class="clues" style="justify-content:center"><span class="tag">记录 ${esc(GameContent.clueNames?.[report.clue]||report.clue)}</span><span class="tag">${report.method==='assisted'?'现场目标已记录 · 不授纪念章':report.optional?'可选目标已达成':'主线完整交接'}</span><span class="tag">${report.method==='tactical'?'战术完成':'协同完成 · 无战术勋章'}</span></div>`:''}<table><thead><tr><th>指挥官</th><th>生产</th><th>占领</th><th>新建</th><th>修复</th><th>能耗</th></tr></thead><tbody>${s.players.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.stats.produced}</td><td>${p.stats.captures}</td><td>${p.stats.constructed}</td><td>${p.stats.repaired}</td><td>${p.stats.energy}</td></tr>`).join('')}</tbody></table><div class="actions">${s.mission?.nextMission&&s.story?.progress.unlocked.includes(s.mission.nextMission)?`<button data-chapter="${s.mission.nextMission}" class="primary">进入下一章 →</button>`:''}${s.mission?btn('返回章节','campaign'):btn('新演习','free')}${s.mission?btn('重试本章','retry'):''}${btn('存档','saves')}${btn('返回大厅','home')}</div></section>`;}
 function unitCard(u){return `<article class="unit-card" role="button" tabindex="0" data-unit-card="${u.id}"><div class="card-meta"><span>${u.code}</span><span>${u.specialRole?'SPECIAL':'TIER '+u.tier}</span></div>${window.GameAnime?`<img class="character-card" src="assets/units/portraits/${u.id}.png" loading="lazy" decoding="async" alt="${u.name} 机装少女">`:A.unitSvg(u.id)}<h3>${u.type} · ${u.name}</h3><div class="card-meta"><span>¤${u.cost} / ⚡${u.energyPerStep}</span><span>${D.buildingById[u.facility].name} ${u.tier}级</span></div><p class="note">${u.role}</p></article>`;}
 function productionView(id){const d=D.byId[id];return d?`<div class="production-preview">${window.GameAnime?.avatar(id)||A.unitSvg(id)}<span><b>${d.name} · ${d.type}</b><small>¤${d.cost} · ${d.buildTurns} 回合 · 每格 ⚡${d.energyPerStep}</small></span><button data-unit-card="${id}">立绘</button></div>`:'';}
 function productionPreview(id){const el=document.getElementById('production-preview');if(el)el.innerHTML=productionView(id);const b=ui.tile&&ui.game.buildings.find(b=>b.q===ui.tile.q&&b.r===ui.tile.r),button=document.querySelector('[data-action="produce"]');if(b&&button){const reason=G.productionReason(ui.game,b,id);button.disabled=!!reason;button.setAttribute('data-tooltip',reason||'提交生产订单，完工后自动部署；部署格被占用时入库。');}}
 function unitsPage(){const units=D.units.filter(u=>(ui.branch==='all'||u.branch===ui.branch)&&(ui.system==='all'||(ui.system==='special'?!u.system:u.system===ui.system))&&(ui.tier==='all'||u.tier===Number(ui.tier))&&(!ui.query||[u.name,u.type,u.role,u.skill].join(' ').includes(ui.query)));return header('单位图鉴','十个三级体系与八种特殊单位。兵种决定生产体系，当前状态决定攻击权限。')+`<div class="unit-toolbar">${[['all','全部 38'],['army','陆军'],['navy','海军'],['air','空军']].map(([id,n])=>`<button data-branch="${id}" class="${ui.branch===id?'primary':''}">${n}</button>`).join('')}<select id="unit-system" aria-label="单位体系">${opt('all','全部体系',ui.system)}${D.systems.map(s=>opt(s.id,s.name,ui.system)).join('')}${opt('special','八种特殊单位',ui.system)}</select><select id="unit-tier" aria-label="生产等级">${opt('all','全部生产等级',ui.tier)}${[1,2,3].map(n=>opt(String(n),n+'级生产设施',ui.tier)).join('')}</select><input id="unit-search" placeholder="搜索型号、角色或技能" aria-label="搜索单位" value="${esc(ui.query)}" style="max-width:260px"></div><p class="note">筛选结果 ${units.length} / 38；筛选只影响图鉴。</p>${units.some(u=>u.system)?`<h3>主体型号</h3><div class="unit-grid">${units.filter(u=>u.system).map(unitCard).join('')}</div>`:''}${units.some(u=>!u.system)?`<h3>特殊单位</h3><div class="unit-grid">${units.filter(u=>!u.system).map(unitCard).join('')}</div>`:''}`;}
 function rulesPage(){return header('行动手册','规则版本 1.1 · 每条指令统一结算，失败操作不扣资源。')+`<article class="panel rules"><h3>回合与能源</h3><p>每个己方回合先领取已有完好建筑收入，再完成建设、升级和生产，随后部队获得 2 AP、一次反击与一次工程修复机会。移动一次消耗 1 AP，攻击、占领和大多数主动技能消耗 1 AP 后结束该单位行动；应急修复只消耗 1 AP，有剩余 AP 时可继续行动。</p><p>两次移动共用整回合移动预算。全程进入道路的地面部队额外获得 1 点预算，首次进入非道路即失去加成。步兵移动免耗能；两栖轻坦海洋每格 2、陆地每格 1 能源。攻击、反击、生产、单位修复和占领均不耗能源；损毁设施的付费重建需要金钱与能源。</p><h3>攻击与直接反击</h3><p>陆地、海洋、空中是三种当前状态。普通单位可以攻击射程内陆地和海洋目标，只有明确对空能力的单位可以攻击空中。轰炸机能攻击海陆，不能对空。炮兵移动后不能开火；间接火力不触发反击。</p><p>基准伤害 = max(10，基础伤害 + 类别与状态加成 + 技能加成 − 有效装甲 − 掩体)。AI 火力倍率先作用于伤害及加成总和，再扣除目标有效装甲和掩体。直接攻击后，存活目标若具备反击权限且攻击者在其射程内，消耗一次反击次数。普通反击为当前难度计算后伤害的 50%，六种专职防空单位为 150%；不存在周边单位自动拦截或连锁反击。</p><h3>视野、视线与格子</h3><p>山脊和工业废墟遮挡地表直接攻击与观察，空中目标、空军与间接火力忽略地形射线，但攻击必须取得当前视野。盟友共享视野。探明建筑保留最后观测记录，离开视野的敌军不会留下可攻击的图标。</p><p>每格最多一个单位，海陆空均不能叠格或穿过已知单位；建筑与单位可以同格。遇到隐藏阻挡时止步，只扣实际进入格的移动点、能源与一次行动。</p><h3>所有单位都能占领</h3><p>必须进入建筑本格的任意单位，可以接管可见敌方或中立建筑；建筑格内的敌军必须先清除。单位移动到建筑的实际终点后，剩余至少 1 AP 时会自动额外消耗占领行动；经过的建筑不会自动占领。盟友建筑不能被接管。建筑保留等级和当前 HP，原有订单与库存作废。废墟仍登记为胜利目标，需在设施管理中支付金钱与能源重建至50%HP后恢复功能。</p><h3>驻守、建筑损毁与恢复</h3><p>总部、兵营、战车厂、军港和机场有HP。同格友军驻守时，攻击自动命中守军，设施分担基础结算伤害的25%（向下取整，最多分担到剩余HP）；其他伤害由守军承受。反击也遵守分伤规则。城市、贸易站、能源站和海上平台不设HP、不提供庇护，只能占领。</p><p>废墟不会自行恢复。付费重建保留等级，立即恢复最大HP的50%，消耗金钱 ceil(建筑造价×等级/2)、能源 ceil(基础最大HP/20)，总部按240基础造价计算。主动工程修复也不能将设施修复到50%以上，且不能免费重建废墟。每个所属方回合开始，完工且HP大于0的设施自动恢复最大HP的5% / 7.5% / 10%（一级 / 二级 / 三级，向上取整，封顶最大HP）。损毁仍清空订单和库存。</p><h3>建设与生产</h3><p>建设不消耗单位 AP。建筑需位于己方完好总部或城市两格内，普通建筑限平地、道路、海岸；军港必须邻海，能源建筑必须占用对应陆地或海洋能源点。每方同时新建一座建筑。</p><p>设施生产和升级共用一个订单槽位，金钱在下单时支付，取消不退款。库存上限三；在场单位、单位订单与库存合计上限 24。设施记住一个本格或兼容邻格作为部署格，生产完成自动出库。部署格被占用时按生产顺序存储最多三支部队，空出后自动部署队首；其他方回合出库的部队在下一己方回合才获得行动点。设施损毁或易主立即清除订单与库存。</p><h3>多人目标与保存</h3><p>总部模式接管对手原始总部时，使该原始席位出局，清除其部队，其余建筑转为中立。全建筑模式始终统计登记的所有建筑，包括新建、废墟和投降资产。单个总部易主不会使该方出局。</p><p>对局每个完整行动后自动保存，支持命名存档与 JSON 导入导出。地图完整保存，不依赖重新生成。旧 v0.4 工作台缺少完整回合状态，读档会明确提示不兼容。</p><h3>人机难度</h3><p>简单：AI 生命和伤害为基准 85%，装甲为 90%；标准：使用基准数值与常规决策；困难：保持基准数值，加强威胁评估、集火、走位与反制生产；地狱：进一步强化决策，AI 生命和伤害 120%、装甲 110%，初始资源与回合收入 150%。加成只作用于 AI，包括新生产部队；读档不会重复叠加。</p><h3>键盘与操作</h3><p>左键选中己方单位后，直接点击空格移动、敌军攻击、可接管建筑占领；右键也可直接下令，无需确认移动。同格存在多个合法攻击目标时选择目标。技能选择后直接点击目标，生产设施内设置自动部署格，建设规划中选择建筑后直接点击合法格。WASD / 方向键移动镜头，滚轮缩放，空格暂停对局、动画和音效；Tab 聚焦地图格，Enter 选择或下令，Esc 关闭浮层或取消选择。M 移动、F 攻击、C 占领、Q 技能、N 下一支部队、H 总部。</p><div class="actions"><a href="docs/交付索引-v0.9.md" target="_blank">查看设计交付索引 ↗</a>${btn('规则测试场','sandbox')}${ui.game?btn('返回战场','resume','primary'):''}</div></article>`;}
 function savesPage(){const data=S.read();return header('存档管理','保留最近五个自动存档、四个回合起点与十二个命名存档。存档只记录完整行动事务。',ui.game?btn('返回战场','resume','primary'):'')+`<section class="panel"><div class="actions">${ui.game?btn('新建命名存档','save-manual','primary'):''}${ui.game?btn('导出当前对局 JSON','export'):''}<label style="display:inline"><span class="tag">导入 JSON 存档</span><input id="import-save" type="file" accept="application/json,.json" style="margin-top:7px"></label></div></section><div class="cards"><section class="panel"><h3>命名存档</h3><div class="save-list" style="margin-top:16px">${data.manual.map(saveEntry).join('')||'<p class="note">尚无命名存档</p>'}</div></section><section class="panel"><h3>自动保存</h3><div class="save-list" style="margin-top:16px">${data.autos.map(saveEntry).join('')||'<p class="note">尚无自动存档</p>'}</div></section></div><section class="panel" style="margin-top:20px"><h3>回合起点 · 用于重试</h3><div class="save-list" style="margin-top:16px">${data.turnStarts.map(saveEntry).join('')||'<p class="note">开始任务后记录</p>'}</div></section>`;}
 function saveEntry(e){return `<article class="save-entry"><strong>${esc(e.label)}</strong><small>${e.mode==='campaign'?'剧情':'自由'} · ${e.map} · ${sourceName(e.source)} · 第 ${e.round} 轮 · ${e.actor}<br>${goalName(e.goal)} · ${e.team}${e.seed?' · '+esc(e.seed):''}<br>${new Date(e.date).toLocaleString('zh-CN')}</small><div class="actions"><button data-load="${e.id}" class="small">恢复此存档</button><button data-delete="${e.id}" class="small">删除</button></div></article>`;}
 function render(){window.GameTooltips?.hide();document.body.dataset.motionMode=ui.motionMode;app.inert=false;document.querySelector('.masthead').inert=false;const immersive=ui.view==='game'&&ui.game&&(ui.busy||!ui.game.result&&!(ui.game.story?.ending&&!ui.game.story.queue.length));document.body.classList.toggle('in-battle',!!immersive);const pages={home,free,campaign:campaignPage,game:battle,units:unitsPage,rules:rulesPage,saves:savesPage};app.innerHTML=(pages[ui.view]||home)();if(ui.view==='game'){bindBoard();if(!ui.busy){showStory();if(ui.game?.mission&&ui.game.actor==='union'&&C.timeHelp(ui.game)&&!ui.game.story.queue.length&&!ui.dialog){ui.game.story.helpDismissed=true;showHelp();}}}if(ui.dialog){app.inert=true;document.querySelector('.masthead').inert=true;}window.GameTooltips?.prepare(app);updateSoundScene(true);}
 function setGame(s){window.GameAnime?.headings.clear();B.clearTouch?.();settings.difficulty=G.difficulty(s);ui.aiDecision=null;FX.cancel();FX.setPaused(false);B.releaseKeys();ui.busy=false;ui.drawer=null;ui.choices=null;ui.game=s;const restored=G.flushDeployments(s);if(restored.length){s.revision++;G.vision(s);}ui.selected=null;ui.tile=null;ui.intent=null;ui.observer=s.players.find(p=>p.controller==='local_human')?.id;ui.paused=false;ui.view='game';ui.dialog=null;modal.innerHTML='';focusHQ();if(ui.chainAssist&&s.story)C.assist(s);location.hash='game';save({label:'对局开始',turnStart:s.turnStarted});render();}
 function focusHQ(){const s=ui.game,b=G.building(s,G.player(s,viewer()).originalHqId)||s.units[0];if(b){const p=xy(b);ui.camera={...p,width:innerWidth<=760?460:s.mode==='campaign'?1050:1250};}}
 async function act(command,automatic=false){B.clearTouch?.();const s=ui.game;if(!s||ui.busy)return;if(ui.paused){if(!automatic)toast('对局已暂停，请先继续');return;}if(!automatic&&G.player(s).controller!=='local_human'){toast('当前为 AI 行动阶段');return;}const actor=s.actor,index=G.player(s).ownTurnIndex,id=viewer(),before=FX.capture(s,command,id),source=G.unit(s,command.unitId),sourceBuilding=source&&s.buildings.some(b=>b.q===source.q&&b.r===source.r),res=G.execute(s,command);if(!res.ok){if(!automatic){FX.feedback?.('invalid');toast(res.error);}return res;}ui.busy=true;ui.choices=null;if(s.actor!==actor){ui.selected=null;ui.tile=null;ui.intent=null;ui.drawer=null;}else {ui.intent=null;if(!automatic&&source&&G.unit(s,source.id))ui.tile=G.cell(s,G.unit(s,source.id));const selected=G.unit(s,ui.selected);if(ui.selected&&(!selected||!G.visible(s,id,selected)))ui.selected=null;if(command.kind==='construct'||command.kind==='deploy')ui.drawer=null;if(command.kind==='setDeployment'){ui.tile=G.cell(s,G.building(s,command.buildingId));ui.drawer='building';ui.selected=null;}}C.after(s);save({label:automatic?'AI 行动完成':command.kind==='end'?'回合交接':'行动完成',turnStart:s.actor!==actor||G.player(s).ownTurnIndex!==index});render();try{await FX.play({before,after:s,command,board:document.getElementById('board'),viewerId:id,xy,fast:automatic&&ui.fastAI,mode:ui.motionMode,spriteScale:.46,buildingScale:.7,buildingOffset:{x:0,y:-9},unitOffset:{x:-23,y:sourceBuilding?-12:-29}});}catch(err){console.error('动作播放失败',err);}finally{if(ui.game===s){ui.busy=false;render();}}return res;}
 function pickCell(q,r,button='left'){B.pickCell(q,r,button);}
 function bindBoard(){B.bindBoard();}
 function togglePause(){ui.paused=!ui.paused;FX.setPaused(ui.paused);const frame=document.querySelector('.battle-frame');frame?.classList.toggle('is-paused',ui.paused);const banner=document.querySelector('.pause-banner');if(banner)banner.hidden=!ui.paused;const button=document.querySelector('[data-action="pause"]');if(button)button.textContent=ui.paused?'▶ 继续':'Ⅱ 暂停';const end=document.querySelector('.end-turn');if(end)end.disabled=ui.paused||ui.busy||G.player(ui.game).controller!=='local_human';updateSoundScene(true);toast(ui.paused?'对局已暂停 · 空格继续':'对局继续');}
 function dialog(title,body,actions){app.inert=true;document.querySelector('.masthead').inert=true;ui.dialog={title,body,actions};modal.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><h2>${title}</h2>${body}<div class="actions">${actions}</div></section></div>`;window.GameTooltips?.prepare(modal);modal.querySelector('button,input')?.focus();updateSoundScene(true);}
 function closeDialog(){ui.dialog=null;modal.innerHTML='';render();}
 function showStory(){const s=ui.game,id=s?.story?.queue[0];if(!id)return;app.inert=true;document.querySelector('.masthead').inert=true;ui.storyTextComplete=ui.instantText;const scene=GameContent.scenes[id],paragraphs=scene.text.split(/\n\s*\n/).map(p=>p.trim()),buildings=s.map.buildings;const background=`<svg viewBox="0 0 500 90">${Array.from({length:11},(_,i)=>`<path d="M${i*45} 0l45 90m0-90-45 90" stroke="#a8be8e" fill="none"/>`).join('')}<path d="M25 75Q180-10 360 65T480 10" fill="none" stroke="#e3c386" stroke-width="3" stroke-dasharray="7 5"/>${[80,260,420].map(x=>`<circle cx="${x}" cy="45" r="8" fill="#71dabc"/>`).join('')}</svg>`;modal.innerHTML=`<div class="modal-backdrop"><section class="modal story-modal" role="dialog" aria-modal="true" aria-label="剧情 ${id}"><div class="eyebrow">${id} / ${s.mission.region}</div><h2>${esc(scene.title.replace(/^｜/,''))||s.mission.title}</h2><div class="story-screen">${background}<span class="stamp">${s.mission.region} / ${esc(s.mission.storyTime)}</span></div>${paragraphs.map(p=>{const split=p.indexOf('：'),name=split>=0?p.slice(0,split):'电台',text=split>=0?p.slice(split+1):p;return `<div class="dialogue"><div class="portrait" aria-label="${name} 肖像"><img src="assets/units/avatars/${({前哨:'infantry',哨兵:'walker',游隼:'scout',织补:'engineer',雨燕:'lighttank',猎矛:'antitank',浪锋:'marine',涉潮:'amphibious',潮刃:'navaldestroyer',纸鸢:'reconplane',苍隼:'fighter',天幕:'antiair',棱镜:'tank',磐石:'heavy',弧光:'artillery',脉冲:'jammer',巡岚:'cruiser',镇海:'battleship',穹海:'areaaship',远雷:'bomber'})[name]||'infantry'}.png" alt="${name}"></div><div><strong>${esc(name)}</strong><p class="subtitle" data-full="${esc(text)}">${ui.instantText?esc(text):''}</p></div></div>`;}).join('')}<div class="actions">${btn('保存退出','story-exit','small')}${btn('立即显示全文','skip-text','small')}${btn('确认并继续 →','story-confirm','primary')}</div></section></div>`;if(!ui.instantText){let n=0;clearInterval(showStory.timer);showStory.timer=setInterval(()=>{let done=true;for(const el of modal.querySelectorAll('.subtitle')){el.textContent=[...el.dataset.full].slice(0,n).join('');done&&=n>=[...el.dataset.full].length;}n+=2;if(done){ui.storyTextComplete=true;clearInterval(showStory.timer);}},30);}}
 function showHelp(){dialog('参谋建议',C.help(ui.game).map(a=>`<p>${esc(a.text)}</p>`).join('')+`<p class="note">帮助不消耗 AP，不修改战场。你可以读取最近己方回合起点、重新开始本章，或明确选择协同接管。</p>`,btn('关闭','close')+btn('最近己方回合起点','retry-turn')+btn('重试本章','retry')+btn('协同接管','assist','primary'));}
 async function action(name){if(!['touch-confirm','touch-cancel','touch-collapse','touch-map'].includes(name))B.clearTouch?.();const s=ui.game;if(ui.busy&&!['pause','toggle-sound','zoom-in','zoom-out','focus-hq','overview'].includes(name)){toast('行动播放中，请稍候；空格可暂停');return;}if(name.startsWith('drawer-')){ui.drawer=name==='drawer-close'?null:ui.drawer===name.slice(7)?null:name.slice(7);ui.choices=null;if(ui.drawer==='building')ui.intent=null;render();return;}switch(name){
 case 'audio-settings':dialog('视听设置',`<label class="toggle-setting"><input id="battle-sound" type="checkbox" ${ui.sound?'checked':''}> 总声音</label><label>总音量<input id="battle-volume" type="range" min="0" max="100" value="${Math.round(ui.volume*100)}"></label><label class="toggle-setting"><input id="battle-ambience" type="checkbox" ${ui.ambience?'checked':''}> 环境声</label>${B.audioControls()}<p class="meta">配乐与音效在本机播放；设备合成口令默认关闭。</p>`,btn('关闭','close'));break;case 'voice-preview':{let shown=false;const spoken=window.GameAudio?.say(ui.characterId,'selected',{preview:true,onSubtitle:text=>{shown=true;toast(text);}});if(!spoken&&!shown)toast('设备口令未播放：总声音已静音或本机音频 / 中文语音不可用');break;}case 'touch-confirm':B.confirmTouch();break;case 'touch-cancel':B.clearTouch();render();break;case 'touch-collapse':ui.touchCollapsed=!ui.touchCollapsed;render();break;case 'touch-map':ui.touchMap=!ui.touchMap;render();break;case 'toggle-sound':ui.sound=!ui.sound;FX.setSoundEnabled(ui.sound);FX.unlock();savePreferences();if(!ui.busy)render();else {const b=document.querySelector('[data-action="toggle-sound"]');if(b)b.textContent=ui.sound?'♪ 音效':'♪ 静音';}break;
 case 'next-unit':B.nextUnit();break;case 'choices-close':ui.choices=null;render();break;
 case 'build-mode':ui.buildType=document.getElementById('build-type')?.value||ui.buildType;ui.intent='construct';ui.selected=null;ui.tile=null;ui.drawer=null;render();toast('点击合法格直接建设 '+D.buildingById[ui.buildType].name);break;case 'home':case 'free':case 'campaign':case 'units':case 'rules':case 'saves':navigate(name);break;case 'resume':navigate('game');break;case 'latest':{const e=S.read().autos[0];if(e)try{setGame(S.restore(e));}catch(err){toast(err.message);}break;}
  case 'preview':{if(!settings.controllers.slice(0,settings.playerCount).includes('local_human')){toast('请设置至少一位本地人类玩家');break;}try{ui.preview=settings.source==='random'?R.generate(settings):settings.source==='standard'?M.standard():M.fixed(settings.size,settings.playerCount);if(ui.preview.seed)settings.seed=ui.preview.seed;const value=new Uint32Array(1);if(globalThis.crypto?.getRandomValues)crypto.getRandomValues(value);else value[0]=Date.now();ui.previewStart=value[0]%settings.playerCount;render();}catch(e){toast(e.message);}break;}
  case 'copy-seed':try{await navigator.clipboard.writeText(ui.preview.seed);toast('种子已复制');}catch{toast('种子：'+ui.preview.seed);}break;
  case 'start-free':if(!settings.controllers.slice(0,settings.playerCount).includes('local_human')){toast('需要至少一位本地人类玩家');break;}if(!ui.preview){toast('请先生成预览');break;}setGame(G.create(ui.preview,{...settings,startIndex:ui.previewStart,controllers:settings.controllers.slice(0,settings.playerCount),names:settings.names.slice(0,settings.playerCount)}));dialog('六域演习',`<p>共同历 218 年，六域联合演习开始。控制港务、能源与指挥网络，按本局目标完成战场交接。</p><p>${goalName(settings.victoryMode)}。所有 38 种型号可通过生产设施升级解锁。演习记录仅供回顾。</p>`,btn('进入行动阶段','close','primary'));break;
  case 'sandbox':{const field=G.create(M.standard(),{fog:false,controllers:['local_human','local_human'],victoryMode:'own_all_registered_buildings'});field.mode='sandbox';field.map.actualSource='sandbox';field.players.forEach(p=>p.resources={money:2400,energy:200});field.buildings.filter(b=>b.owner&&D.buildingById[b.type].maxLevel===3).forEach(b=>b.level=3);setGame(field);toast('规则测试场：全三级设施，资源可编辑，不计正式完成');break;}
  case 'clear':ui.selected=null;ui.tile=null;ui.intent=null;ui.choices=null;ui.drawer=null;render();break;case 'pause':togglePause();break;case 'handoff':s.handoffRequired=false;ui.observer=s.actor;ui.selected=null;ui.tile=null;ui.intent=null;focusHQ();save({label:'完成设备交接'});render();break;
  case 'intent-move':case 'intent-attack':case 'intent-capture':if(!G.unit(s,ui.selected))break;ui.intent=name.slice(7);ui.drawer=null;ui.tile=null;render();break;case 'intent-skill':{const u=G.unit(s,ui.selected);if(!u)break;const skill=D.byId[u.type].skill;if(['构筑掩体','锚定防线','主动扫描'].includes(skill)){act({kind:'skill',unitId:u.id});}else{ui.intent='skill';ui.drawer=null;ui.tile=null;render();}break;}
  case 'construct':{const type=document.getElementById('build-type').value;act({kind:'construct',type,q:ui.tile.q,r:ui.tile.r});break;}
  case 'set-deployment':{const b=ui.tile&&s.buildings.find(b=>b.q===ui.tile.q&&b.r===ui.tile.r);if(!b||D.buildingById[b.type].group!=='production'){toast('请先打开己方生产设施');break;}const reason=G.facilityReason(s,b);if(reason){toast(reason);break;}ui.facility=b.id;ui.intent='setDeployment';ui.selected=null;ui.tile=null;ui.drawer=null;render();toast('点击高亮的设施格或邻格，设定自动部署位置');break;}
  case 'produce':{const b=ui.tile&&s.buildings.find(b=>b.q===ui.tile.q&&b.r===ui.tile.r);const type=document.getElementById('production-type')?.value;if(!b||!type){toast('没有可生产型号，请检查资金、等级与授权');break;}act({kind:'produce',buildingId:b.id,type});break;}
  case 'sandbox-resources':dialog('测试场资源编辑','<label>当前方金钱（0—3000）<input id="test-money" type="number" min="0" max="3000" value="'+G.player(s).resources.money+'"></label><label>当前方能源（0—300）<input id="test-energy" type="number" min="0" max="300" value="'+G.player(s).resources.energy+'"></label>',btn('取消','close')+btn('应用测试资源','sandbox-apply','primary'));break;case 'sandbox-apply':if(s.mode==='sandbox'){G.player(s).resources={money:Math.max(0,Math.min(3000,Math.floor(Number(document.getElementById('test-money').value)))),energy:Math.max(0,Math.min(300,Math.floor(Number(document.getElementById('test-energy').value))))};save({label:'测试资源修改'});closeDialog();}break;
  case 'zoom-in':ui.camera.width=Math.max(360,ui.camera.width*.8);B.applyCamera();break;case 'zoom-out':ui.camera.width=Math.min(6000,ui.camera.width*1.25);B.applyCamera();break;case 'focus-hq':focusHQ();B.applyCamera();break;case 'overview':{const b=bounds(s.cells),aspect=innerHeight/innerWidth;ui.camera={x:b.x+b.w/2,y:b.y+b.h/2,width:Math.max(b.w,b.h/aspect)*1.12};B.applyCamera();break;}
  case 'pan-left':case 'pan-right':ui.camera.x+=(name==='pan-left'?-1:1)*ui.camera.width*.25;B.applyCamera();break;case 'pan-up':case 'pan-down':ui.camera.y+=(name==='pan-up'?-1:1)*ui.camera.width*.2;B.applyCamera();break;
  case 'save-manual':dialog('命名存档','<label>存档名称<input id="save-label" maxlength="60" value="'+esc(s.mission?.title||'六域演习')+' · 第 '+s.round+' 轮"></label>',btn('取消','close')+btn('保存','save-confirm','primary'));break;case 'save-confirm':save({manual:true,label:document.getElementById('save-label').value.trim()||'命名存档'});ui.dialog=null;modal.innerHTML='';render();toast('存档已保存');break;
  case 'export':{const blob=new Blob([S.exportFile(s)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`六域-${s.map.id}-R${s.round}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}
  case 'surrender':dialog('确认投降',`<p>当前指挥官将出局，部队清除，其余建筑转为中立。本次结果会自动保存。</p>`,btn('继续作战','close')+btn('确认投降','surrender-confirm','danger'));break;case 'surrender-confirm':ui.dialog=null;modal.innerHTML='';act({kind:'surrender'});break;
  case 'help':showHelp();break;case 'assist':dialog('协同接管当前任务','<p>协同部队接替当前战斗，保留停止时的战场记录，补播剩余主线对白并登记交接。此方式不判定为战术胜利，也不颁发战术勋章。</p>',btn('继续作战','close')+btn('确认协同接管','assist-confirm','primary'));break;
  case 'assist-confirm':ui.dialog=null;modal.innerHTML='';C.assist(s);save({label:'协同接管前战场与交接队列'});render();break;
  case 'assist-chain':dialog('协同完成后续主线','<p>后续已解锁关卡将依次通过协同交接继续。所有战前、战中、战后与尾声对白仍需确认；不会发放战术勋章。</p>',btn('取消','close')+btn('确认并从下一未完成章节开始','assist-chain-confirm','primary'));break;
  case 'assist-chain-confirm':{ui.chainAssist=true;const goal=s?.mission?s.settings.victoryMode:document.getElementById('campaign-goal')?.value||'capture_hq';if(s?.story)S.progress(s.story.progress);const progress=S.progress()||C.newProgress(),id=progress.unlocked.find(x=>!progress.completed[x])||progress.unlocked.at(-1);setGame(C.create(id,progress,{victoryMode:goal,difficulty:settings.difficulty}));C.assist(ui.game);render();break;}
  case 'story-exit':save({label:'过场中保存退出'});navigate('home');break;case 'story-confirm':if(!ui.storyTextComplete){clearInterval(showStory.timer);modal.querySelectorAll('.subtitle').forEach(el=>el.textContent=el.dataset.full);ui.storyTextComplete=true;toast('全文已显示，请确认后继续');break;}clearInterval(showStory.timer);C.confirm(s);S.progress(s.story.progress);save({label:'剧情确认',turnStart:s.turnStarted&&s.story.seen.at(-1)===s.mission.scenes.intro});modal.innerHTML='';if(ui.chainAssist&&s.story.ending&&!s.story.queue.length&&s.mission.nextMission){setGame(C.create(s.mission.nextMission,s.story.progress,{victoryMode:s.settings.victoryMode,difficulty:s.settings.difficulty}));C.assist(ui.game);}render();break;
  case 'skip-text':ui.storyTextComplete=true;clearInterval(showStory.timer);modal.querySelectorAll('.subtitle').forEach(el=>el.textContent=el.dataset.full);break;
  case 'retry':ui.chainAssist=false;setGame(C.create(s.mission.id,s.story.progress,{victoryMode:s.settings.victoryMode,difficulty:s.settings.difficulty}));break;case 'retry-turn':{const entry=S.read().turnStarts.find(e=>e.snapshot.mode==='campaign'&&e.snapshot.mission.id===s.mission.id&&e.snapshot.actor==='union');if(entry)setGame(S.restore(entry));else toast('没有本章己方回合起点');break;}
  case 'history':{const progress=s?.story?.progress||S.progress()||C.newProgress();dialog('剧情回顾',progress.seenScenes.map(id=>`<p><button class="small" data-replay="${id}">${id}</button> ${esc(GameContent.scenes[id].title)}</p>`).join('')||'<p>尚未确认任何主线对白。</p>',btn('关闭','close'));break;}
  case 'close':closeDialog();break;
 }}
 document.addEventListener('click',e=>{const el=e.target.closest('button,a,[data-unit-card]');if(!el)return;if(el.matches(':disabled'))return;FX.unlock();if(ui.busy&&!['pause','toggle-sound','zoom-in','zoom-out','focus-hq','overview'].includes(el.dataset.action)){toast('行动播放中，请稍候；空格可暂停');return;}if(el.dataset.focusUnit){B.focusUnit(el.dataset.focusUnit);return;}if(el.dataset.buildType){ui.buildType=el.dataset.buildType;ui.intent='construct';ui.selected=null;ui.tile=null;ui.drawer=null;render();toast('点击合法格直接建设 '+D.buildingById[ui.buildType].name);return;}if(el.dataset.nav){navigate(el.dataset.nav);return;}if(el.dataset.action){action(el.dataset.action).catch(err=>toast(err.message));return;}if(el.dataset.cmd){if(ui.isTouch&&ui.choices){B.previewCommand(JSON.parse(el.dataset.cmd));return;}act(JSON.parse(el.dataset.cmd)).catch(err=>toast(err.message));return;}if(el.dataset.chapter){if(ui.game?.story)S.progress(ui.game.story.progress);const goal=document.getElementById('campaign-goal')?.value||ui.game?.settings.victoryMode||'capture_hq',difficulty=document.getElementById('campaign-difficulty')?.value||settings.difficulty;try{setGame(C.create(el.dataset.chapter,S.progress()||C.newProgress(),{victoryMode:goal,difficulty}));if(ui.chainAssist){C.assist(ui.game);render();}}catch(err){toast(err.message);}return;}if(el.dataset.load){const data=S.read(),entry=[...data.manual,...data.autos,...data.turnStarts].find(x=>x.id===el.dataset.load);try{setGame(S.restore(entry));}catch(err){toast(err.message);}return;}if(el.dataset.delete){S.remove(el.dataset.delete);render();return;}if(el.dataset.stock){ui.facility=el.dataset.facility;ui.stockId=el.dataset.stock;ui.intent='deploy';ui.selected=null;ui.drawer=null;ui.tile=null;render();toast('点击设施或邻格直接部署库存部队');return;}if(el.dataset.branch){ui.branch=el.dataset.branch;render();return;}if(el.dataset.unitCard){const d=D.byId[el.dataset.unitCard];ui.characterId=d.id;dialog(d.type+' · '+d.name,`<div class="character-detail">${window.GameAnime?.portrait(d.id)||A.unitSvg(d.id)}<div><span class="tag">${D.branches[d.branch]} · ${d.category==='armored'?'装甲目标':'轻型目标'} · 全单位占领</span><p>${esc(d.blurb)}</p><p>织星体系 · 成年人工生命 · 型号代表形象</p><img class="chibi-preview" src="assets/units/chibi/${d.id}.png" alt="${d.name} Q版工作姿态">${d.amphibious?`<img class="chibi-preview" src="assets/units/chibi/${d.id}-land.png" alt="${d.name} 陆地形态">`:''}<p>HP ${d.hp} · 装甲 ${d.armor} · 伤害 ${d.damage}<br>射程 ${d.minRange}—${d.maxRange} · 移动 ${d.move} · 视野 ${d.vision}<br>¤${d.cost} · 每格 ⚡${d.energyPerStep} · ${d.buildTurns} 回合生产<br>${D.buildingById[d.facility].name} ${d.tier}级 · ${d.antiAir?'具备对空能力':'对海 / 对陆'}</p><p>${d.skill}：${d.skillText}</p><p>${esc(d.tactic)}</p></div></div>`,btn('试听设备口令','voice-preview')+btn('关闭','close'));return;}if(el.dataset.replay){const scene=GameContent.scenes[el.dataset.replay];dialog(scene.id,scene.text.split(/\n\s*\n/).map(p=>`<p>${esc(p)}</p>`).join(''),btn('返回回顾','history'));}});
 document.addEventListener('input',e=>{const el=e.target;if(el.dataset.audioGroup){window.GameAudio?.setGroup(el.dataset.audioGroup,Number(el.value)/100);FX.refreshAudioGroups?.();}else if(el.id==='battle-volume'){ui.volume=Number(el.value)/100;FX.setVolume(ui.volume);savePreferences();}else if(el.dataset.setting==='seed'){settings.seed=el.value;ui.preview=null;app.querySelector('.preview-grid')?.closest('section')?.remove();}else if(el.dataset.name!==undefined)settings.names[Number(el.dataset.name)]=el.value;});
 document.addEventListener('change',async e=>{const el=e.target;if(el.id==='motion-mode'){ui.motionMode=el.value;document.body.dataset.motionMode=ui.motionMode;savePreferences();}else if(el.id==='battle-music'){window.GameAudio?.setMusic(el.checked);FX.unlock();}else if(el.id==='battle-voice'){window.GameAudio?.setVoice(el.checked);FX.unlock();}else if(el.id==='production-type'){productionPreview(el.value);}else if(el.id==='battle-sound'){ui.sound=el.checked;FX.setSoundEnabled(ui.sound);FX.unlock();savePreferences();render();}else if(el.id==='battle-ambience'){ui.ambience=el.checked;FX.setAmbienceEnabled?.(ui.ambience);FX.unlock();savePreferences();updateSoundScene(true);}else if(el.id==='build-type'){ui.buildType=el.value;}else if(el.id==='campaign-difficulty'){settings.difficulty=el.value;}else if(el.dataset.setting){const field=el.dataset.setting;settings[field]=field==='playerCount'?Number(el.value):field==='fog'?el.value==='true':el.value;if(field==='seed')return;if(field==='size'){const sizes=GameContent.free.sizePresets.find(p=>p.id===settings.size);if(!sizes.allowedPlayers.includes(settings.playerCount))settings.playerCount=sizes.defaultPlayers;}if(field==='source'&&settings.source==='standard')settings.playerCount=2;if(!['ffa',...(settings.playerCount===4?['2v2']:settings.playerCount===6?['3v3','2v2v2']:[])].includes(settings.teams))settings.teams='ffa';if(['size','source','playerCount','landscapeId'].includes(field))ui.preview=null;render();}else if(el.dataset.controller!==undefined){settings.controllers[Number(el.dataset.controller)]=el.value;}else if(el.dataset.name!==undefined){settings.names[Number(el.dataset.name)]=el.value;}else if(el.id==='unit-select'&&el.value){B.focusUnit(el.value);}else if(el.id==='known-target'&&el.value){const b=ui.game.knownBuildings[viewer()][el.value];ui.tile=G.cell(ui.game,b);const p=xy(b);ui.camera.x=p.x;ui.camera.y=p.y;render();}else if(el.id==='instant-text')ui.instantText=el.checked;else if(el.id==='fast-ai'){ui.fastAI=el.checked;savePreferences();}else if(el.id==='unit-system'){ui.system=el.value;render();}else if(el.id==='unit-tier'){ui.tier=el.value;render();}else if(el.id==='unit-search'){ui.query=el.value.trim();render();}else if(el.id==='import-save'&&el.files[0]){try{setGame(S.importFile(await el.files[0].text()));toast('存档导入成功');}catch(err){toast(err.message);}}});
 document.addEventListener('keydown',e=>{if(ui.view==='game')FX.unlock();if(B.keyDown(e))return;if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='Escape'&&!ui.busy&&!ui.game?.story?.queue.length){if(ui.dialog)closeDialog();else {ui.selected=null;ui.intent=null;ui.tile=null;render();}}if(e.key==='Enter'&&e.target.dataset.cell){const [q,r]=e.target.dataset.cell.split(',').map(Number);pickCell(q,r);}if(e.key==='Enter'&&e.target.dataset.unitCard)e.target.click();});
 let last=performance.now(),aiSteps=0,aiActor=null,lastTick=0;setInterval(()=>{const now=performance.now(),elapsed=now-last;last=now;const s=ui.game;if(!s||ui.paused||document.hidden||s.handoffRequired)return;const finished=s.story?s.story.ending&&!s.story.queue.length:!!s.result;if(!finished&&ui.view==='game'&&!ui.dialog)s.activeMillis+=elapsed;if(ui.view==='game'&&!ui.dialog&&s.story&&!s.story.progress.complete)s.story.progress.activeMillis+=elapsed;if(ui.view!=='game'||ui.busy||finished||s.story?.queue.length||ui.dialog||ui.drawer||s.result||s.story?.combatLocked)return;if(G.player(s).controller!=='ai'){if(s.story&&C.timeHelp(s)){s.story.helpDismissed=true;showHelp();}return;}if(now-lastTick<(ui.fastAI?80:550))return;lastTick=now;if(aiActor!==s.actor){aiActor=s.actor;aiSteps=0;}if(aiSteps++>130){aiSteps=0;act({kind:'end'},true).catch(err=>toast(err.message));}else {const decision=GameAI.decision(s);ui.aiDecision={...GameAI.forViewer(s,decision,viewer()),actor:s.actor};const command=decision.command||{kind:'end'};act(command,true).then(outcome=>{if(!outcome?.ok&&ui.game===s&&!ui.busy)act({kind:'end'},true);}).catch(err=>toast(err.message));}},100);

 window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(['home','free','campaign','game','units','rules','saves'].includes(view)&&view!==ui.view)navigate(view==='game'&&!ui.game?'home':view);});
 document.addEventListener('visibilitychange',()=>{B.clearTouch?.();window.GameAudio?.setHidden(document.hidden);if(document.hidden)FX.cancel();updateSoundScene(true);});
 window.addEventListener('pagehide',()=>{FX.cancel();FX.setScene?.({terrain:'plain',active:false});B.releaseKeys();if(ui.game)save({label:'关闭页面前保存'});});
 const hash=location.hash.slice(1);ui.view=['units','rules','saves','campaign','free'].includes(hash)?hash:'home';render();
})();
